#pragma once

namespace Hitman::BloodMoney
{
    enum EHM3Action {
        eNone = 0,
        eCancel = 1,
        eOpenDoor = 2,
        eCloseDoor = 3,
        eLockDoor = 4,
        eUnLockDoor = 5,
        ePickLock = 6,
        eStrangle = 7,
        eHackSlash = 8,
        ePushPerson = 9,
        eReload = 10,
        eCombine = 11,
        eDrop = 12,
        eThrow = 13,
        eHolster = 14,
        eLookKeyhole = 15,
        ePickup = 16,
        eChangeClothes = 17,
        eTalk = 18,
        eHumanShield = 19,
        eHumanShieldRelease = 20,
        eDragBody = 21,
        ePutInSuitcase = 22,
        eConcealWeapon = 23,
        eHideWeapon = 24,
        eHideInCloset = 25,
        eDropBody = 26,
        eOpenLid = 27,
        eCloseLid = 28,
        eUseKeyCard = 29,
        eGrab = 30,
        eRelease = 31,
        eClimbHatch = 32,
        eStrangleInElevator = 33,
        ePutItemElevator = 34,
        ePlaceItem = 35,
        ePlaceBomb = 36,
        eRetrieveItem = 37,
        eJumpBalcony = 38,
        eActionKill = 39,
        eElevatorButton = 40,
        ePlace = 41,
        eRetrieve = 42,
        eUseSwitch = 43,
        eGeneric = 44,
        eHideBodyOnTable = 45,
        ePlaceItemToPos = 46,
        eHitmanUseWeaponStorage = 47,
        eBreakUtilBox = 48,
        eUseLightSwitch = 49,
        eUseFireAlarm = 50,
        eExitKeyhole = 51,
        eExitCloset = 52,
        eSurrendWeapon = 53,
        eStealTape = 54,
        eADisposeBodyToDumpster = 55,
        eADisposeBodyToCrate = 56,
        eADisposeBodyGarbageTruck = 57,
        eAThrowRail = 58,
        eAThrowChute = 59,
        eLast = 60,
    };

}