#include <Glacier/ReGlacier.h>
#include <Glacier/ScriptEngine/Globals.h>
#include <SI/SI.h>
#include <SI/SI_ZCar.h>
#include <SI/SI_ZHM3Actor.h>
#include <SI/SI_ZLink.h>
#include <SI/SI_Coverlist.h>
#include <SI/SI_Zgeom.h>
#include <SI/SI_Zhm3Boid.h>
#include <SI/SI_M12LevelcontrolExtra.h>
#include <SI/SI_Holevelcontrol.h>
#include <SI/SI_Bloodtrail.h>
#include <SI/SI_Cigs.h>
#include <SI/SI_Zlist.h>
#include <SI/SI_Debugfunctions.h>
#include <SI/SI_Physics.h>
#include <SI/SI_Audio.h>
#include <SI/SI_Math.h>
#include <SI/SI_Istring.h>
#include <SI/SI_Pathfinder.h>


namespace Glacier
{
    static SI::ScriptInterfacesTable ScriptInterfacesDefault = {
        &Zcar__Moveto, // 0
        &Zcar__Setspeedmultiplier, // 1
        &Zcar__Settargetspeedmultiplier, // 2
        &Zcar__Getpathendpoint, // 3
        &Zcar__Getpathstartpoint, // 4
        &Zcar__Setpath, // 5
        &Zcar__Getposobj, // 6
        &Zcar__Attachactortoseat, // 7
        &Zcar__Detachactorfromseat, // 8
        &Zcar__Stop, // 9
        &Zcar__Tempstop, // 10
        &Zcar__Continue_, // 11
        &Zcar__Hithitman, // 12
        &Zcar__Setcarposdir, // 13
        &Zlink__Stopallanims, // 14
        &Zlink__Stopubanims, // 15
        &Zlink__Getanim, // 16
        &Zlink__Checkanimrunning, // 17
        &Zlink__Getnumberofframes, // 18
        &Zlink__Playanimsegment, // 19
        &Zlink__Canplayanim, // 20
        &Zlink__Canplayanimsegment, // 21
        &Zlink__Playaniminterpolated, // 22
        &Zlink__Setactiveanimdest, // 23
        &Zlink__Getactiveanimdest, // 24
        &Zlink__Lockfacing, // 25
        &Zlink__Getmetakeyframenr, // 26
        &Zlink__Getmetakeynrframenr, // 27
        &Zlink__Getanimendpoint, // 28
        &Zlink__Getmetakeyframenrfrommetastring, // 29
        &Zlink__Setholdweaponubanim, // 30
        &Zhm3Actor__Setblinking, // 31
        &Zhm3Actor__Initmapicon, // 32
        &Zhm3Actor__Forceshowmapicon, // 33
        &Zhm3Actor__Die, // 34
        &Zhm3Actor__Initializehitpoints, // 35
        &Zhm3Actor__Sethitpoints, // 36
        &Zhm3Actor__Setcharactertype, // 37
        &Zhm3Actor__Getcharactertype, // 38
        &Zhm3Actor__Changemapiconandcharactertype, // 39
        &Zhm3Actor__Removefrommap, // 40
        &Zhm3Actor__Gethitpoints, // 41
        &Zhm3Actor__Takedamage, // 42
        &Zhm3Actor__Setleavebloodtrail, // 43
        &Zhm3Actor__Setvisionrangesandfovs, // 44
        &Zhm3Actor__Setvisionrangeandfov, // 45
        &Zhm3Actor__Setmood, // 46
        &Zhm3Actor__Gettension, // 47
        &Zhm3Actor__Settension, // 48
        &Zhm3Actor__Increasetension, // 49
        &Zhm3Actor__Releasetension, // 50
        &Zhm3Actor__Getmaxneed, // 51
        &Zhm3Actor__Setneed, // 52
        &Zhm3Actor__Setneedtime, // 53
        &Zhm3Actor__Getneed, // 54
        &Zhm3Actor__Lockubanim, // 55
        &Zhm3Actor__Enableubholdanims, // 56
        &Zhm3Actor__Disableubholdanims, // 57
        &Zhm3Actor__Enableubholdanim, // 58
        &Zhm3Actor__Isubanimlocked, // 59
        &Zhm3Actor__Setscriptubanim, // 60
        &Zhm3Actor__Resetscriptubanim, // 61
        &Zhm3Actor__Playscriptubanim, // 62
        &Zhm3Actor__Playscriptubanimloop, // 63
        &Zhm3Actor__Stopscriptubanimplay, // 64
        &Zhm3Actor__Hasrunningubanim, // 65
        &Zhm3Actor__Setweapontemplate, // 66
        &Zhm3Actor__Getweapontemplate, // 67
        &Zhm3Actor__Setweapon, // 68
        &Zhm3Actor__Resetweapon, // 69
        &Zhm3Actor__Getweapon, // 70
        &Zhm3Actor__Setammoinweapon, // 71
        &Zhm3Actor__Pullweapon, // 72
        &Zhm3Actor__Ownsownweapon, // 73
        &Zhm3Actor__Isweapondrawn, // 74
        &Zhm3Actor__Currentweaponcanbeholstered, // 75
        &Zhm3Actor__Holsterweapon, // 76
        &Zhm3Actor__Isholdingitem, // 77
        &Zhm3Actor__Hasfreehand, // 78
        &Zhm3Actor__Islinkactionrunning, // 79
        &Zhm3Actor__Putiteminrightpocket, // 80
        &Zhm3Actor__Putiteminleftpocket, // 81
        &Zhm3Actor__Pullitemfromrightpocket, // 82
        &Zhm3Actor__Pullitemfromleftpocket, // 83
        &Zhm3Actor__Setisholdingshootableiteml, // 84
        &Zhm3Actor__Setisholdingshootableitemr, // 85
        &Zhm3Actor__Makeitemvisible, // 86
        &Zhm3Actor__Makeiteminvisible, // 87
        &Zhm3Actor__Makeactorvisible, // 88
        &Zhm3Actor__Makeactorinvisible, // 89
        &Zhm3Actor__Removedecal, // 90
        &Zhm3Actor__Setvisibletypes, // 91
        &Zhm3Actor__Getvisibletypes, // 92
        &Zhm3Actor__Setseerblind, // 93
        &Zhm3Actor__Disablevision, // 94
        &Zhm3Actor__Enablevision, // 95
        &Zhm3Actor__Disablepickupclothes, // 96
        &Zhm3Actor__Enablepickupclothes, // 97
        &Zhm3Actor__Getvisibleprojectileweapons, // 98
        &Zhm3Actor__Isitemedible, // 99
        &Zhm3Actor__Isitemdrinkable, // 100
        &Zhm3Actor__Getitemnumbitestotal, // 101
        &Zhm3Actor__Getitemnumbites, // 102
        &Zhm3Actor__Removeitembite, // 103
        &Zhm3Actor__Restoreitembites, // 104
        &Zhm3Actor__Getiteminfectiontype, // 105
        &Zhm3Actor__Aimweaponatgeom, // 106
        &Zhm3Actor__Aimweaponatpos, // 107
        &Zhm3Actor__Fireweapon, // 108
        &Zhm3Actor__Playfireweaponsound, // 109
        &Zhm3Actor__M12_Albinofireweapon, // 110
        &Zhm3Actor__Triggerweaponpush, // 111
        &Zhm3Actor__Isaiminposition, // 112
        &Zhm3Actor__Isaimingattarget, // 113
        &Zhm3Actor__Reloadweapon, // 114
        &Zhm3Actor__Numberofshotsleft, // 115
        &Zhm3Actor__Isbodyknownandunchanged, // 116
        &Zhm3Actor__Registerdeadbody, // 117
        &Zhm3Actor__Isobjectvisible, // 118
        &Zhm3Actor__Objectisinfront, // 119
        &Zhm3Actor__Chkcolibeforeactor, // 120
        &Zhm3Actor__Isitemininventory, // 121
        &Zhm3Actor__Additemtoinventory, // 122
        &Zhm3Actor__Removeitemfrominventory, // 123
        &Zhm3Actor__Dumpinventorytoground, // 124
        &Zhm3Actor__Undress, // 125
        &Zhm3Actor__Dress, // 126
        &Zhm3Actor__Dialoglisten, // 127
        &Zhm3Actor__Dialogtalk, // 128
        &Zhm3Actor__Throwknifeatref, // 129
        &Zhm3Actor__Findsitdowngeom, // 130
        &Zhm3Actor__Sitdown, // 131
        &Zhm3Actor__Sitdowninstant, // 132
        &Zhm3Actor__Movechairifapplicable, // 133
        &Zhm3Actor__Movechair, // 134
        &Zhm3Actor__Situp, // 135
        &Zhm3Actor__Findliedowngeom, // 136
        &Zhm3Actor__Liedown, // 137
        &Zhm3Actor__Findlightswitch, // 138
        &Zhm3Actor__Togglelightswitch, // 139
        &Zhm3Actor__Getlightswitchstate, // 140
        &Zhm3Actor__Getbodyposition, // 141
        &Zhm3Actor__Setbodyposition, // 142
        &Zhm3Actor__Setbodypositionunknown, // 143
        &Zhm3Actor__Setbodypositionnormal, // 144
        &Zhm3Actor__Sethmescort, // 145
        &Zhm3Actor__Gethmescort, // 146
        &Zhm3Actor__Playsound, // 147
        &Zhm3Actor__Isweaponallowed, // 148
        &Zhm3Actor__Isweaponfoundathitman, // 149
        &Zhm3Actor__Transferhitmanweaponstoactor, // 150
        &Zhm3Actor__Isonback, // 151
        &Zhm3Actor__Setneardeath, // 152
        &Zhm3Actor__Dropbloodstain, // 153
        &Zhm3Actor__Activatebloodspurt, // 154
        &Zhm3Actor__Wantbloodstain, // 155
        &Zhm3Actor__Setwantbloodonhit, // 156
        &Zhm3Actor__Isactor, // 157
        &Zhm3Actor__Ishitmandraggingactor, // 158
        &Zhm3Actor__Iswearingclothes, // 159
        &Zhm3Actor__Getoriginalsuit, // 160
        &Zhm3Actor__Getflankingpos, // 161
        &Zhm3Actor__Getbodycheckposdir, // 162
        &Zhm3Actor__Getposonpath, // 163
        &Zhm3Actor__Blowhitmandisguise, // 164
        &Zhm3Actor__Generateaudioevent, // 165
        &Zhm3Actor__Playactorspeech, // 166
        &Zhm3Actor__Playresourceasspeech, // 167
        &Zhm3Actor__Playlocaleresourceasspeech, // 168
        &Zhm3Actor__Getlocalesoundresource, // 169
        &Zhm3Actor__Playrandomlocaleresourceasspeech, // 170
        &Zhm3Actor__Isspeechplaying, // 171
        &Zhm3Actor__Stopspeech, // 172
        &Zhm3Actor__Bite, // 173
        &Zhm3Actor__Punch, // 174
        &Zhm3Actor__Stungunattack, // 175
        &Zhm3Actor__Activaterigidbody, // 176
        &Zhm3Actor__Userigidbodyonpush, // 177
        &Zhm3Actor__Useubragdoll, // 178
        &Zhm3Actor__Dragbody, // 179
        &Zhm3Actor__Actorbeingpushed, // 180
        &Zhm3Actor__Isactorbeingkilled, // 181
        &Zhm3Actor__Changeintobodybag, // 182
        &Zhm3Actor__Isbodybag, // 183
        &Zhm3Actor__Maybebodybagged, // 184
        &Zhm3Actor__Setmaybebodybagged, // 185
        &Zhm3Actor__Setignorehelprequests, // 186
        &Zhm3Actor__Setissearching, // 187
        &Zhm3Actor__Disabledrag, // 188
        &Zhm3Actor__Getnumberofavailableragdolls, // 189
        &Zhm3Actor__Setactorspecies, // 190
        &Zhm3Actor__Sendeventtoactorswithinbox, // 191
        &Zhm3Actor__Playanimwithcamerabone, // 192
        &Zhm3Actor__Findclosestcharactertype, // 193
        &Zhm3Actor__Disableragdollanddieanim, // 194
        &Zhm3Actor__Dummy, // 195
        &Zhm3Actor__Repairutilbox, // 196
        &Zhm3Actor__Terminatecurrentlnkaction, // 197
        &Zhm3Actor__Getsecuritydeviceloopingsound, // 198
        &Zhm3Actor__Getsecuritydeviceweaponfoundsound, // 199
        &Zhm3Actor__Activateragdollnextframe, // 200
        &Zhm3Actor__Activateragdoll, // 201
        &Zhm3Actor__Hitragdoll, // 202
        &Zhm3Actor__Ishitmanvisible, // 203
        &Zhm3Actor__Setignoredisguise, // 204
        &Zhm3Actor__Isignoredisguise, // 205
        &Zhm3Actor__Canplayanimpf, // 206
        &Zhm3Actor__Setposdiractor, // 207
        &Zhm3Actor__Calculatestopdistancetoavoidobstacle, // 208
        &Zhm3Actor__Setinterruptable, // 209
        &Zhm3Actor__Positionlock, // 210
        &Zhm3Actor__Positionunlock, // 211
        &Zhm3Actor__Isanimubanim, // 212
        &Zhm3Actor__Getangletoactor2, // 213
        &Zhm3Actor__Addmouthemitter, // 214
        &Zhm3Actor__Removemouthemitter, // 215
        &Zhm3Actor__Onpickupitem, // 216
        &Zhm3Actor__Isenteringorleavingelevator, // 217
        &Zhm3Actor__Isinorusingelevator, // 218
        &Zhm3Actor__Isinoutsidelocation, // 219
        &Zhm3Actor__Isinelevator, // 220
        &Zhm3Actor__Getelevatorhatchgeom, // 221
        &Zhm3Actor__Broadcasttoothersinelevator, // 222
        &Zhm3Actor__Isaccidentkilled, // 223
        &Zhm3Actor__Ispointinsideelevatorarea, // 224
        &Zhm3Actor__Setsuspectedsuit, // 225
        &Zhm3Actor__Ishitmanhidingbehindnextdoor, // 226
        &Zhm3Actor__Idlelookat, // 227
        &Zhm3Actor__Setdisableragdollforshots, // 228
        &Zactor__Setscriptpaused, // 229
        &Zactor__Setmoveset, // 230
        &Zactor__Stopmovementatdistance, // 231
        &Zactor__Setmovespeedmultiplier, // 232
        &Zactor__Getactorspeed, // 233
        &Zactor__Dontstop, // 234
        &Zactor__Movetoposq, // 235
        &Zactor__Movetolocationq, // 236
        &Zactor__Stoppath, // 237
        &Zactor__Setstopdistance, // 238
        &Zactor__Setpathnotify, // 239
        &Zactor__Setupdateposition, // 240
        &Zactor__Lockmovement, // 241
        &Zactor__Unlockmovement, // 242
        &Zactor__Clearreservation, // 243
        &Zactor__Ignorereservations, // 244
        &Zactor__Usereservations, // 245
        &Zactor__Isragdollactive, // 246
        &Zactor__Isdead, // 247
        &Zactor__Isunconscious, // 248
        &Zactor__Isawake, // 249
        &Zactor__Getactorstate, // 250
        &Zactor__Setawake, // 251
        &Zactor__Setunconscious, // 252
        &Zactor__Setsleeping, // 253
        &Zactor__Setdead, // 254
        &Zactor__Lookat, // 255
        &Zactor__Getlookat, // 256
        &Zactor__Enablelookat, // 257
        &Zactor__Islookatenabled, // 258
        &Zactor__Setactorposdir, // 259
        &Zactor__Copytoref, // 260
        &Zactor__Setvisfov, // 261
        &Zactor__Isonstairs, // 262
        &Zactor__Setshootintoground, // 263
        &Zactor__Setshootintogroundinfullbody, // 264
        &Zactor__Getboidspeed, // 265
        &Zactor__Inactivateboid, // 266
        &Zactor__Placeactorinmovinggroup, // 267
        &Zactor__Removeactorfrommovinggroup, // 268
        &Zactor__Getnumoftransitions, // 269
        &Zactor__Setnumoftransitions, // 270
        &Zactor__Setfootwearmaterial, // 271
        &Zactor__Setmovepoolweight, // 272
        &Zactor__Sethandtarget, // 273
        &Zactor__Getvariant, // 274
        &Zactor__Setvariant, // 275
        &Zactor__Addtoforcedrawoffscreenlist, // 276
        &Zactor__Removefromforcedrawoffscreenlist, // 277
        &Zactor__Turnactor, // 278
        &Zactor__Setcanopendoors, // 279
        &Hm3Gui__Displayinfo, // 280
        &Hm3Gui__Displaypipinfo, // 281
        &Hm3Gui__Displaywarning, // 282
        &Hm3Gui__Displaypipwarning, // 283
        &Hm3Gui__Displayhint, // 284
        &Hm3Gui__Displaysubtitle, // 285
        &Hm3Gui__Displaysubtitletimed, // 286
        &Silevelcontrol__Missioncompleted, // 287
        &Silevelcontrol__Missionfailed, // 288
        &Silevelcontrol__Characterkilled, // 289
        &Silevelcontrol__Characterharmed, // 290
        &Silevelcontrol__Completeobjective, // 291
        &Silevelcontrol__Completeobjectivenotickoffmark, // 292
        &Silevelcontrol__Uncompleteobjective, // 293
        &Silevelcontrol__Hideobjective, // 294
        &Silevelcontrol__Unhideobjective, // 295
        &Silevelcontrol__Isobjectivecompleted, // 296
        &Silevelcontrol__Changeobjectivetext, // 297
        &Silevelcontrol__Clearchangedobjectivetext, // 298
        &Silevelcontrol__Changeobjectivepath, // 299
        &Silevelcontrol__Clearchangedobjectivepath, // 300
        &Silevelcontrol__Getlevelcontrol, // 301
        &Silevelcontrol__Gethitman, // 302
        &Silevelcontrol__Ishitmanrecognizable, // 303
        &Silevelcontrol__Killhitman, // 304
        &Silevelcontrol__Getnotoriety, // 305
        &Silevelcontrol__Getcoverlist, // 306
        &Silevelcontrol__Start_Actorinvestigatehitman, // 307
        &Silevelcontrol__End_Actorinvestigatehitman, // 308
        &Silevelcontrol__Getdifficultysettings, // 309
        &Silevelcontrol__Getdifficulty, // 310
        &Silevelcontrol__Ishitmantrespassing, // 311
        &Silevelcontrol__Ishitmaninoutsidelocation, // 312
        &Silevelcontrol__Iscontainerallowedhere, // 313
        &Silevelcontrol__Gethumanshieldtarget, // 314
        &Silevelcontrol__Gethitmanhidecloset, // 315
        &Silevelcontrol__Getcurrentvictim, // 316
        &Silevelcontrol__Ishitmanincloset, // 317
        &Silevelcontrol__Killhitmanincloset, // 318
        &Silevelcontrol__Getdoorpickedbyhm, // 319
        &Silevelcontrol__Ishitmanlockpicking, // 320
        &Silevelcontrol__Ishitmanloookingthroughkeyhole, // 321
        &Silevelcontrol__Ishitmanthrowingstuff, // 322
        &Silevelcontrol__Subscribehitmanchangeclothes, // 323
        &Silevelcontrol__Getcurrenthitmansuit, // 324
        &Silevelcontrol__Ishitmanwearinghitmansuit, // 325
        &Silevelcontrol__Getcurrenthitmanlefthanditem, // 326
        &Silevelcontrol__Getcurrenthitmanweapontemplate, // 327
        &Silevelcontrol__Getactorfriskinghm, // 328
        &Silevelcontrol__Setactorfriskinghm, // 329
        &Silevelcontrol__Getfriskoperation, // 330
        &Silevelcontrol__Setfriskoperation, // 331
        &Silevelcontrol__Getcurrentzone, // 332
        &Silevelcontrol__Starteventcamera, // 333
        &Silevelcontrol__Starteventcameralookatgeom, // 334
        &Silevelcontrol__Starteventcamerawithcameraboneanim, // 335
        &Silevelcontrol__Endeventcamera, // 336
        &Silevelcontrol__Getguardsfriskbox, // 337
        &Silevelcontrol__Hashmweaponinhand, // 338
        &Silevelcontrol__Incfriskfails, // 339
        &Silevelcontrol__Incheadshots, // 340
        &Silevelcontrol__Inctargetspoisoned, // 341
        &Silevelcontrol__Incsedates, // 342
        &Silevelcontrol__Incimpersonations, // 343
        &Silevelcontrol__Incpusheddeath, // 344
        &Silevelcontrol__Inctargetssniped, // 345
        &Silevelcontrol__Incbodiesfound, // 346
        &Silevelcontrol__Incsedatedbodiesfound, // 347
        &Silevelcontrol__Incbloodtrailsfound, // 348
        &Silevelcontrol__Incclosecombatkill, // 349
        &Silevelcontrol__Incaccidentkill, // 350
        &Silevelcontrol__Incaccidentkillignoredamage, // 351
        &Silevelcontrol__Setchangeclothesallowed, // 352
        &Silevelcontrol__Caughtontape, // 353
        &Silevelcontrol__Tapestolen, // 354
        &Silevelcontrol__Weaponused, // 355
        &Silevelcontrol__Settargetnum, // 356
        &Silevelcontrol__Gethminventoryitem, // 357
        &Silevelcontrol__Isitemtemplateinhminventory, // 358
        &Silevelcontrol__Isiteminhminventory, // 359
        &Silevelcontrol__Copyhmtoref, // 360
        &Silevelcontrol__Audioaddpauseobject, // 361
        &Silevelcontrol__Starteventmusic, // 362
        &Silevelcontrol__Createsecuritydevicefromtemplate, // 363
        &Silevelcontrol__Getsuitcaseinhitmanshand, // 364
        &Silevelcontrol__Isdooropen, // 365
        &Silevelcontrol__Isdoorlocked, // 366
        &Silevelcontrol__Getclosestposter, // 367
        &Silevelcontrol__Getreachablehitmanpfpos, // 368
        &Silevelcontrol__Getclosestexitposforclimbinghitman, // 369
        &Silevelcontrol__Ishitmaninreachableposition, // 370
        &Silevelcontrol__Ishitmaninsidepathfinder, // 371
        &Silevelcontrol__Forcecloselasthitmandoor, // 372
        &Silevelcontrol__Ishitmaninelevator, // 373
        &Silevelcontrol__Ishitmantopofelevator, // 374
        &Silevelcontrol__Showonmap, // 375
        &Silevelcontrol__Isactorinwaterbox, // 376
        &Silevelcontrol__Remove_Existing_Eventcam, // 377
        &Pathfollower__Ispathfollowervalid, // 378
        &Pathfollower__Numwaypointlists, // 379
        &Pathfollower__Setwaypointindex, // 380
        &Pathfollower__Useclosestonstart, // 381
        &Pathfollower__Getnextwaypoint, // 382
        &Pathfollower__Setwaypointlist, // 383
        &Pathfollower__Getcurrentwaypointlist, // 384
        &Pathfollower__Setexternalwaypointlist, // 385
        &Pathfollower__Setpathtype, // 386
        &Pathfollower__Getpathtype, // 387
        &Pathfollower__Getusewalk, // 388
        &Pathfollower__Getplayanimswhilewalking, // 389
        &Hm3Weapon__Getweapontemplate, // 390
        &Hm3Weapon__Getweapontype, // 391
        &Hm3Weapon__Gettimebetweenshots, // 392
        &Hm3Weapon__Getweaponoperations, // 393
        &Hm3Weapon__Weaponfiresprojectiles, // 394
        &Hm3Weapon__Getprojectilesinmagazine, // 395
        &Hm3Weapon__Emptyweapon, // 396
        &Hm3Weapon__Setprojectilesinmagazine, // 397
        &Hm3Weapon__Weaponissmall, // 398
        &Hm3Weapon__Issniper, // 399
        &Hm3Weapon__Isdetectable, // 400
        &Coverlist__Releasecover, // 401
        &Coverlist__Checkcoverfrompos, // 402
        &Coverlist__Getbestcoverfrompos, // 403
        &Coverlist__Getbestcover, // 404
        &Coverlist__Getcoverindexesaroundpos, // 405
        &Coverlist__Getpisscover, // 406
        &Coverlist__Getpissposdir, // 407
        &Coverlist__Getcoverposdir, // 408
        &Coverlist__Getcoverposdir_Pos, // 409
        &Coverlist__Getcoverposition, // 410
        &Coverlist__Getshootposdir, // 411
        &Coverlist__Getshootposdir_Pos, // 412
        &Coverlist__Getintermediateposition, // 413
        &Actorcommunication__Registerradiouser, // 414
        &Actorcommunication__Sendradiomessage, // 415
        &Actorcommunication__Sendradiomessagetoclosestn, // 416
        &Actorcommunication__Sendradiomessagetoneedeforce, // 417
        &Actorcommunication__Sendrangedmessage, // 418
        &Actorcommunication__Sendglobalevent, // 419
        &Actorcommunication__Sendeventtoactorsinbox, // 420
        &Actorcommunication__Sendeventtoactorsinbox2, // 421
        &Fightcontroller__Attackingtarget, // 422
        &Fightcontroller__Requestcoverfire, // 423
        &Fightcontroller__Huntingtarget, // 424
        &Fightcontroller__Standby, // 425
        &Fightcontroller__Updatetargetinfo, // 426
        &Fightcontroller__Signoff, // 427
        &Fightcontroller__Querytarget, // 428
        &Fightcontroller__Querytargetclose, // 429
        &Fightcontroller__Queryshouldattack, // 430
        &Fightcontroller__Iscombathappening, // 431
        &Fightcontroller__Requestnewposition, // 432
        &Guardquartercontroller__Initializeweaponstorage, // 433
        &Guardquartercontroller__Registeractor, // 434
        &Guardquartercontroller__Delegatetask, // 435
        &Guardquartercontroller__Taskdone, // 436
        &Guardquartercontroller__Accepttask, // 437
        &Guardquartercontroller__Actornotavailable, // 438
        &Guardquartercontroller__Getclosestbodybagbox, // 439
        &Guardquartercontroller__Decreasebodybagboxcapacity, // 440
        &Guardquartercontroller__Canaddweapontostorage, // 441
        &Guardquartercontroller__Placeweaponinstorage, // 442
        &Guardquartercontroller__Removeweaponfromstorage, // 443
        &Guardquartercontroller__Getstorageposdirref, // 444
        &Guardquartercontroller__Isweaponinstorage, // 445
        &Guardquartercontroller__Getweaponreffromstorage, // 446
        &Dialog__Startdialog, // 447
        &Dialog__Startonelinerdialog, // 448
        &Dialog__Startonelinerdialognoturn, // 449
        &Dialog__Pushdialogcamera, // 450
        &Dialog__Popdialogcamera, // 451
        &Dialog__Startdialogex, // 452
        &Dialog__Isplaying, // 453
        &Dialog__Setnotifytarget, // 454
        &Dialog__Stopdialog, // 455
        &Dialog__Actorplaynextdialog, // 456
        &Dialog__Setdialogskipable, // 457
        &Dialog__Sethmposbeforedialog, // 458
        &Zusepoint__Lock, // 459
        &Zusepoint__Unlock, // 460
        &Zusepoint__Changeprobability, // 461
        &Zusepoint__Relocate, // 462
        &Zusepoint__Islocked, // 463
        &Zgeom__Getsize, // 464
        &Zgeom__Setposition, // 465
        &Zgeom__Getposition, // 466
        &Zgeom__Getlocalpoint, // 467
        &Zgeom__Getposdir, // 468
        &Zgeom__Setposdir, // 469
        &Zgeom__Getclosestposdirinbox, // 470
        &Zgeom__Getdistancetoobject, // 471
        &Zgeom__Getdistancetopos, // 472
        &Zgeom__Hascontroller, // 473
        &Zgeom__Getcontroller, // 474
        &Zgeom__Getangletoobject, // 475
        &Zgeom__Getangletodir, // 476
        &Zgeom__Getangletogeomdir, // 477
        &Zgeom__Copyobjectposdir, // 478
        &Zgeom__Copyobjectpos, // 479
        &Zgeom__Copyobjectdir, // 480
        &Zgeom__Getobjectrelpos, // 481
        &Zgeom__Checkworldpointinside, // 482
        &Zgeom__Isinview, // 483
        &Zgeom__Printname, // 484
        &Zgeom__Getdistancetoitem, // 485
        &Zgeom__Makeinactive, // 486
        &Zgeom__Makeactive, // 487
        &Zgeom__Hide, // 488
        &Zgeom__Getcurrentroom, // 489
        &Zgeom__Numberofexitsfromgeomscurrentroom, // 490
        &Zhm3Boid__Die, // 491
        &Zhm3Boid__Getdistancefrombonetoobject, // 492
        &Zhm3Boid__Getfacing, // 493
        &Zhm3Boid__Disableboid, // 494
        &Zhm3Boid__Shootintoground, // 495
        &Zhm3Boid__Disableallbehaviors, // 496
        &Zhm3Boid__Updatelocalspace, // 497
        &Zhm3Boid__Setminmaxspeed, // 498
        &Zhm3Boid__Resetspeed, // 499
        &Zhm3Boid__Setminmaxforce, // 500
        &Zhm3Boid__Setvisionrangeandangle, // 501
        &Zhm3Boid__Applyconstantforce, // 502
        &Zhm3Boid__Enablebanking, // 503
        &Zhm3Boid__Setforceconstraint, // 504
        &Zhm3Boid__Enableseparation, // 505
        &Zhm3Boid__Enablecohesion, // 506
        &Zhm3Boid__Enableallignment, // 507
        &Zhm3Boid__Enableflee, // 508
        &Zhm3Boid__Enablefall, // 509
        &Zhm3Boid__Enablestayinbox, // 510
        &Zhm3Boid__Enablestayinspherepos, // 511
        &Zhm3Boid__Enablestayinsphere, // 512
        &Zhm3Boid__Enablefollowwaypoints, // 513
        &Zhm3Boid__Enablewander2D, // 514
        &Zhm3Boid__Enableseekref, // 515
        &Zhm3Boid__Enableseekpos, // 516
        &Zhm3Boid__Enablefallbehavior, // 517
        &Zhm3Boid__Setdragtarget, // 518
        &Zhm3Boid__Releasedragtarget, // 519
        &Zhm3Boid__Setpos, // 520
        &Zhm3Boid__Setglobalbonescale, // 521
        &Friskbox__Addguardtofriskbox, // 522
        &Friskbox__Removeguardfromfriskbox, // 523
        &Friskbox__Setenabled, // 524
        &Friskbox__Isenabled, // 525
        &Friskbox__Playfriskokanimmirrored, // 526
        &Friskbox__Addsuitcase, // 527
        &Friskbox__Removesuitcase, // 528
        &Friskbox__Ishitmancarryingconfsuitcase, // 529
        &Friskbox__Setsuitcaseplaced, // 530
        &Friskbox__Issurrendweaponenabled, // 531
        &Friskbox__Canpickupweaponsitems, // 532
        &Friskbox__Sethitmanssuitcasechecked, // 533
        &Osd__Addinfo, // 534
        &Osd__Addtickoffmark, // 535
        &Zhm3Securitycamera__Getfusebox, // 536
        &Zhm3Securitycamera__Getradiochannel, // 537
        &Zhm3Securitycamera__Getfootpoint, // 538
        &Poscontroller__Addactor, // 539
        &Poscontroller__Removeactor, // 540
        &Poscontroller__Getposition, // 541
        &M04Levelcontrol__Isglobeopen, // 542
        &M04Levelcontrol__Didhmtalktoagent, // 543
        &M04Levelcontrol__Ishmashitman, // 544
        &M04Levelcontrol__Ishmasbodyguard, // 545
        &M04Levelcontrol__Ishmaspatient, // 546
        &M04Levelcontrol__Ishmasguard, // 547
        &M04Levelcontrol__Ishmaswarden, // 548
        &M04Levelcontrol__Ishmastherapist, // 549
        &M11Levelcontrol__Additemforcolicheck, // 550
        &M11Levelcontrol__Removeitemforcolicheck, // 551
        &M11Levelcontrol__Activatecoliforactor, // 552
        &M11Levelcontrol__Deactivatecoliforactor, // 553
        &M11Levelcontrol__Setarranger, // 554
        &M11Levelcontrol__Setangel, // 555
        &M11Levelcontrol__Usecomputer, // 556
        &M11Levelcontrol__Throwknife, // 557
        &M11Levelcontrol__Operateprojector, // 558
        &M11Levelcontrol__Startprojector, // 559
        &M11Levelcontrol__Removefromwaterbox, // 560
        &M11Levelcontrol__Karoketimeplayed, // 561
        &M11Levelcontrol__Disablecrowdframeupdate, // 562
        &M12Levelcontrol__Sionhighnoon, // 563
        &M12Levelcontrol__Siafterhighnoon, // 564
        &M12Levelcontrol__Sihighnoonactive, // 565
        &M12Levelcontrol__Sihighnoonsilenced, // 566
        &M12Levelcontrol__Isweaponremotebomb, // 567
        &M12Levelcontrol__Displaybombhint, // 568
        &M12Levelcontrol__Moveobject, // 569
        &M12Levelcontrol__Disablehitmancontrols, // 570
        &M12Levelcontrol__Hitmanfallforward, // 571
        &Holevelcontrol__Hideoutcheckitem, // 572
        &Holevelcontrol__Checkcustomweaponstate, // 573
        &Holevelcontrol__Showhappysubtitle, // 574
        &Bloodtrail__Isbloodtrail, // 575
        &Bloodtrail__Getnexttrailpoint, // 576
        &Bloodtrail__Gettrailnumber, // 577
        &Bloodtrail__Deactivatetrail, // 578
        &Cigs__Getcig, // 579
        &Cigs__Freecig, // 580
        &Zlist__Getrndref, // 581
        &Zlist__Getcount, // 582
        &Zlist__Getref, // 583
        &Zlist__Getindex, // 584
        &Zlist__Contains, // 585
        &Zlist__Add, // 586
        &Zlist__Remove, // 587
        &Zlist__Clear, // 588
        &Zlist__Sendeventtolist, // 589
        &Addlinedecay, // 590
        &Addvectordecay, // 591
        &Debugfunctions__Displayscriptline, // 592
        &Debugfunctions__Displayscriptlinefrompos, // 593
        &Debugfunctions__Displaypermanentscriptline, // 594
        &Debugfunctions__Displaypermanentscriptlinefrompos, // 595
        &Debugfunctions__Modifypermanentscriptline, // 596
        &Debugfunctions__Addpermanentscripttext, // 597
        &Physics__Releasebone, // 598
        &Physics__Setvelocity, // 599
        &Item__Attachrhand, // 600
        &Item__Attachlhand, // 601
        &Item__Detachrhand, // 602
        &Item__Detachlhand, // 603
        &Item__Resetedibleitem, // 604
        &Item__Getlhanditem, // 605
        &Item__Getrhanditem, // 606
        &Item__Enablepickup, // 607
        &Item__Setowner, // 608
        &Item__Setownerparent, // 609
        &Item__Getparent, // 610
        &Item__Getowner, // 611
        &Item__Setitemstate, // 612
        &Item__Getitemstate, // 613
        &Item__Isitemhidden, // 614
        &Item__Isitemactive, // 615
        &Item__Sliprighthanditem, // 616
        &Item__Sliprighthanditemnoevent, // 617
        &Item__Sliplefthanditem, // 618
        &Item__Sliplefthanditemnoevent, // 619
        &Item__Isitemcontainer, // 620
        &Item__Insertitemincontainer, // 621
        &Item__Removeitemfromcontainer, // 622
        &Item__Putlhitemtopos, // 623
        &Item__Putrhitemtopos, // 624
        &Item__Containweapons, // 625
        &Item__Containmetallicweapons, // 626
        &Item__Iscontainerisempty, // 627
        &Item__Setvisibletonpcs, // 628
        &Item__Iscontainercontainsitem, // 629
        &Item__Getitemincontainer, // 630
        &Item__Clearfooddrinkinfection, // 631
        &Item__Getanim, // 632
        &Item__Playanimsegment, // 633
        &Item__Useitemactivateanimation, // 634
        &Item__Setforceunpickablebyhm, // 635
        &Item__Getforceunpickablebyhm, // 636
        &Item__Hideitem, // 637
        &Item__Showitem, // 638
        &Item__Isitemlarge, // 639
        &Item__Isitemcigarette, // 640
        &Item__Hastemplate, // 641
        &Item__Isitemontopofelevator, // 642
        &Item__Setscale, // 643
        &Print, // 644
        &Error, // 645
        &Warning, // 646
        &Zscassert, // 647
        &Engine__Random, // 648
        &Engine__Randomrange, // 649
        &Engine__Gettime, // 650
        &Engine__Getsceneval, // 651
        &Engine__Setsceneval, // 652
        &Engine__Localeexists, // 653
        &Engine__Isvalidvector, // 654
        &Scene__Setobjectposition, // 655
        &Scene__Setobjectpositionv3, // 656
        &Scene__Getobjectposition, // 657
        &Scene__Getgeomsinsidebox, // 658
        &Scene__Getactorsinbox, // 659
        &Scene__Isbox, // 660
        &Scene__Isposinsidebox, // 661
        &Scene__Getposinbox, // 662
        &Scene__Setscale, // 663
        &Scene__Objecthascontroller, // 664
        &Scene__Getcontrolleronobject, // 665
        &Scene__Getdistancebetweenobjects, // 666
        &Scene__Getdistbetweenobjectandpos, // 667
        &Scene__Getdistbetweenobjectandpos2D, // 668
        &Scene__Getnumofaccessdenies, // 669
        &Scene__Makeinactive, // 670
        &Scene__Makeactive, // 671
        &Scene__Getdoorstatus, // 672
        &Scene__Getparent, // 673
        &Scene__Isshattered, // 674
        &Scene__Isground, // 675
        &Scene__Setnoiselevel, // 676
        &Scene__Getnoiselevel, // 677
        &Scene__Getisinoutsidelocation, // 678
        &Audio__Playsound2D, // 679
        &Audio__Playsound3D, // 680
        &Audio__Playlocaleresource2D, // 681
        &Audio__Getlocaleresource, // 682
        &Audio__Setnotifytarget, // 683
        &Audio__Gettimeplayed, // 684
        &Audio__Gettimeleft, // 685
        &Audio__Stopsound, // 686
        &Audio__Setvolume, // 687
        &Audio__Getsndobjsoundobjectref, // 688
        &Audio__Setsoundobjectautodelete, // 689
        &Math__Vset, // 690
        &Math__Vcpy, // 691
        &Math__Vscalar, // 692
        &Math__Vaddscalar, // 693
        &Math__Vdist, // 694
        &Math__Vsub, // 695
        &Math__Vadd, // 696
        &Math__Vneg, // 697
        &Math__Vreset, // 698
        &Math__Vdot, // 699
        &Math__Vlen, // 700
        &Math__Vnorm, // 701
        &Math__Vpul, // 702
        &Math__Sqrtf, // 703
        &Math__Vrot, // 704
        &Istring__Isnameequal, // 705
        &Istring__Isnamecontains, // 706
        &Istring__Isempty, // 707
        &Pathfinder__Isvectinside, // 708
        &Pathfinder__Isposinside, // 709
        &Pathfinder__Getsearchposaroundpos, // 710
        &Pathfinder__Getposaroundpos, // 711
        &Pathfinder__Getentitypos, // 712
        &Pathfinder__Getclosestwallpos, // 713
        &Pathfinder__Teleportboid, // 714
        &Pathfinder__Iswallbetweenpoints, // 715
     };
    static_assert(sizeof(SI::ScriptInterfacesTable) == sizeof(void*) * 0x2CC);

    STATIC_GLOBAL_CLASS_INSTANCE_IMPL(ScriptInterfacesArray_t, ScriptInterfaces, 0x007F2D20, (void**)&ScriptInterfacesDefault);
}
