#ifndef __HBM_SCRIPT_RUNTIME_ZSCRIPTIMPORTTABLE_H__
#define __HBM_SCRIPT_RUNTIME_ZSCRIPTIMPORTTABLE_H__

/*
 * ZScriptImportTable — C-facing mirror of the Glacier ScriptImports block.
 *
 * The DLL's ordinal-4 export `ScriptImports` is a flat `void*[0x2CC]` array
 * that the engine overwrites verbatim with `ScriptInterfaces` at
 * AttachSceneScripts. This header gives that block a typed, self-documenting
 * shape: a struct of 0x2CC function pointers in original PC slot order, plus
 * the local C types those signatures need.
 *
 * This is a C port of the original Glacier `ZScriptImportTable.h` (the typed
 * import table). Enums are collapsed to `int`; `_v3` is a local 3-float
 * struct (aliased `v3`); `ZREF`/`anim` are integer handles. The struct layout
 * is frozen — field order == runtime slot order == SI::ScriptInterfacesTable.
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Local script-facing types (C mirrors of Glacier/ScriptEngine/Common.h) ---- */

typedef struct _v3
{
    float x;
    float y;
    float z;
} _v3;
typedef _v3 v3;

typedef int32_t ZREF;
typedef uint16_t anim;

/* ZSC_EVENT — {ZMSGID zmsg; void* pData;} */
typedef struct ZSC_EVENT
{
    uint16_t zmsg;
    void* pData;
} ZSC_EVENT;

/* sCover — Glacier/ScriptEngine/Common.h::_sCover */
typedef struct sCover
{
    v3 position;
    v3 facing;
    int movedirection; /* eDirection */
    float distance;
    int indx;
} sCover;

/* sGQCTask — Glacier/ScriptEngine/Common.h::_sGQCTask */
typedef struct sGQCTask
{
    int type;   /* eGQCTaskType */
    ZREF rtarget;
} sGQCTask;

/* SDifficultySettings — Hitman::SDifficultySettings, 0xA4 bytes */
typedef struct SDifficultySettings
{
    float fstanddowntime;
    float ffollowtrailtime;
    float fhunttargettracktime;
    float fseethroughdisguisedistance;
    float fseethroughdisguisespeed;
    float fforgetdisguisespeed;
    float frunsuspiciousrange;
    float faccuracymodifier;
    float fburstlength;
    float frofmultiplier;
    float faimspeed;
    float fdrawspeedmultiplier;
    float fshothearingrange;
    float fscreamhearingrange;
    float fcheckfootstepsbehindrange;
    float factorrelaxedvisionrange;
    float factorrelaxedfov;
    float factoralertvisionrange;
    float factoralertfov;
    float ffallingdamagemultiplier;
    float fusecoverpercentage;
    float fbleedtodeathtime;
    float fciviliansattackhmpercentage;
    float fcivilianhidetime;
    float flockpicktimemultiplier;
    float ffriskintrusiondecaytime;
    float fsmallweaponvisiblemultiplierciv;
    float fsmallweaponvisiblemultipliergrd;
    int ihitmanhitpoints;
    int iguardhitpoints;
    int icivilianhitpoints;
    int itargethitpoints;
    char bautoaim;
    char bheadshotsagainsthitman;
    float fmoneymultiplier;
    float fmaxmoneymultiplier;
    float fcleanupprice;
    float finnocentbribeprice;
    float fpolicebribeprice;
    float fnewidentityprice;
    float fweaponupgradeprice;
    float fweaponretrieveprice;
} SDifficultySettings;

/* ScriptImports_t — the per-slot import entry type (PC: typedef void (__cdecl*)(int*)) */
typedef void (*ScriptImports_t)(int*);

/* ZScriptImportTable — export ordinal enum (Glacier/ScriptEngine/ZScriptImportTable.h) */
typedef enum ZScriptImportTable
{
    Z_SF = 1,
    Z_ISF = 2,
    Z_Scripts = 3,
    Z_ScriptImports = 4
} ZScriptImportTable;

/* ---- The typed import table: 0x2CC function pointers, PC slot order ---- */
typedef struct SCRIPTIMPORTSTABLE
{
    void (*Zcar__Moveto)(ZREF rCar, v3 target, int useDirection);
    void (*Zcar__Setspeedmultiplier)(ZREF rCar, float multiplier);
    void (*Zcar__Settargetspeedmultiplier)(ZREF rCar, float minMultiplier, float maxMultiplier);
    v3 (*Zcar__Getpathendpoint)(ZREF rCar);
    v3 (*Zcar__Getpathstartpoint)(ZREF rCar);
    void (*Zcar__Setpath)(ZREF rCar, ZREF rPath, int updatePosition);
    ZREF (*Zcar__Getposobj)(ZREF rCar, const char* name);
    void (*Zcar__Attachactortoseat)(ZREF rCar, ZREF rActor, int seatIndex);
    void (*Zcar__Detachactorfromseat)(ZREF rCar, ZREF rActor, int seatIndex);
    void (*Zcar__Stop)(ZREF rCar, float blendTime);
    void (*Zcar__Tempstop)(ZREF rCar, float blendTime);
    void (*Zcar__Continue_)(ZREF rCar);
    void (*Zcar__Hithitman)(ZREF rCar);
    void (*Zcar__Setcarposdir)(ZREF rCar, v3 position, v3 direction);
    void (*Zlink__Stopallanims)(ZREF rLink);
    void (*Zlink__Stopubanims)(ZREF rLink);
    anim (*Zlink__Getanim)(ZREF rLink, const char* name);
    int (*Zlink__Checkanimrunning)(ZREF rLink, int animId);
    int (*Zlink__Getnumberofframes)(ZREF rLink, anim animId);
    int (*Zlink__Playanimsegment)(ZREF rLink, anim animId, int segment, float start, float end, float blendTime);
    int (*Zlink__Canplayanim)(ZREF rLink, anim animId, int segment);
    int (*Zlink__Canplayanimsegment)(ZREF rLink, anim animId, float start, float end, float blendIn, float blendOut);
    int (*Zlink__Playaniminterpolated)(ZREF rLink, anim animId, v3 position, v3 direction, float start, float end, float blendIn, float blendOut, int flags);
    int (*Zlink__Setactiveanimdest)(ZREF rLink, v3 position, v3 direction, float blendTime);
    int (*Zlink__Getactiveanimdest)(ZREF rLink, v3* position, v3* direction);
    void (*Zlink__Lockfacing)(ZREF rLink, ZREF rTarget);
    int (*Zlink__Getmetakeyframenr)(ZREF rLink, anim animId, int meta);
    int (*Zlink__Getmetakeynrframenr)(ZREF rLink, anim animId, int meta, int metaIndex);
    int (*Zlink__Getanimendpoint)(ZREF rLink, anim animId, ZREF rBase, v3* endpoint);
    int (*Zlink__Getmetakeyframenrfrommetastring)(ZREF rLink, anim animId, const char* meta);
    void (*Zlink__Setholdweaponubanim)(ZREF rLink, anim animId);
    void (*Zhm3Actor__Setblinking)(ZREF rActor, int disabled);
    void (*Zhm3Actor__Initmapicon)(ZREF rActor);
    void (*Zhm3Actor__Forceshowmapicon)(ZREF rActor);
    void (*Zhm3Actor__Die)(ZREF rActor);
    void (*Zhm3Actor__Initializehitpoints)(ZREF rActor, int hitPoints);
    void (*Zhm3Actor__Sethitpoints)(ZREF rActor, float hitPoints);
    void (*Zhm3Actor__Setcharactertype)(ZREF rActor, int characterType);
    int (*Zhm3Actor__Getcharactertype)(ZREF rActor, ZREF rDefaultActor);
    void (*Zhm3Actor__Changemapiconandcharactertype)(ZREF rActor, int characterType, int forceDeadIcon);
    void (*Zhm3Actor__Removefrommap)(ZREF rActor);
    float (*Zhm3Actor__Gethitpoints)(ZREF rActor);
    float (*Zhm3Actor__Takedamage)(ZREF rActor, float damage);
    void (*Zhm3Actor__Setleavebloodtrail)(ZREF rActor, int enabled);
    void (*Zhm3Actor__Setvisionrangesandfovs)(ZREF rActor, float closeRange, float closeFov, float farRange, float farFov);
    void (*Zhm3Actor__Setvisionrangeandfov)(ZREF rActor, float range, float fov);
    void (*Zhm3Actor__Setmood)(ZREF rActor, uint8_t mood, float intensity);
    float (*Zhm3Actor__Gettension)(ZREF rActor);
    void (*Zhm3Actor__Settension)(ZREF rActor, int interestLevel);
    void (*Zhm3Actor__Increasetension)(ZREF rActor, int interestLevel, float amount);
    void (*Zhm3Actor__Releasetension)(ZREF rActor, int interestLevel);
    uint8_t (*Zhm3Actor__Getmaxneed)(ZREF rActor, float value);
    void (*Zhm3Actor__Setneed)(ZREF rActor, uint8_t need, float value);
    void (*Zhm3Actor__Setneedtime)(ZREF rActor, uint8_t need, float value);
    float (*Zhm3Actor__Getneed)(ZREF rActor, uint8_t need);
    void (*Zhm3Actor__Lockubanim)(ZREF rActor, int locked);
    void (*Zhm3Actor__Enableubholdanims)(ZREF rActor);
    void (*Zhm3Actor__Disableubholdanims)(ZREF rActor);
    int (*Zhm3Actor__Enableubholdanim)(ZREF rActor);
    int (*Zhm3Actor__Isubanimlocked)(ZREF rActor);
    int (*Zhm3Actor__Setscriptubanim)(ZREF rActor, anim animId);
    void (*Zhm3Actor__Resetscriptubanim)(ZREF rActor);
    int (*Zhm3Actor__Playscriptubanim)(ZREF rActor, anim animId, int force);
    int (*Zhm3Actor__Playscriptubanimloop)(ZREF rActor, anim animId, int force);
    int (*Zhm3Actor__Stopscriptubanimplay)(ZREF rActor);
    int (*Zhm3Actor__Hasrunningubanim)(ZREF rActor);
    void (*Zhm3Actor__Setweapontemplate)(ZREF rActor, ZREF rWeaponTemplate);
    ZREF (*Zhm3Actor__Getweapontemplate)(ZREF rActor);
    void (*Zhm3Actor__Setweapon)(ZREF rActor, ZREF rWeapon);
    void (*Zhm3Actor__Resetweapon)(ZREF rActor);
    ZREF (*Zhm3Actor__Getweapon)(ZREF rActor);
    void (*Zhm3Actor__Setammoinweapon)(ZREF rActor, int ammo);
    void (*Zhm3Actor__Pullweapon)(ZREF rActor);
    int (*Zhm3Actor__Ownsownweapon)(ZREF rActor);
    int (*Zhm3Actor__Isweapondrawn)(ZREF rActor);
    int (*Zhm3Actor__Currentweaponcanbeholstered)(ZREF rActor);
    int (*Zhm3Actor__Holsterweapon)(ZREF rActor);
    int (*Zhm3Actor__Isholdingitem)(ZREF rActor);
    int (*Zhm3Actor__Hasfreehand)(ZREF rActor);
    int (*Zhm3Actor__Islinkactionrunning)(ZREF rActor);
    void (*Zhm3Actor__Putiteminrightpocket)(ZREF rActor, ZREF rItem);
    void (*Zhm3Actor__Putiteminleftpocket)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Pullitemfromrightpocket)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Pullitemfromleftpocket)(ZREF rActor, ZREF rItem);
    void (*Zhm3Actor__Setisholdingshootableiteml)(ZREF rActor, int holding);
    void (*Zhm3Actor__Setisholdingshootableitemr)(ZREF rActor, int holding);
    void (*Zhm3Actor__Makeitemvisible)(ZREF rActor, ZREF rItem);
    void (*Zhm3Actor__Makeiteminvisible)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Makeactorvisible)(ZREF rActor, ZREF rTarget);
    int (*Zhm3Actor__Makeactorinvisible)(ZREF rActor, ZREF rTarget);
    void (*Zhm3Actor__Removedecal)(ZREF rActor, int decalId);
    int (*Zhm3Actor__Setvisibletypes)(ZREF rActor, int visibleTypes);
    int (*Zhm3Actor__Getvisibletypes)(ZREF rActor);
    void (*Zhm3Actor__Setseerblind)(ZREF rActor, int blind);
    int (*Zhm3Actor__Disablevision)(ZREF rActor, ZREF rTarget);
    int (*Zhm3Actor__Enablevision)(ZREF rActor, ZREF rTarget);
    void (*Zhm3Actor__Disablepickupclothes)(ZREF rActor, ZREF rClothes);
    void (*Zhm3Actor__Enablepickupclothes)(ZREF rActor, ZREF rClothes);
    int (*Zhm3Actor__Getvisibleprojectileweapons)(ZREF rActor, ZREF* outWeapons, int maxWeapons, ZREF rExcludeWeapon);
    int (*Zhm3Actor__Isitemedible)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Isitemdrinkable)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Getitemnumbitestotal)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Getitemnumbites)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Removeitembite)(ZREF rActor, ZREF rItem);
    void (*Zhm3Actor__Restoreitembites)(ZREF rActor, ZREF rItem, int bites);
    int (*Zhm3Actor__Getiteminfectiontype)(ZREF rActor, ZREF rItem);
    void (*Zhm3Actor__Aimweaponatgeom)(ZREF rActor, ZREF rTarget, float blendTime);
    void (*Zhm3Actor__Aimweaponatpos)(ZREF rActor, v3 position, float blendTime);
    void (*Zhm3Actor__Fireweapon)(ZREF rActor, int fire, float blendTime, int unknown);
    void (*Zhm3Actor__Playfireweaponsound)(ZREF rActor, ZREF rWeapon);
    void (*Zhm3Actor__M12_Albinofireweapon)(ZREF rActor, int fire, float blendTime, int unknown);
    int (*Zhm3Actor__Triggerweaponpush)(ZREF rActor, ZREF rWeapon);
    int (*Zhm3Actor__Isaiminposition)(ZREF rActor);
    int (*Zhm3Actor__Isaimingattarget)(ZREF rActor, ZREF rTarget, float tolerance, ZREF* rAimedTarget, v3* aimPosition);
    int (*Zhm3Actor__Reloadweapon)(ZREF rActor, int instant);
    int (*Zhm3Actor__Numberofshotsleft)(ZREF rActor);
    int (*Zhm3Actor__Isbodyknownandunchanged)(ZREF rActor, ZREF rBody);
    void (*Zhm3Actor__Registerdeadbody)(ZREF rActor, ZREF rBody);
    int (*Zhm3Actor__Isobjectvisible)(ZREF rActor, ZREF rObject);
    int (*Zhm3Actor__Objectisinfront)(ZREF rActor, ZREF rObject);
    float (*Zhm3Actor__Chkcolibeforeactor)(ZREF rActor, float distance, float radius, v3* position);
    ZREF (*Zhm3Actor__Isitemininventory)(ZREF rActor, const char* itemName);
    int (*Zhm3Actor__Additemtoinventory)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Removeitemfrominventory)(ZREF rActor, ZREF rItem);
    void (*Zhm3Actor__Dumpinventorytoground)(ZREF rActor);
    ZREF (*Zhm3Actor__Undress)(ZREF rActor);
    int (*Zhm3Actor__Dress)(ZREF rActor, ZREF rClothes);
    void (*Zhm3Actor__Dialoglisten)(ZREF rActor);
    void (*Zhm3Actor__Dialogtalk)(ZREF rActor);
    void (*Zhm3Actor__Throwknifeatref)(ZREF rActor, ZREF rKnife, ZREF rTarget);
    int (*Zhm3Actor__Findsitdowngeom)(ZREF rActor, v3* position, v3* direction, int* seatIndex, int flags, ZREF rIgnore);
    int (*Zhm3Actor__Sitdown)(ZREF rActor, anim animId, int instant);
    int (*Zhm3Actor__Sitdowninstant)(ZREF rActor, anim animId, int instant);
    int (*Zhm3Actor__Movechairifapplicable)(ZREF rActor, anim animId, int instant);
    void (*Zhm3Actor__Movechair)(ZREF rActor, anim animId, int instant);
    void (*Zhm3Actor__Situp)(ZREF rActor);
    int (*Zhm3Actor__Findliedowngeom)(ZREF rActor, v3* position, v3* direction, int allowOccupied);
    int (*Zhm3Actor__Liedown)(ZREF rActor, int instant);
    ZREF (*Zhm3Actor__Findlightswitch)(ZREF rActor);
    void (*Zhm3Actor__Togglelightswitch)(ZREF rActor, ZREF rLightSwitch, int on);
    int (*Zhm3Actor__Getlightswitchstate)(ZREF rActor, ZREF rLightSwitch);
    int (*Zhm3Actor__Getbodyposition)(ZREF rActor);
    void (*Zhm3Actor__Setbodyposition)(ZREF rActor, int bodyPosition);
    void (*Zhm3Actor__Setbodypositionunknown)(ZREF rActor);
    void (*Zhm3Actor__Setbodypositionnormal)(ZREF rActor);
    void (*Zhm3Actor__Sethmescort)(ZREF rActor, ZREF rEscort);
    ZREF (*Zhm3Actor__Gethmescort)(ZREF rActor);
    void (*Zhm3Actor__Playsound)(ZREF rActor, int audioEvent);
    int (*Zhm3Actor__Isweaponallowed)(ZREF rActor, ZREF rWeapon);
    int (*Zhm3Actor__Isweaponfoundathitman)(ZREF rActor);
    ZREF (*Zhm3Actor__Transferhitmanweaponstoactor)(ZREF rActor);
    int (*Zhm3Actor__Isonback)(ZREF rActor);
    void (*Zhm3Actor__Setneardeath)(ZREF rActor, int nearDeath);
    void (*Zhm3Actor__Dropbloodstain)(ZREF rActor);
    void (*Zhm3Actor__Activatebloodspurt)(ZREF rActor, int bloodSpurt, v3* position);
    int (*Zhm3Actor__Wantbloodstain)(ZREF rActor, int wantBloodStain);
    void (*Zhm3Actor__Setwantbloodonhit)(ZREF rActor, int wantBloodOnHit);
    int (*Zhm3Actor__Isactor)(ZREF rActor, ZREF rTarget);
    int (*Zhm3Actor__Ishitmandraggingactor)(ZREF rActor, ZREF rTarget);
    int (*Zhm3Actor__Iswearingclothes)(ZREF rActor, ZREF rClothes);
    ZREF (*Zhm3Actor__Getoriginalsuit)(ZREF rActor, ZREF rClothes);
    int (*Zhm3Actor__Getflankingpos)(ZREF rActor, ZREF rTarget, int direction, v3* position);
    int (*Zhm3Actor__Getbodycheckposdir)(ZREF rActor, ZREF rBody, v3* position, v3* direction);
    void (*Zhm3Actor__Getposonpath)(ZREF rActor, ZREF rPath, float distance, v3* position);
    void (*Zhm3Actor__Blowhitmandisguise)(ZREF rActor);
    void (*Zhm3Actor__Generateaudioevent)(ZREF rActor, int audioEvent);
    void (*Zhm3Actor__Playactorspeech)(ZREF rActor, int audioType, int audioEvent);
    int (*Zhm3Actor__Playresourceasspeech)(ZREF rActor, int resourceId);
    int (*Zhm3Actor__Playlocaleresourceasspeech)(ZREF rActor, const char* resourceName);
    int (*Zhm3Actor__Getlocalesoundresource)(ZREF rActor, const char* resourceName);
    int (*Zhm3Actor__Playrandomlocaleresourceasspeech)(ZREF rActor, const char* resourceName);
    int (*Zhm3Actor__Isspeechplaying)(ZREF rActor);
    void (*Zhm3Actor__Stopspeech)(ZREF rActor);
    void (*Zhm3Actor__Bite)(ZREF rActor, int16_t animVariation, v3 from, v3 to, float blendIn, float blendOut);
    void (*Zhm3Actor__Punch)(ZREF rActor);
    void (*Zhm3Actor__Stungunattack)(ZREF rActor);
    void (*Zhm3Actor__Activaterigidbody)(ZREF rActor);
    void (*Zhm3Actor__Userigidbodyonpush)(ZREF rActor, int enabled);
    void (*Zhm3Actor__Useubragdoll)(ZREF rActor, int enabled);
    void (*Zhm3Actor__Dragbody)(ZREF rActor, ZREF rBody);
    int (*Zhm3Actor__Actorbeingpushed)(ZREF rActor);
    int (*Zhm3Actor__Isactorbeingkilled)(ZREF rActor, ZREF rTarget);
    void (*Zhm3Actor__Changeintobodybag)(ZREF rActor, ZREF rTarget);
    int (*Zhm3Actor__Isbodybag)(ZREF rActor, ZREF rTarget);
    int (*Zhm3Actor__Maybebodybagged)(ZREF rActor, ZREF rTarget);
    void (*Zhm3Actor__Setmaybebodybagged)(ZREF rActor, int maybeBodyBagged);
    void (*Zhm3Actor__Setignorehelprequests)(ZREF rActor, int ignoreHelpRequests);
    void (*Zhm3Actor__Setissearching)(ZREF rActor, int isSearching);
    void (*Zhm3Actor__Disabledrag)(ZREF rActor, ZREF rBody);
    int (*Zhm3Actor__Getnumberofavailableragdolls)(ZREF rActor);
    void (*Zhm3Actor__Setactorspecies)(ZREF rActor, int actorSpecies);
    void (*Zhm3Actor__Sendeventtoactorswithinbox)(ZREF rActor, ZSC_EVENT event, ZREF rBox);
    int (*Zhm3Actor__Playanimwithcamerabone)(ZREF rActor, anim animId);
    ZREF (*Zhm3Actor__Findclosestcharactertype)(ZREF rActor, int actorType, v3 position, float radius);
    void (*Zhm3Actor__Disableragdollanddieanim)(ZREF rActor);
    void (*Zhm3Actor__Dummy)(ZREF rActor);
    void (*Zhm3Actor__Repairutilbox)(ZREF rActor, ZREF rUtilBox);
    void (*Zhm3Actor__Terminatecurrentlnkaction)(ZREF rActor);
    int (*Zhm3Actor__Getsecuritydeviceloopingsound)(ZREF rActor, ZREF rSecurityDevice);
    int (*Zhm3Actor__Getsecuritydeviceweaponfoundsound)(ZREF rActor, ZREF rSecurityDevice);
    void (*Zhm3Actor__Activateragdollnextframe)(ZREF rActor);
    void (*Zhm3Actor__Activateragdoll)(ZREF rActor);
    void (*Zhm3Actor__Hitragdoll)(ZREF rActor, v3 position, v3 impulse, float force);
    int (*Zhm3Actor__Ishitmanvisible)(ZREF rActor);
    void (*Zhm3Actor__Setignoredisguise)(ZREF rActor, int ignoreDisguise);
    int (*Zhm3Actor__Isignoredisguise)(ZREF rActor);
    int (*Zhm3Actor__Canplayanimpf)(ZREF rActor, anim animId, int flags);
    void (*Zhm3Actor__Setposdiractor)(ZREF rActor, v3* position, v3* direction);
    float (*Zhm3Actor__Calculatestopdistancetoavoidobstacle)(ZREF rActor);
    void (*Zhm3Actor__Setinterruptable)(ZREF rActor, int interruptable);
    void (*Zhm3Actor__Positionlock)(ZREF rActor);
    void (*Zhm3Actor__Positionunlock)(ZREF rActor);
    int (*Zhm3Actor__Isanimubanim)(ZREF rActor, anim animId);
    float (*Zhm3Actor__Getangletoactor2)(ZREF rActor, ZREF rTarget, ZREF rReference);
    void (*Zhm3Actor__Addmouthemitter)(ZREF rActor, ZREF rEmitter);
    void (*Zhm3Actor__Removemouthemitter)(ZREF rActor, ZREF rEmitter);
    void (*Zhm3Actor__Onpickupitem)(ZREF rActor, ZREF rItem);
    int (*Zhm3Actor__Isenteringorleavingelevator)(ZREF rActor);
    int (*Zhm3Actor__Isinorusingelevator)(ZREF rActor);
    int (*Zhm3Actor__Isinoutsidelocation)(ZREF rActor);
    ZREF (*Zhm3Actor__Isinelevator)(ZREF rActor);
    ZREF (*Zhm3Actor__Getelevatorhatchgeom)(ZREF rActor);
    void (*Zhm3Actor__Broadcasttoothersinelevator)(ZREF rActor, ZREF rElevator, ZSC_EVENT event);
    int (*Zhm3Actor__Isaccidentkilled)(ZREF rActor);
    int (*Zhm3Actor__Ispointinsideelevatorarea)(ZREF rActor, v3 position);
    void (*Zhm3Actor__Setsuspectedsuit)(ZREF rActor, ZREF rSuit);
    int (*Zhm3Actor__Ishitmanhidingbehindnextdoor)(ZREF rActor, ZREF* rDoor, v3* position);
    void (*Zhm3Actor__Idlelookat)(ZREF rActor, ZREF rTarget);
    void (*Zhm3Actor__Setdisableragdollforshots)(ZREF rActor, int disable);
    void (*Zactor__Setscriptpaused)(ZREF rActor, int paused);
    void (*Zactor__Setmoveset)(ZREF rActor, int moveSet, int moveSetType);
    void (*Zactor__Stopmovementatdistance)(ZREF rActor, float distance);
    void (*Zactor__Setmovespeedmultiplier)(ZREF rActor, float speedMultiplier);
    float (*Zactor__Getactorspeed)(ZREF rActor, ZREF rTarget);
    void (*Zactor__Dontstop)(ZREF rActor, int dontStop);
    int (*Zactor__Movetoposq)(ZREF rActor, v3 position, float distance, int moveSet, int moveSetType);
    int (*Zactor__Movetolocationq)(ZREF rActor, ZREF rLocation, float distance, int moveSet, int moveSetType);
    void (*Zactor__Stoppath)(ZREF rActor);
    void (*Zactor__Setstopdistance)(ZREF rActor, float stopDistance);
    void (*Zactor__Setpathnotify)(ZREF rActor, float notifyDistance);
    void (*Zactor__Setupdateposition)(ZREF rActor, int updatePosition);
    void (*Zactor__Lockmovement)(ZREF rActor);
    void (*Zactor__Unlockmovement)(ZREF rActor);
    void (*Zactor__Clearreservation)(ZREF rActor);
    void (*Zactor__Ignorereservations)(ZREF rActor);
    void (*Zactor__Usereservations)(ZREF rActor);
    int (*Zactor__Isragdollactive)(ZREF rActor, ZREF rTarget);
    int (*Zactor__Isdead)(ZREF rActor);
    int (*Zactor__Isunconscious)(ZREF rActor);
    int (*Zactor__Isawake)(ZREF rActor);
    int (*Zactor__Getactorstate)(ZREF rActor);
    void (*Zactor__Setawake)(ZREF rActor);
    void (*Zactor__Setunconscious)(ZREF rActor);
    void (*Zactor__Setsleeping)(ZREF rActor);
    void (*Zactor__Setdead)(ZREF rActor);
    void (*Zactor__Lookat)(ZREF rActor, ZREF rTarget);
    ZREF (*Zactor__Getlookat)(ZREF rActor);
    void (*Zactor__Enablelookat)(ZREF rActor, int enabled);
    int (*Zactor__Islookatenabled)(ZREF rActor);
    void (*Zactor__Setactorposdir)(ZREF rActor, v3 position, v3 direction);
    void (*Zactor__Copytoref)(ZREF rActor, ZREF rReference);
    void (*Zactor__Setvisfov)(ZREF rActor, float fov);
    int (*Zactor__Isonstairs)(ZREF rActor);
    void (*Zactor__Setshootintoground)(ZREF rActor, int enabled);
    void (*Zactor__Setshootintogroundinfullbody)(ZREF rActor, int enabled);
    float (*Zactor__Getboidspeed)(ZREF rActor);
    void (*Zactor__Inactivateboid)(ZREF rActor);
    void (*Zactor__Placeactorinmovinggroup)(ZREF rActor, ZREF rGroup, ZREF rReference);
    void (*Zactor__Removeactorfrommovinggroup)(ZREF rActor, ZREF rGroup);
    int (*Zactor__Getnumoftransitions)(ZREF rActor, int moveSet);
    void (*Zactor__Setnumoftransitions)(ZREF rActor, int moveSet, int numTransitions);
    void (*Zactor__Setfootwearmaterial)(ZREF rActor, int material);
    void (*Zactor__Setmovepoolweight)(ZREF rActor, float weight);
    void (*Zactor__Sethandtarget)(ZREF rActor, int hand, ZREF rTarget, float weight);
    int (*Zactor__Getvariant)(ZREF rActor);
    void (*Zactor__Setvariant)(ZREF rActor, int variant);
    void (*Zactor__Addtoforcedrawoffscreenlist)(ZREF rActor);
    void (*Zactor__Removefromforcedrawoffscreenlist)(ZREF rActor);
    void (*Zactor__Turnactor)(ZREF rActor, float angle);
    void (*Zactor__Setcanopendoors)(ZREF rActor, int canOpenDoors);
    void (*Hm3Gui__Displayinfo)(const char* text);
    void (*Hm3Gui__Displaypipinfo)(const char* text);
    void (*Hm3Gui__Displaywarning)(const char* text);
    void (*Hm3Gui__Displaypipwarning)(const char* text);
    void (*Hm3Gui__Displayhint)(const char* text);
    void (*Hm3Gui__Displaysubtitle)(const char* text);
    void (*Hm3Gui__Displaysubtitletimed)(const char* text, float duration);
    void (*Silevelcontrol__Missioncompleted)();
    void (*Silevelcontrol__Missionfailed)(const char* reason);
    void (*Silevelcontrol__Characterkilled)(ZREF rActor);
    void (*Silevelcontrol__Characterharmed)(ZREF rActor);
    void (*Silevelcontrol__Completeobjective)(int objectiveId);
    void (*Silevelcontrol__Completeobjectivenotickoffmark)(int objectiveId);
    void (*Silevelcontrol__Uncompleteobjective)(int objectiveId);
    void (*Silevelcontrol__Hideobjective)(int objectiveId);
    void (*Silevelcontrol__Unhideobjective)(int objectiveId);
    int (*Silevelcontrol__Isobjectivecompleted)(int objectiveId);
    void (*Silevelcontrol__Changeobjectivetext)(int objectiveId, const char* text);
    void (*Silevelcontrol__Clearchangedobjectivetext)(int objectiveId);
    void (*Silevelcontrol__Changeobjectivepath)(int objectiveId, const char* path);
    void (*Silevelcontrol__Clearchangedobjectivepath)(int objectiveId);
    ZREF (*Silevelcontrol__Getlevelcontrol)();
    ZREF (*Silevelcontrol__Gethitman)();
    int (*Silevelcontrol__Ishitmanrecognizable)();
    void (*Silevelcontrol__Killhitman)();
    int (*Silevelcontrol__Getnotoriety)();
    ZREF (*Silevelcontrol__Getcoverlist)();
    int (*Silevelcontrol__Start_Actorinvestigatehitman)(ZREF rInspector);
    void (*Silevelcontrol__End_Actorinvestigatehitman)(ZREF rInspector);
    SDifficultySettings (*Silevelcontrol__Getdifficultysettings)();
    int (*Silevelcontrol__Getdifficulty)();
    int (*Silevelcontrol__Ishitmantrespassing)();
    int (*Silevelcontrol__Ishitmaninoutsidelocation)();
    int (*Silevelcontrol__Iscontainerallowedhere)(ZREF rContainer);
    ZREF (*Silevelcontrol__Gethumanshieldtarget)();
    ZREF (*Silevelcontrol__Gethitmanhidecloset)();
    ZREF (*Silevelcontrol__Getcurrentvictim)();
    int (*Silevelcontrol__Ishitmanincloset)(ZREF rCloset);
    int (*Silevelcontrol__Killhitmanincloset)();
    ZREF (*Silevelcontrol__Getdoorpickedbyhm)();
    int (*Silevelcontrol__Ishitmanlockpicking)();
    int (*Silevelcontrol__Ishitmanloookingthroughkeyhole)();
    int (*Silevelcontrol__Ishitmanthrowingstuff)();
    int (*Silevelcontrol__Subscribehitmanchangeclothes)(ZREF rSubscriber);
    ZREF (*Silevelcontrol__Getcurrenthitmansuit)();
    int (*Silevelcontrol__Ishitmanwearinghitmansuit)();
    ZREF (*Silevelcontrol__Getcurrenthitmanlefthanditem)();
    ZREF (*Silevelcontrol__Getcurrenthitmanweapontemplate)();
    ZREF (*Silevelcontrol__Getactorfriskinghm)();
    ZREF (*Silevelcontrol__Setactorfriskinghm)(ZREF rActor);
    int (*Silevelcontrol__Getfriskoperation)();
    int (*Silevelcontrol__Setfriskoperation)(int operation);
    int (*Silevelcontrol__Getcurrentzone)();
    int (*Silevelcontrol__Starteventcamera)(ZREF rAttachGeom, int cameraType, ZREF rLookAtGeom, int position);
    int (*Silevelcontrol__Starteventcameralookatgeom)(ZREF rLookAtGeom, ZREF rCameraGeom, int position);
    int (*Silevelcontrol__Starteventcamerawithcameraboneanim)(ZREF rCameraGeom, int animationIndex, int position);
    int (*Silevelcontrol__Endeventcamera)(int eventCameraId);
    ZREF (*Silevelcontrol__Getguardsfriskbox)(ZREF rActor);
    int (*Silevelcontrol__Hashmweaponinhand)();
    void (*Silevelcontrol__Incfriskfails)();
    void (*Silevelcontrol__Incheadshots)();
    void (*Silevelcontrol__Inctargetspoisoned)();
    void (*Silevelcontrol__Incsedates)();
    void (*Silevelcontrol__Incimpersonations)();
    void (*Silevelcontrol__Incpusheddeath)();
    void (*Silevelcontrol__Inctargetssniped)();
    void (*Silevelcontrol__Incbodiesfound)(ZREF rActor);
    void (*Silevelcontrol__Incsedatedbodiesfound)();
    void (*Silevelcontrol__Incbloodtrailsfound)();
    void (*Silevelcontrol__Incclosecombatkill)();
    void (*Silevelcontrol__Incaccidentkill)(ZREF rActor);
    void (*Silevelcontrol__Incaccidentkillignoredamage)(ZREF rActor);
    int (*Silevelcontrol__Setchangeclothesallowed)(int allowed);
    void (*Silevelcontrol__Caughtontape)();
    void (*Silevelcontrol__Tapestolen)();
    void (*Silevelcontrol__Weaponused)(ZREF rActor, ZREF rWeapon);
    void (*Silevelcontrol__Settargetnum)(ZREF rActor, int targetNum);
    ZREF (*Silevelcontrol__Gethminventoryitem)(const char* itemType);
    int (*Silevelcontrol__Isitemtemplateinhminventory)(ZREF rTemplate);
    int (*Silevelcontrol__Isiteminhminventory)(ZREF rItem);
    void (*Silevelcontrol__Copyhmtoref)(ZREF rRef);
    void (*Silevelcontrol__Audioaddpauseobject)(ZREF rObject);
    int (*Silevelcontrol__Starteventmusic)(int musicId);
    ZREF (*Silevelcontrol__Createsecuritydevicefromtemplate)();
    ZREF (*Silevelcontrol__Getsuitcaseinhitmanshand)();
    int (*Silevelcontrol__Isdooropen)(ZREF rDoor);
    int (*Silevelcontrol__Isdoorlocked)(ZREF rDoor);
    void (*Silevelcontrol__Getclosestposter)(ZREF rReference, ZREF* rPoster, v3* position);
    void (*Silevelcontrol__Getreachablehitmanpfpos)(v3* position);
    int (*Silevelcontrol__Getclosestexitposforclimbinghitman)(v3 position, v3* exitPosition);
    int (*Silevelcontrol__Ishitmaninreachableposition)();
    int (*Silevelcontrol__Ishitmaninsidepathfinder)();
    void (*Silevelcontrol__Forcecloselasthitmandoor)();
    int (*Silevelcontrol__Ishitmaninelevator)();
    int (*Silevelcontrol__Ishitmantopofelevator)();
    void (*Silevelcontrol__Showonmap)(ZREF rActor, int show);
    int (*Silevelcontrol__Isactorinwaterbox)(ZREF rActor);
    void (*Silevelcontrol__Remove_Existing_Eventcam)();
    int (*Pathfollower__Ispathfollowervalid)(ZREF rPathFollower);
    int (*Pathfollower__Numwaypointlists)(ZREF rPathFollower);
    void (*Pathfollower__Setwaypointindex)(ZREF rPathFollower, int index);
    void (*Pathfollower__Useclosestonstart)(ZREF rPathFollower, int useClosest);
    ZREF (*Pathfollower__Getnextwaypoint)(ZREF rPathFollower);
    void (*Pathfollower__Setwaypointlist)(ZREF rPathFollower, int listIndex);
    ZREF (*Pathfollower__Getcurrentwaypointlist)(ZREF rPathFollower);
    void (*Pathfollower__Setexternalwaypointlist)(ZREF rPathFollower, ZREF rWaypointList);
    void (*Pathfollower__Setpathtype)(ZREF rPathFollower, int pathType);
    int (*Pathfollower__Getpathtype)(ZREF rPathFollower);
    int (*Pathfollower__Getusewalk)(ZREF rPathFollower);
    int (*Pathfollower__Getplayanimswhilewalking)(ZREF rPathFollower);
    ZREF (*Hm3Weapon__Getweapontemplate)(ZREF rWeapon);
    int (*Hm3Weapon__Getweapontype)(ZREF rWeapon);
    double (*Hm3Weapon__Gettimebetweenshots)(ZREF rWeapon);
    int (*Hm3Weapon__Getweaponoperations)(ZREF rWeapon);
    int (*Hm3Weapon__Weaponfiresprojectiles)(ZREF rWeapon);
    int (*Hm3Weapon__Getprojectilesinmagazine)(ZREF rWeapon);
    int (*Hm3Weapon__Emptyweapon)(ZREF rWeapon);
    int (*Hm3Weapon__Setprojectilesinmagazine)(ZREF rWeapon, char projectiles, int enabled);
    int (*Hm3Weapon__Weaponissmall)(ZREF rWeapon);
    int (*Hm3Weapon__Issniper)(ZREF rWeapon);
    int (*Hm3Weapon__Isdetectable)(ZREF rWeapon);
    void (*Coverlist__Releasecover)(ZREF rCoverList, sCover* cover);
    void (*Coverlist__Checkcoverfrompos)(ZREF rCoverList, ZREF rCover, v3 position, float distance, int direction, sCover* cover);
    void (*Coverlist__Getbestcoverfrompos)(ZREF rCoverList, ZREF rCover, v3 position, float distance, int direction, sCover* cover);
    void (*Coverlist__Getbestcover)(ZREF rCoverList, ZREF rCover, ZREF rPosition, float distance, int direction, sCover* cover);
    int (*Coverlist__Getcoverindexesaroundpos)(ZREF rCoverList, v3 position, float distance, int maxCount, int* coverIndex);
    void (*Coverlist__Getpisscover)(ZREF rCoverList, ZREF rCover, float distance, sCover* cover);
    void (*Coverlist__Getpissposdir)(ZREF rCoverList, ZREF rCover, sCover* cover);
    void (*Coverlist__Getcoverposdir)(ZREF rCoverList, sCover* cover);
    void (*Coverlist__Getcoverposdir_Pos)(ZREF rCoverList, sCover* cover, v3 position);
    void (*Coverlist__Getcoverposition)(ZREF rCoverList, int coverIndex, ZREF rPosition, v3* position);
    void (*Coverlist__Getshootposdir)(ZREF rCoverList, sCover* cover, int alternate);
    void (*Coverlist__Getshootposdir_Pos)(ZREF rCoverList, sCover* cover, v3 position, int alternate);
    void (*Coverlist__Getintermediateposition)(ZREF rCoverList, sCover cover, v3 position, sCover target, float distance, v3* result);
    void (*Actorcommunication__Registerradiouser)(ZREF rActor, int iChannel);
    void (*Actorcommunication__Sendradiomessage)(ZREF rActor, int iChannel, ZSC_EVENT event);
    void (*Actorcommunication__Sendradiomessagetoclosestn)(ZREF rActor, int iChannel, int n, ZSC_EVENT event);
    void (*Actorcommunication__Sendradiomessagetoneedeforce)(ZREF rActor, int iChannel, float force, ZSC_EVENT event);
    void (*Actorcommunication__Sendrangedmessage)(ZREF rActor, float range, ZSC_EVENT event);
    void (*Actorcommunication__Sendglobalevent)(ZREF rActor, ZSC_EVENT event);
    void (*Actorcommunication__Sendeventtoactorsinbox)(ZREF rActor, ZSC_EVENT event);
    void (*Actorcommunication__Sendeventtoactorsinbox2)(ZREF rActor, ZSC_EVENT event);
    int (*Fightcontroller__Attackingtarget)(ZREF rActor, int target, ZREF rTarget);
    void (*Fightcontroller__Requestcoverfire)(ZREF rActor, ZREF rTarget);
    void (*Fightcontroller__Huntingtarget)(ZREF rActor, int target, ZREF rTarget);
    void (*Fightcontroller__Standby)(ZREF rActor, int target, ZREF rTarget);
    int (*Fightcontroller__Updatetargetinfo)(ZREF rActor, ZREF rTarget, ZREF rTargetInfo);
    int (*Fightcontroller__Signoff)(ZREF rActor);
    ZREF (*Fightcontroller__Querytarget)(ZREF rActor, int target);
    ZREF (*Fightcontroller__Querytargetclose)(ZREF rActor);
    int (*Fightcontroller__Queryshouldattack)(ZREF rActor, ZREF rTarget);
    int (*Fightcontroller__Iscombathappening)();
    void (*Fightcontroller__Requestnewposition)(ZREF rPosition);
    void (*Guardquartercontroller__Initializeweaponstorage)(ZREF rGuardQuarterControl, ZREF rWeapon);
    void (*Guardquartercontroller__Registeractor)(ZREF rGuardQuarterControl, ZREF rActor);
    void (*Guardquartercontroller__Delegatetask)(ZREF rGuardQuarterControl, sGQCTask task);
    void (*Guardquartercontroller__Taskdone)(ZREF rGuardQuarterControl, ZREF rActor);
    void (*Guardquartercontroller__Accepttask)(ZREF rGuardQuarterControl, sGQCTask task);
    void (*Guardquartercontroller__Actornotavailable)(ZREF rGuardQuarterControl, ZREF rActor);
    ZREF (*Guardquartercontroller__Getclosestbodybagbox)(ZREF rGuardQuarterControl, ZREF rGeom);
    void (*Guardquartercontroller__Decreasebodybagboxcapacity)(ZREF rGuardQuarterControl, ZREF rBodyBagBox);
    int (*Guardquartercontroller__Canaddweapontostorage)(ZREF rGuardQuarterControl, ZREF rWeapon);
    void (*Guardquartercontroller__Placeweaponinstorage)(ZREF rGuardQuarterControl, ZREF rWeapon);
    void (*Guardquartercontroller__Removeweaponfromstorage)(ZREF rGuardQuarterControl, ZREF rWeapon);
    void (*Guardquartercontroller__Getstorageposdirref)(ZREF rGuardQuarterControl, v3* position, v3* direction, ZREF* rStorageRef);
    int (*Guardquartercontroller__Isweaponinstorage)(ZREF rGuardQuarterControl, ZREF rWeapon);
    ZREF (*Guardquartercontroller__Getweaponreffromstorage)(ZREF rGuardQuarterControl, ZREF rWeapon);
    void (*Dialog__Startdialog)(ZREF rActor, ZREF rPartner, const char* speechGroup, const char* speechGroup2, const char* speechGroup3);
    void (*Dialog__Startonelinerdialog)(ZREF rActor, ZREF rPartner, const char* speechGroup);
    void (*Dialog__Startonelinerdialognoturn)(ZREF rActor, ZREF rPartner, const char* speechGroup);
    void (*Dialog__Pushdialogcamera)(ZREF rActor, ZREF rPartner);
    void (*Dialog__Popdialogcamera)();
    void (*Dialog__Startdialogex)(ZREF rActor, ZREF rPartner, const char* speechGroup, const char* speechGroup2, const char* speechGroup3, int unknown, char unknown2, char unknown3, char unknown4, char unknown5);
    int (*Dialog__Isplaying)();
    void (*Dialog__Setnotifytarget)(ZREF rTarget, ZSC_EVENT event);
    void (*Dialog__Stopdialog)();
    int (*Dialog__Actorplaynextdialog)(ZREF rActor, const char* speechGroupPrefix, int dialogIndex, const char* speechGroupSuffix);
    int (*Dialog__Setdialogskipable)(char skipable);
    void (*Dialog__Sethmposbeforedialog)(v3 position);
    void (*Zusepoint__Lock)(ZREF rUsePoint);
    void (*Zusepoint__Unlock)(ZREF rUsePoint);
    void (*Zusepoint__Changeprobability)(ZREF rUsePoint, float probability);
    void (*Zusepoint__Relocate)(ZREF rUsePoint);
    int (*Zusepoint__Islocked)(ZREF rUsePoint);
    v3 (*Zgeom__Getsize)(ZREF rGeom);
    void (*Zgeom__Setposition)(ZREF rGeom, float x, float y, float z);
    v3 (*Zgeom__Getposition)(ZREF rGeom);
    void (*Zgeom__Getlocalpoint)(ZREF rGeom, v3* point);
    void (*Zgeom__Getposdir)(ZREF rGeom, v3* position, v3* direction);
    void (*Zgeom__Setposdir)(ZREF rGeom, v3* position, v3* direction);
    int (*Zgeom__Getclosestposdirinbox)(ZREF rBox, ZREF rGeom, ZREF rTarget, float radius, v3* position, v3* direction);
    float (*Zgeom__Getdistancetoobject)(ZREF rGeom, ZREF rTarget);
    float (*Zgeom__Getdistancetopos)(ZREF rGeom, v3 position);
    int (*Zgeom__Hascontroller)(ZREF rGeom, const char* controllerName);
    ZREF (*Zgeom__Getcontroller)(ZREF rGeom, const char* controllerName);
    float (*Zgeom__Getangletoobject)(ZREF rGeom, ZREF rTarget);
    float (*Zgeom__Getangletodir)(ZREF rGeom, v3 direction);
    float (*Zgeom__Getangletogeomdir)(ZREF rGeom, ZREF rTarget);
    void (*Zgeom__Copyobjectposdir)(ZREF rGeom, ZREF rTarget);
    void (*Zgeom__Copyobjectpos)(ZREF rGeom, ZREF rTarget);
    void (*Zgeom__Copyobjectdir)(ZREF rGeom, ZREF rTarget);
    v3 (*Zgeom__Getobjectrelpos)(ZREF rGeom, float x, float y, float z);
    int (*Zgeom__Checkworldpointinside)(ZREF rGeom, v3 worldPosition);
    int (*Zgeom__Isinview)(ZREF rGeom);
    void (*Zgeom__Printname)(ZREF rGeom);
    float (*Zgeom__Getdistancetoitem)(ZREF rGeom, ZREF rItem);
    void (*Zgeom__Makeinactive)(ZREF rGeom);
    void (*Zgeom__Makeactive)(ZREF rGeom);
    void (*Zgeom__Hide)(ZREF rGeom, int bHide);
    ZREF (*Zgeom__Getcurrentroom)(ZREF rGeom);
    int (*Zgeom__Numberofexitsfromgeomscurrentroom)(ZREF rGeom, ZREF rRoom);
    void (*Zhm3Boid__Die)(ZREF rBoid);
    float (*Zhm3Boid__Getdistancefrombonetoobject)(ZREF rBoid, int boneId, ZREF rTarget);
    v3 (*Zhm3Boid__Getfacing)(ZREF rBoid);
    void (*Zhm3Boid__Disableboid)(ZREF rBoid);
    void (*Zhm3Boid__Shootintoground)(ZREF rBoid);
    void (*Zhm3Boid__Disableallbehaviors)(ZREF rBoid);
    void (*Zhm3Boid__Updatelocalspace)(ZREF rBoid, char updateLocalSpace);
    void (*Zhm3Boid__Setminmaxspeed)(ZREF rBoid, float minSpeed, float maxSpeed);
    void (*Zhm3Boid__Resetspeed)(ZREF rBoid);
    void (*Zhm3Boid__Setminmaxforce)(ZREF rBoid, float minForce, float maxForce);
    void (*Zhm3Boid__Setvisionrangeandangle)(ZREF rBoid, float range, float angle);
    void (*Zhm3Boid__Applyconstantforce)(ZREF rBoid, float x, float y, float z, char enabled);
    void (*Zhm3Boid__Enablebanking)(ZREF rBoid, char enabled);
    void (*Zhm3Boid__Setforceconstraint)(ZREF rBoid, float x, float y, float z);
    void (*Zhm3Boid__Enableseparation)(ZREF rBoid, float weight, int enabled);
    void (*Zhm3Boid__Enablecohesion)(ZREF rBoid, int enabled);
    void (*Zhm3Boid__Enableallignment)(ZREF rBoid, int enabled);
    void (*Zhm3Boid__Enableflee)(ZREF rBoid, ZREF rFlee, float distance, int enabled);
    void (*Zhm3Boid__Enablefall)(ZREF rBoid, float x, float y, float z, int enabled);
    void (*Zhm3Boid__Enablestayinbox)(ZREF rBoid, ZREF rBox, int enabled);
    void (*Zhm3Boid__Enablestayinspherepos)(ZREF rBoid, v3 position, float radius, int enabled);
    void (*Zhm3Boid__Enablestayinsphere)(ZREF rBoid, ZREF rSphere, float radius, int enabled);
    void (*Zhm3Boid__Enablefollowwaypoints)(ZREF rBoid, ZREF rWaypointList, float distance, int loop, int enabled);
    void (*Zhm3Boid__Enablewander2D)(ZREF rBoid, float minX, float maxX, float minZ, float maxZ, int enabled);
    void (*Zhm3Boid__Enableseekref)(ZREF rBoid, ZREF rTarget, int enabled);
    void (*Zhm3Boid__Enableseekpos)(ZREF rBoid, v3 position, int enabled);
    void (*Zhm3Boid__Enablefallbehavior)(ZREF rBoid, float x, float y, float z, int enabled);
    void (*Zhm3Boid__Setdragtarget)(ZREF rBoid, ZREF rTarget, int boneId, v3 offset);
    void (*Zhm3Boid__Releasedragtarget)(ZREF rBoid, char enabled);
    void (*Zhm3Boid__Setpos)(ZREF rBoid, float x, float y, float z);
    void (*Zhm3Boid__Setglobalbonescale)(ZREF rBoid, float scale);
    void (*Friskbox__Addguardtofriskbox)(ZREF rFriskbox, ZREF rGuard);
    void (*Friskbox__Removeguardfromfriskbox)(ZREF rFriskbox, ZREF rGuard);
    void (*Friskbox__Setenabled)(ZREF rFriskbox, int enabled);
    char (*Friskbox__Isenabled)(ZREF rFriskbox);
    char (*Friskbox__Playfriskokanimmirrored)(ZREF rFriskbox, ZREF rActor);
    void (*Friskbox__Addsuitcase)(ZREF rFriskbox, ZREF rSuitcase);
    void (*Friskbox__Removesuitcase)(ZREF rFriskbox, ZREF rSuitcase);
    char (*Friskbox__Ishitmancarryingconfsuitcase)(ZREF rFriskbox);
    void (*Friskbox__Setsuitcaseplaced)(ZREF rFriskbox, ZREF rSuitcase);
    char (*Friskbox__Issurrendweaponenabled)(ZREF rFriskbox);
    char (*Friskbox__Canpickupweaponsitems)(ZREF rFriskbox);
    void (*Friskbox__Sethitmanssuitcasechecked)(ZREF rFriskbox, int checked);
    void (*Osd__Addinfo)(const char* localeFile, const char* localeKey);
    void (*Osd__Addtickoffmark)();
    ZREF (*Zhm3Securitycamera__Getfusebox)(ZREF rCamera);
    int (*Zhm3Securitycamera__Getradiochannel)(ZREF rCamera);
    v3 (*Zhm3Securitycamera__Getfootpoint)(ZREF rCamera);
    void (*Poscontroller__Addactor)(ZREF rPosController, ZREF rActor);
    void (*Poscontroller__Removeactor)(ZREF rPosController, ZREF rActor);
    v3 (*Poscontroller__Getposition)(ZREF rPosController, ZREF rActor);
    char (*M04Levelcontrol__Isglobeopen)();
    char (*M04Levelcontrol__Didhmtalktoagent)();
    char (*M04Levelcontrol__Ishmashitman)();
    char (*M04Levelcontrol__Ishmasbodyguard)();
    char (*M04Levelcontrol__Ishmaspatient)();
    char (*M04Levelcontrol__Ishmasguard)();
    char (*M04Levelcontrol__Ishmaswarden)();
    char (*M04Levelcontrol__Ishmastherapist)();
    void (*M11Levelcontrol__Additemforcolicheck)(ZREF rItem, ZREF rActor, float duration);
    void (*M11Levelcontrol__Removeitemforcolicheck)(ZREF rItem);
    void (*M11Levelcontrol__Activatecoliforactor)(ZREF rActor);
    void (*M11Levelcontrol__Deactivatecoliforactor)(ZREF rActor);
    void (*M11Levelcontrol__Setarranger)(ZREF rActor);
    void (*M11Levelcontrol__Setangel)(ZREF rActor);
    void (*M11Levelcontrol__Usecomputer)(ZREF rComputer, int bEnabled);
    void (*M11Levelcontrol__Throwknife)(ZREF rActor);
    void (*M11Levelcontrol__Operateprojector)(ZREF rGeom);
    void (*M11Levelcontrol__Startprojector)(int bEnabled);
    void (*M11Levelcontrol__Removefromwaterbox)(ZREF rGeom);
    float (*M11Levelcontrol__Karoketimeplayed)();
    void (*M11Levelcontrol__Disablecrowdframeupdate)(int bDisabled);
    void (*M12Levelcontrol__Sionhighnoon)();
    void (*M12Levelcontrol__Siafterhighnoon)();
    int (*M12Levelcontrol__Sihighnoonactive)();
    int (*M12Levelcontrol__Sihighnoonsilenced)();
    int (*M12Levelcontrol__Isweaponremotebomb)(ZREF rWeapon);
    void (*M12Levelcontrol__Displaybombhint)();
    void (*M12Levelcontrol__Moveobject)(ZREF rObject, ZREF rPosition, ZREF rDirection, float fTime, float fBlendTime);
    void (*M12Levelcontrol__Disablehitmancontrols)(int bDisabled);
    void (*M12Levelcontrol__Hitmanfallforward)();
    int (*Holevelcontrol__Hideoutcheckitem)(ZREF rItem);
    void (*Holevelcontrol__Checkcustomweaponstate)(ZREF rWeapon);
    void (*Holevelcontrol__Showhappysubtitle)(const char* text, float seconds);
    int (*Bloodtrail__Isbloodtrail)(ZREF rGeom);
    ZREF (*Bloodtrail__Getnexttrailpoint)(ZREF rTrail);
    int (*Bloodtrail__Gettrailnumber)(ZREF rTrail);
    void (*Bloodtrail__Deactivatetrail)(ZREF rTrail);
    void (*Cigs__Getcig)(ZREF rCigs, ZREF* rCig);
    void (*Cigs__Freecig)(ZREF rCigs, ZREF rCig);
    ZREF (*Zlist__Getrndref)(ZREF rList);
    int (*Zlist__Getcount)(ZREF rList);
    ZREF (*Zlist__Getref)(ZREF rList, int index);
    int (*Zlist__Getindex)(ZREF rList, ZREF rItem);
    int (*Zlist__Contains)(ZREF rList, ZREF rItem);
    void (*Zlist__Add)(ZREF rList, ZREF rItem);
    void (*Zlist__Remove)(ZREF rList, ZREF rItem);
    void (*Zlist__Clear)(ZREF rList);
    void (*Zlist__Sendeventtolist)(ZREF rList, ZSC_EVENT event);
    void (*Addlinedecay)(v3 start, v3 end, int color, float decay);
    void (*Addvectordecay)(v3 start, v3 end, float decay, int color, float arrowLength);
    void (*Debugfunctions__Displayscriptline)(ZREF firstGeom, ZREF secondGeom, int color);
    void (*Debugfunctions__Displayscriptlinefrompos)(v3 start, v3 end, int color);
    int (*Debugfunctions__Displaypermanentscriptline)(ZREF firstGeom, ZREF secondGeom, int color);
    int (*Debugfunctions__Displaypermanentscriptlinefrompos)(v3 start, v3 end, int color);
    int (*Debugfunctions__Modifypermanentscriptline)(int line, ZREF firstGeom, ZREF secondGeom, int color);
    int (*Debugfunctions__Addpermanentscripttext)(ZREF geom, int height, int color, const char* format, ...);
    int (*Physics__Releasebone)(ZREF rGeom, v3 impulse, float force);
    int (*Physics__Setvelocity)(ZREF rGeom, float xRotation, float yRotation, float zRotation, v3 velocity);
    int (*Item__Attachrhand)(ZREF rActor, ZREF rItem);
    int (*Item__Attachlhand)(ZREF rActor, ZREF rItem);
    int (*Item__Detachrhand)(ZREF rActor, ZREF rItem);
    int (*Item__Detachlhand)(ZREF rActor, ZREF rItem);
    void (*Item__Resetedibleitem)(ZREF rItem, v3 position);
    ZREF (*Item__Getlhanditem)(ZREF rActor);
    ZREF (*Item__Getrhanditem)(ZREF rActor);
    void (*Item__Enablepickup)(ZREF rItem, int bEnabled);
    int (*Item__Setowner)(ZREF rOwner, ZREF rItem);
    int (*Item__Setownerparent)(ZREF rParent, ZREF rOwner, ZREF rItem);
    ZREF (*Item__Getparent)(ZREF rItem);
    ZREF (*Item__Getowner)(ZREF rItem);
    void (*Item__Setitemstate)(ZREF rItem, int state);
    int (*Item__Getitemstate)(ZREF rItem);
    int (*Item__Isitemhidden)(ZREF rItem);
    int (*Item__Isitemactive)(ZREF rItem);
    ZREF (*Item__Sliprighthanditem)(ZREF rActor);
    ZREF (*Item__Sliprighthanditemnoevent)(ZREF rActor);
    ZREF (*Item__Sliplefthanditem)(ZREF rActor);
    ZREF (*Item__Sliplefthanditemnoevent)(ZREF rActor);
    int (*Item__Isitemcontainer)(ZREF rItem);
    void (*Item__Insertitemincontainer)(ZREF rContainer, ZREF rItem);
    void (*Item__Removeitemfromcontainer)(ZREF rContainer, ZREF rItem);
    ZREF (*Item__Putlhitemtopos)(ZREF rActor, v3 position);
    ZREF (*Item__Putrhitemtopos)(ZREF rActor, v3 position);
    int (*Item__Containweapons)(ZREF rItem);
    int (*Item__Containmetallicweapons)(ZREF rItem);
    int (*Item__Iscontainerisempty)(ZREF rItem);
    void (*Item__Setvisibletonpcs)(ZREF rItem, int bVisible);
    int (*Item__Iscontainercontainsitem)(ZREF rContainer, ZREF rItem);
    ZREF (*Item__Getitemincontainer)(ZREF rContainer, const char* itemName);
    void (*Item__Clearfooddrinkinfection)(ZREF rItem);
    anim (*Item__Getanim)(ZREF rItem, const char* name);
    int (*Item__Playanimsegment)(ZREF rItem, anim animId, int segment, float start, float end, float blendTime);
    int (*Item__Useitemactivateanimation)(ZREF rItem);
    void (*Item__Setforceunpickablebyhm)(ZREF rItem, int forceUnpickable);
    int (*Item__Getforceunpickablebyhm)(ZREF rItem);
    void (*Item__Hideitem)(ZREF rItem);
    void (*Item__Showitem)(ZREF rItem);
    int (*Item__Isitemlarge)(ZREF rItem);
    int (*Item__Isitemcigarette)(ZREF rItem);
    int (*Item__Hastemplate)(ZREF rTemplate, ZREF rItem);
    int (*Item__Isitemontopofelevator)(ZREF rItem);
    void (*Item__Setscale)(ZREF rItem, float scale);
    void (*Print)(const char* format, ...);
    void (*Error)(const char* format, ...);
    void (*Warning)(const char* format, ...);
    void (*Zscassert)(int bCond);
    float (*Engine__Random)();
    int (*Engine__Randomrange)(int min, int max);
    float (*Engine__Gettime)();
    ZREF (*Engine__Getsceneval)(const char* name);
    void (*Engine__Setsceneval)(const char* name, ZREF value);
    int (*Engine__Localeexists)(const char* name);
    int (*Engine__Isvalidvector)(float x, float y, float z);
    void (*Scene__Setobjectposition)(ZREF rObject, float x, float y, float z);
    void (*Scene__Setobjectpositionv3)(ZREF rObject, v3 position);
    v3 (*Scene__Getobjectposition)(ZREF rObject);
    int (*Scene__Getgeomsinsidebox)(ZREF rBox, ZREF* outGeoms, int maxGeoms, int includeInactive, int includeChildren);
    int (*Scene__Getactorsinbox)(ZREF rBox, ZREF* outActors, int maxActors);
    int (*Scene__Isbox)(ZREF rObject);
    int (*Scene__Isposinsidebox)(ZREF rBox, v3 position);
    v3 (*Scene__Getposinbox)(ZREF rBox);
    void (*Scene__Setscale)(ZREF rObject, float x, float y, float z);
    int (*Scene__Objecthascontroller)(ZREF rObject, const char* controllerName);
    ZREF (*Scene__Getcontrolleronobject)(ZREF rObject, const char* controllerName);
    float (*Scene__Getdistancebetweenobjects)(ZREF firstObject, ZREF secondObject);
    float (*Scene__Getdistbetweenobjectandpos)(ZREF rObject, v3 position);
    float (*Scene__Getdistbetweenobjectandpos2D)(ZREF rObject, v3 position);
    int (*Scene__Getnumofaccessdenies)(ZREF rObject, int accessType);
    void (*Scene__Makeinactive)(ZREF rObject);
    void (*Scene__Makeactive)(ZREF rObject);
    int (*Scene__Getdoorstatus)(ZREF rObject);
    ZREF (*Scene__Getparent)(ZREF rObject);
    int (*Scene__Isshattered)(ZREF rObject);
    int (*Scene__Isground)(ZREF rObject);
    int (*Scene__Setnoiselevel)(ZREF rObject, int level);
    int (*Scene__Getnoiselevel)(ZREF rObject);
    int (*Scene__Getisinoutsidelocation)(ZREF rObject);
    int (*Audio__Playsound2D)(int soundId);
    int (*Audio__Playsound3D)(int soundId, ZREF object);
    int (*Audio__Playlocaleresource2D)(const char* name);
    int (*Audio__Getlocaleresource)(const char* name);
    void (*Audio__Setnotifytarget)(ZREF target, int soundObject);
    float (*Audio__Gettimeplayed)(ZREF soundObject);
    float (*Audio__Gettimeleft)(ZREF soundObject);
    void (*Audio__Stopsound)(ZREF soundObject);
    void (*Audio__Setvolume)(ZREF soundObject, float volume);
    ZREF (*Audio__Getsndobjsoundobjectref)(ZREF object);
    void (*Audio__Setsoundobjectautodelete)(ZREF soundObject, int autoDelete);
    void (*Math__Vset)(v3* result, float x, float y, float z);
    void (*Math__Vcpy)(v3* result, v3 source);
    void (*Math__Vscalar)(v3* result, v3 source, float scalar);
    void (*Math__Vaddscalar)(v3* result, v3 first, v3 second, float scalar);
    float (*Math__Vdist)(v3 first, v3 second);
    void (*Math__Vsub)(v3* result, v3 first, v3 second);
    void (*Math__Vadd)(v3* result, v3 first, v3 second);
    void (*Math__Vneg)(v3* result);
    void (*Math__Vreset)(v3* result);
    float (*Math__Vdot)(v3 first, v3 second);
    float (*Math__Vlen)(v3 value);
    void (*Math__Vnorm)(v3* value);
    void (*Math__Vpul)(v3* result, v3 first, v3 second, float factor);
    float (*Math__Sqrtf)(float value);
    void (*Math__Vrot)(v3* result, v3 rotation);
    int (*Istring__Isnameequal)(ZREF geom, const char* name);
    int (*Istring__Isnamecontains)(ZREF geom, const char* name);
    int (*Istring__Isempty)(const char* value);
    int (*Pathfinder__Isvectinside)(v3 position);
    int (*Pathfinder__Isposinside)(float x, float y, float z);
    v3 (*Pathfinder__Getsearchposaroundpos)(v3 position, float radius, int divisions, int index);
    v3 (*Pathfinder__Getposaroundpos)(v3 position, float radius);
    v3 (*Pathfinder__Getentitypos)(ZREF entity);
    v3 (*Pathfinder__Getclosestwallpos)(ZREF actor, v3 position);
    void (*Pathfinder__Teleportboid)(ZREF boid, v3 position);
    int (*Pathfinder__Iswallbetweenpoints)(v3 first, v3 second);
} SCRIPTIMPORTSTABLE;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __HBM_SCRIPT_RUNTIME_ZSCRIPTIMPORTTABLE_H__ */
