#pragma once

#include <BloodMoney/Game/ZHM3Actor.h>
#include <Glacier/GlacierFWD.h>
#include <Glacier/ScriptEngine/Common.h>
#include <Glacier/ZREF.h>
#include <cstdint>

namespace Glacier
{
    void Zhm3Actor__Setblinking(ZREF rActor, bool disabled);
    void Zhm3Actor__Initmapicon(ZREF rActor);
    void Zhm3Actor__Forceshowmapicon(ZREF rActor);
    void Zhm3Actor__Die(ZREF rActor);
    void Zhm3Actor__Initializehitpoints(ZREF rActor, int hitPoints);
    void Zhm3Actor__Sethitpoints(ZREF rActor, float hitPoints);
    void Zhm3Actor__Setcharactertype(ZREF rActor, Hitman::BloodMoney::eCharacterType characterType);
    Hitman::BloodMoney::eCharacterType Zhm3Actor__Getcharactertype(ZREF rActor, ZREF rDefaultActor);
    void Zhm3Actor__Changemapiconandcharactertype(ZREF rActor, Hitman::BloodMoney::eCharacterType characterType, bool forceDeadIcon);
    void Zhm3Actor__Removefrommap(ZREF rActor);
    float Zhm3Actor__Gethitpoints(ZREF rActor);
    float Zhm3Actor__Takedamage(ZREF rActor, float damage);
    void Zhm3Actor__Setleavebloodtrail(ZREF rActor, bool enabled);
    void Zhm3Actor__Setvisionrangesandfovs(ZREF rActor, float closeRange, float closeFov, float farRange, float farFov);
    void Zhm3Actor__Setvisionrangeandfov(ZREF rActor, float range, float fov);
    void Zhm3Actor__Setmood(ZREF rActor, uint8_t mood, float intensity);
    float Zhm3Actor__Gettension(ZREF rActor);
    void Zhm3Actor__Settension(ZREF rActor, Hitman::BloodMoney::eInterestLevel interestLevel);
    void Zhm3Actor__Increasetension(ZREF rActor, Hitman::BloodMoney::eInterestLevel interestLevel, float amount);
    void Zhm3Actor__Releasetension(ZREF rActor, Hitman::BloodMoney::eInterestLevel interestLevel);
    uint8_t Zhm3Actor__Getmaxneed(ZREF rActor, float value);
    void Zhm3Actor__Setneed(ZREF rActor, uint8_t need, float value);
    void Zhm3Actor__Setneedtime(ZREF rActor, uint8_t need, float value);
    float Zhm3Actor__Getneed(ZREF rActor, uint8_t need);
    void Zhm3Actor__Lockubanim(ZREF rActor, bool locked);
    void Zhm3Actor__Enableubholdanims(ZREF rActor);
    void Zhm3Actor__Disableubholdanims(ZREF rActor);
    bool Zhm3Actor__Enableubholdanim(ZREF rActor);
    bool Zhm3Actor__Isubanimlocked(ZREF rActor);
    int Zhm3Actor__Setscriptubanim(ZREF rActor, anim animId);
    void Zhm3Actor__Resetscriptubanim(ZREF rActor);
    int Zhm3Actor__Playscriptubanim(ZREF rActor, anim animId, bool force);
    int Zhm3Actor__Playscriptubanimloop(ZREF rActor, anim animId, bool force);
    int Zhm3Actor__Stopscriptubanimplay(ZREF rActor);
    bool Zhm3Actor__Hasrunningubanim(ZREF rActor);
    void Zhm3Actor__Setweapontemplate(ZREF rActor, ZREF rWeaponTemplate);
    ZREF Zhm3Actor__Getweapontemplate(ZREF rActor);
    void Zhm3Actor__Setweapon(ZREF rActor, ZREF rWeapon);
    void Zhm3Actor__Resetweapon(ZREF rActor);
    ZREF Zhm3Actor__Getweapon(ZREF rActor);
    void Zhm3Actor__Setammoinweapon(ZREF rActor, int ammo);
    void Zhm3Actor__Pullweapon(ZREF rActor);
    bool Zhm3Actor__Ownsownweapon(ZREF rActor);
    bool Zhm3Actor__Isweapondrawn(ZREF rActor);
    bool Zhm3Actor__Currentweaponcanbeholstered(ZREF rActor);
    bool Zhm3Actor__Holsterweapon(ZREF rActor);
    bool Zhm3Actor__Isholdingitem(ZREF rActor);
    bool Zhm3Actor__Hasfreehand(ZREF rActor);
    bool Zhm3Actor__Islinkactionrunning(ZREF rActor);
    void Zhm3Actor__Putiteminrightpocket(ZREF rActor, ZREF rItem);
    void Zhm3Actor__Putiteminleftpocket(ZREF rActor, ZREF rItem);
    bool Zhm3Actor__Pullitemfromrightpocket(ZREF rActor, ZREF rItem);
    bool Zhm3Actor__Pullitemfromleftpocket(ZREF rActor, ZREF rItem);
    void Zhm3Actor__Setisholdingshootableiteml(ZREF rActor, bool holding);
    void Zhm3Actor__Setisholdingshootableitemr(ZREF rActor, bool holding);
    void Zhm3Actor__Makeitemvisible(ZREF rActor, ZREF rItem);
    void Zhm3Actor__Makeiteminvisible(ZREF rActor, ZREF rItem);
    bool Zhm3Actor__Makeactorvisible(ZREF rActor, ZREF rTarget);
    bool Zhm3Actor__Makeactorinvisible(ZREF rActor, ZREF rTarget);
    void Zhm3Actor__Removedecal(ZREF rActor, int decalId);
    int Zhm3Actor__Setvisibletypes(ZREF rActor, int visibleTypes);
    int Zhm3Actor__Getvisibletypes(ZREF rActor);
    void Zhm3Actor__Setseerblind(ZREF rActor, bool blind);
    bool Zhm3Actor__Disablevision(ZREF rActor, ZREF rTarget);
    bool Zhm3Actor__Enablevision(ZREF rActor, ZREF rTarget);
    void Zhm3Actor__Disablepickupclothes(ZREF rActor, ZREF rClothes);
    void Zhm3Actor__Enablepickupclothes(ZREF rActor, ZREF rClothes);
    int Zhm3Actor__Getvisibleprojectileweapons(ZREF rActor, ZREF* outWeapons, int maxWeapons, ZREF rExcludeWeapon);
    bool Zhm3Actor__Isitemedible(ZREF rActor, ZREF rItem);
    bool Zhm3Actor__Isitemdrinkable(ZREF rActor, ZREF rItem);
    int Zhm3Actor__Getitemnumbitestotal(ZREF rActor, ZREF rItem);
    int Zhm3Actor__Getitemnumbites(ZREF rActor, ZREF rItem);
    int Zhm3Actor__Removeitembite(ZREF rActor, ZREF rItem);
    void Zhm3Actor__Restoreitembites(ZREF rActor, ZREF rItem, int bites);
    int Zhm3Actor__Getiteminfectiontype(ZREF rActor, ZREF rItem);
    void Zhm3Actor__Aimweaponatgeom(ZREF rActor, ZREF rTarget, float blendTime);
    void Zhm3Actor__Aimweaponatpos(ZREF rActor, v3 position, float blendTime);
    void Zhm3Actor__Fireweapon(ZREF rActor, bool fire, float blendTime, bool unknown);
    void Zhm3Actor__Playfireweaponsound(ZREF rActor, ZREF rWeapon);
    void Zhm3Actor__M12_Albinofireweapon(ZREF rActor, bool fire, float blendTime, bool unknown);
    bool Zhm3Actor__Triggerweaponpush(ZREF rActor, ZREF rWeapon);
    bool Zhm3Actor__Isaiminposition(ZREF rActor);
    bool Zhm3Actor__Isaimingattarget(ZREF rActor, ZREF rTarget, float tolerance, ZREF& rAimedTarget, v3& aimPosition);
    bool Zhm3Actor__Reloadweapon(ZREF rActor, bool instant);
    int Zhm3Actor__Numberofshotsleft(ZREF rActor);
    bool Zhm3Actor__Isbodyknownandunchanged(ZREF rActor, ZREF rBody);
    void Zhm3Actor__Registerdeadbody(ZREF rActor, ZREF rBody);
    bool Zhm3Actor__Isobjectvisible(ZREF rActor, ZREF rObject);
    bool Zhm3Actor__Objectisinfront(ZREF rActor, ZREF rObject);
    float Zhm3Actor__Chkcolibeforeactor(ZREF rActor, float distance, float radius, v3& position);
    ZREF Zhm3Actor__Isitemininventory(ZREF rActor, const char* itemName);
    bool Zhm3Actor__Additemtoinventory(ZREF rActor, ZREF rItem);
    bool Zhm3Actor__Removeitemfrominventory(ZREF rActor, ZREF rItem);
    void Zhm3Actor__Dumpinventorytoground(ZREF rActor);
    ZREF Zhm3Actor__Undress(ZREF rActor);
    bool Zhm3Actor__Dress(ZREF rActor, ZREF rClothes);
    void Zhm3Actor__Dialoglisten(ZREF rActor);
    void Zhm3Actor__Dialogtalk(ZREF rActor);
    void Zhm3Actor__Throwknifeatref(ZREF rActor, ZREF rKnife, ZREF rTarget);
    bool Zhm3Actor__Findsitdowngeom(ZREF rActor, v3& position, v3& direction, int& seatIndex, int flags, ZREF rIgnore);
    int Zhm3Actor__Sitdown(ZREF rActor, anim animId, bool instant);
    int Zhm3Actor__Sitdowninstant(ZREF rActor, anim animId, bool instant);
    bool Zhm3Actor__Movechairifapplicable(ZREF rActor, anim animId, bool instant);
    void Zhm3Actor__Movechair(ZREF rActor, anim animId, bool instant);
    void Zhm3Actor__Situp(ZREF rActor);
    bool Zhm3Actor__Findliedowngeom(ZREF rActor, v3& position, v3& direction, bool allowOccupied);
    int Zhm3Actor__Liedown(ZREF rActor, bool instant);
    ZREF Zhm3Actor__Findlightswitch(ZREF rActor);
    void Zhm3Actor__Togglelightswitch(ZREF rActor, ZREF rLightSwitch, bool on);
    bool Zhm3Actor__Getlightswitchstate(ZREF rActor, ZREF rLightSwitch);
    int Zhm3Actor__Getbodyposition(ZREF rActor);
    void Zhm3Actor__Setbodyposition(ZREF rActor, int bodyPosition);
    void Zhm3Actor__Setbodypositionunknown(ZREF rActor);
    void Zhm3Actor__Setbodypositionnormal(ZREF rActor);
    void Zhm3Actor__Sethmescort(ZREF rActor, ZREF rEscort);
    ZREF Zhm3Actor__Gethmescort(ZREF rActor);
    void Zhm3Actor__Playsound(ZREF rActor, eAudioEvent audioEvent);
    bool Zhm3Actor__Isweaponallowed(ZREF rActor, ZREF rWeapon);
    bool Zhm3Actor__Isweaponfoundathitman(ZREF rActor);
    ZREF Zhm3Actor__Transferhitmanweaponstoactor(ZREF rActor);
    bool Zhm3Actor__Isonback(ZREF rActor);
    void Zhm3Actor__Setneardeath(ZREF rActor, bool nearDeath);
    void Zhm3Actor__Dropbloodstain(ZREF rActor);
    void Zhm3Actor__Activatebloodspurt(ZREF rActor, int bloodSpurt, v3& position);
    bool Zhm3Actor__Wantbloodstain(ZREF rActor, bool wantBloodStain);
    void Zhm3Actor__Setwantbloodonhit(ZREF rActor, bool wantBloodOnHit);
    bool Zhm3Actor__Isactor(ZREF rActor, ZREF rTarget);
    bool Zhm3Actor__Ishitmandraggingactor(ZREF rActor, ZREF rTarget);
    bool Zhm3Actor__Iswearingclothes(ZREF rActor, ZREF rClothes);
    ZREF Zhm3Actor__Getoriginalsuit(ZREF rActor, ZREF rClothes);
    bool Zhm3Actor__Getflankingpos(ZREF rActor, ZREF rTarget, eDirection direction, v3& position);
    bool Zhm3Actor__Getbodycheckposdir(ZREF rActor, ZREF rBody, v3& position, v3& direction);
    void Zhm3Actor__Getposonpath(ZREF rActor, ZREF rPath, float distance, v3& position);
    void Zhm3Actor__Blowhitmandisguise(ZREF rActor);
    void Zhm3Actor__Generateaudioevent(ZREF rActor, eAudioEvent audioEvent);
    void Zhm3Actor__Playactorspeech(ZREF rActor, eAudioType audioType, eAudioEvent audioEvent);
    int Zhm3Actor__Playresourceasspeech(ZREF rActor, int resourceId);
    int Zhm3Actor__Playlocaleresourceasspeech(ZREF rActor, const char* resourceName);
    int Zhm3Actor__Getlocalesoundresource(ZREF rActor, const char* resourceName);
    int Zhm3Actor__Playrandomlocaleresourceasspeech(ZREF rActor, const char* resourceName);
    bool Zhm3Actor__Isspeechplaying(ZREF rActor);
    void Zhm3Actor__Stopspeech(ZREF rActor);
    void Zhm3Actor__Bite(ZREF rActor, int16_t animVariation, v3 from, v3 to, float blendIn, float blendOut);
    void Zhm3Actor__Punch(ZREF rActor);
    void Zhm3Actor__Stungunattack(ZREF rActor);
    void Zhm3Actor__Activaterigidbody(ZREF rActor);
    void Zhm3Actor__Userigidbodyonpush(ZREF rActor, bool enabled);
    void Zhm3Actor__Useubragdoll(ZREF rActor, bool enabled);
    void Zhm3Actor__Dragbody(ZREF rActor, ZREF rBody);
    bool Zhm3Actor__Actorbeingpushed(ZREF rActor);
    bool Zhm3Actor__Isactorbeingkilled(ZREF rActor, ZREF rTarget);
    void Zhm3Actor__Changeintobodybag(ZREF rActor, ZREF rTarget);
    bool Zhm3Actor__Isbodybag(ZREF rActor, ZREF rTarget);
    bool Zhm3Actor__Maybebodybagged(ZREF rActor, ZREF rTarget);
    void Zhm3Actor__Setmaybebodybagged(ZREF rActor, bool maybeBodyBagged);
    void Zhm3Actor__Setignorehelprequests(ZREF rActor, bool ignoreHelpRequests);
    void Zhm3Actor__Setissearching(ZREF rActor, bool isSearching);
    void Zhm3Actor__Disabledrag(ZREF rActor, ZREF rBody);
    int Zhm3Actor__Getnumberofavailableragdolls(ZREF rActor);
    void Zhm3Actor__Setactorspecies(ZREF rActor, int actorSpecies);
    void Zhm3Actor__Sendeventtoactorswithinbox(ZREF rActor, ZSC_EVENT event, ZREF rBox);
    int Zhm3Actor__Playanimwithcamerabone(ZREF rActor, anim animId);
    ZREF Zhm3Actor__Findclosestcharactertype(ZREF rActor, int actorType, v3 position, float radius);
    void Zhm3Actor__Disableragdollanddieanim(ZREF rActor);
    void Zhm3Actor__Dummy(ZREF rActor);
    void Zhm3Actor__Repairutilbox(ZREF rActor, ZREF rUtilBox);
    void Zhm3Actor__Terminatecurrentlnkaction(ZREF rActor);
    int Zhm3Actor__Getsecuritydeviceloopingsound(ZREF rActor, ZREF rSecurityDevice);
    int Zhm3Actor__Getsecuritydeviceweaponfoundsound(ZREF rActor, ZREF rSecurityDevice);
    void Zhm3Actor__Activateragdollnextframe(ZREF rActor);
    void Zhm3Actor__Activateragdoll(ZREF rActor);
    void Zhm3Actor__Hitragdoll(ZREF rActor, v3 position, v3 impulse, float force);
    bool Zhm3Actor__Ishitmanvisible(ZREF rActor);
    void Zhm3Actor__Setignoredisguise(ZREF rActor, bool ignoreDisguise);
    bool Zhm3Actor__Isignoredisguise(ZREF rActor);
    bool Zhm3Actor__Canplayanimpf(ZREF rActor, anim animId, int flags);
    void Zhm3Actor__Setposdiractor(ZREF rActor, v3& position, v3& direction);
    float Zhm3Actor__Calculatestopdistancetoavoidobstacle(ZREF rActor);
    void Zhm3Actor__Setinterruptable(ZREF rActor, bool interruptable);
    void Zhm3Actor__Positionlock(ZREF rActor);
    void Zhm3Actor__Positionunlock(ZREF rActor);
    bool Zhm3Actor__Isanimubanim(ZREF rActor, anim animId);
    float Zhm3Actor__Getangletoactor2(ZREF rActor, ZREF rTarget, ZREF rReference);
    void Zhm3Actor__Addmouthemitter(ZREF rActor, ZREF rEmitter);
    void Zhm3Actor__Removemouthemitter(ZREF rActor, ZREF rEmitter);
    void Zhm3Actor__Onpickupitem(ZREF rActor, ZREF rItem);
    bool Zhm3Actor__Isenteringorleavingelevator(ZREF rActor);
    bool Zhm3Actor__Isinorusingelevator(ZREF rActor);
    bool Zhm3Actor__Isinoutsidelocation(ZREF rActor);
    ZREF Zhm3Actor__Isinelevator(ZREF rActor);
    ZREF Zhm3Actor__Getelevatorhatchgeom(ZREF rActor);
    void Zhm3Actor__Broadcasttoothersinelevator(ZREF rActor, ZREF rElevator, ZSC_EVENT event);
    bool Zhm3Actor__Isaccidentkilled(ZREF rActor);
    bool Zhm3Actor__Ispointinsideelevatorarea(ZREF rActor, v3 position);
    void Zhm3Actor__Setsuspectedsuit(ZREF rActor, ZREF rSuit);
    bool Zhm3Actor__Ishitmanhidingbehindnextdoor(ZREF rActor, ZREF& rDoor, v3& position);
    void Zhm3Actor__Idlelookat(ZREF rActor, ZREF rTarget);
    void Zhm3Actor__Setdisableragdollforshots(ZREF rActor, bool disable);
}
