#pragma once

namespace Glacier
{
    class ZHM3Actor
    {
    public:
        /*
            .data:00573770 off_573770:     .word _ZN9ZHM3ActorD1Ev  # DATA XREF: ZHM3Actor::ZHM3Actor(char const*,ZBaseGeom *)+4Co
            .data:00573774                 .word _ZN9ZHM3ActorD0Ev  # ZHM3Actor::~ZHM3Actor()
            .data:00573778                 .word _ZN13ZSerializable7PreSaveER17ISerializerStream  # ZSerializable::PreSave(ISerializerStream &)
            .data:0057377C                 .word _ZN9ZHM3Actor8PostSaveER17ISerializerStream  # ZHM3Actor::PostSave(ISerializerStream &)
            .data:00573780                 .word _ZN13ZSerializable7PreLoadER17ISerializerStream  # ZSerializable::PreLoad(ISerializerStream &)
            .data:00573784                 .word _ZN9ZHM3Actor8PostLoadER17ISerializerStream  # ZHM3Actor::PostLoad(ISerializerStream &)
            .data:00573788                 .word _ZN13ZSerializable11PostProcessEjj  # ZSerializable::PostProcess(uint,uint)
            .data:0057378C                 .word _ZN6ZActor8LoadSaveER17ISerializerStreamb  # ZActor::LoadSave(ISerializerStream &,bool)
            .data:00573790                 .word _ZN5ZGEOM10LoadObjectER22IInputSerializerStream  # ZGEOM::LoadObject(IInputSerializerStream &)
            .data:00573794                 .word _ZN5ZGEOM10SaveObjectER23IOutputSerializerStream  # ZGEOM::SaveObject(IOutputSerializerStream &)
            .data:00573798                 .word _ZN13ZSerializable14ExchangeObjectER17ISerializerStream  # ZSerializable::ExchangeObject(ISerializerStream &)
            .data:0057379C                 .word _ZN13ZSerializable12SetToDefaultEv  # ZSerializable::SetToDefault(void)
            .data:005737A0                 .word _ZN3RTP5cBase9GetTypeIDEv  # RTP::cBase::GetTypeID(void)
            .data:005737A4                 .word _ZNK9ZHM3Actor13GetPropertiesEv  # ZHM3Actor::GetProperties(void)
            .data:005737A8                 .word _ZNK9ZHM3Actor11GetObjectIdEv  # ZHM3Actor::GetObjectId(void)
            .data:005737AC                 .word _ZNK9ZHM3Actor18GetObjectIdAndMaskERjS0_  # ZHM3Actor::GetObjectIdAndMask(uint &,uint &)
            .data:005737B0                 .word _ZNK9ZHM3Actor15GetOldClassInfoEv  # ZHM3Actor::GetOldClassInfo(void)
            .data:005737B4                 .word _ZN5ZGEOM6DoInitEv  # ZGEOM::DoInit(void)
            .data:005737B8                 .word _ZN7ZLNKOBJ11CalcCenSizeEv  # ZLNKOBJ::CalcCenSize(void)
            .data:005737BC                 .word _ZN5ZGEOM11PreSaveGameEv  # ZGEOM::PreSaveGame(void)
            .data:005737C0                 .word _ZN5ZGEOM14CheckPointSaveER17ZCheckPointBuffer  # ZGEOM::CheckPointSave(ZCheckPointBuffer &)
            .data:005737C4                 .word _ZN5ZGEOM14CheckPointLoadER17ZCheckPointBuffer  # ZGEOM::CheckPointLoad(ZCheckPointBuffer &)
            .data:005737C8                 .word _ZN5ZGEOM8ActivateEb  # ZGEOM::Activate(bool)
            .data:005737CC                 .word _ZN5ZGEOM12MakeInactiveEv  # ZGEOM::MakeInactive(void)
            .data:005737D0                 .word _ZN5ZGEOM10MakeActiveEv  # ZGEOM::MakeActive(void)
            .data:005737D4                 .word _ZN7ZSTDOBJ16GetBoundTreeTypeEv  # ZSTDOBJ::GetBoundTreeType(void)
            .data:005737D8                 .word _ZN9ZIKLNKOBJ16AnimCallBackToIdEM5ZGEOMFbPN9Animation15ActiveAnimationEffjE  # ZIKLNKOBJ::AnimCallBackToId(bool (ZGEOM::*)(Animation::ActiveAnimation *,float,float,uint))
            .data:005737DC                 .word _ZN9ZIKLNKOBJ18AnimCallBackFromIdEi  # ZIKLNKOBJ::AnimCallBackFromId(int)
            .data:005737E0                 .word _ZN5ZGEOM14CameraMessagesEb  # ZGEOM::CameraMessages(bool)
            .data:005737E4                 .word _ZN5ZGEOM12CreateExDataEv  # ZGEOM::CreateExData(void)
            .data:005737E8                 .word _ZN5ZGEOM10FreeExDataEv  # ZGEOM::FreeExData(void)
            .data:005737EC                 .word _ZN5ZGEOM10CopyExDataEPKS_  # ZGEOM::CopyExData(ZGEOM const*)
            .data:005737F0                 .word _ZNK5ZGEOM12GetChunkDataEi  # ZGEOM::GetChunkData(int)
            .data:005737F4                 .word _ZNK5ZGEOM12RecurGetNextEPPK9ZBaseGeom  # ZGEOM::RecurGetNext(ZBaseGeom const**)
            .data:005737F8                 .word _ZN5ZGEOM24DisableParentBoundAdjustEv  # ZGEOM::DisableParentBoundAdjust(void)
            .data:005737FC                 .word _ZN5ZGEOM12ExpandBoundsEPfS0_S0_P9ZBaseGeom  # ZGEOM::ExpandBounds(float *,float *,float *,ZBaseGeom *)
            .data:00573800                 .word _ZN5ZGEOM6SetMatEPKf  # ZGEOM::SetMat(float const*)
            .data:00573804                 .word _ZN5ZGEOM6SetPosEPKf  # ZGEOM::SetPos(float const*)
            .data:00573808                 .word _ZN5ZGEOM9SetMatPosEPKfS1_  # ZGEOM::SetMatPos(float const*,float const*)
            .data:0057380C                 .word _ZN6ZActor16SetWorldPositionEPKf  # ZActor::SetWorldPosition(float const*)
            .data:00573810                 .word _ZN6ZActor9SetRootTMEPKfS1_  # ZActor::SetRootTM(float const*,float const*)
            .data:00573814                 .word _ZN5ZGEOM7DisplayEb  # ZGEOM::Display(bool)
            .data:00573818                 .word _ZN7ZSTDOBJ6SelectEb  # ZSTDOBJ::Select(bool)
            .data:0057381C                 .word _ZN6ZActor4HideEb  # ZActor::Hide(bool)
            .data:00573820                 .word _ZN5ZGEOM13HideRecursiveEb  # ZGEOM::HideRecursive(bool)
            .data:00573824                 .word _ZN5ZGEOM6FreezeEb  # ZGEOM::Freeze(bool)
            .data:00573828                 .word _ZN7ZSTDOBJ9DispBoundEb  # ZSTDOBJ::DispBound(bool)
            .data:0057382C                 .word _ZN5ZGEOM9SetMovingEb  # ZGEOM::SetMoving(bool)
            .data:00573830                 .word _ZN7ZSTDOBJ17RequestCustomDrawEv  # ZSTDOBJ::RequestCustomDraw(void)
            .data:00573834                 .word _ZN5ZGEOM12HasOwnerDrawEv  # ZGEOM::HasOwnerDraw(void)
            .data:00573838                 .word _ZN5ZGEOM9OwnerDrawEP9ZBaseGeomjP11ZDrawBufferP7ZCAMERAPKfS7_PKv  # ZGEOM::OwnerDraw(ZBaseGeom *,uint,ZDrawBuffer *,ZCAMERA *,float const*,float const*,void const*)
            .data:0057383C                 .word _ZN5ZGEOM22CorrectOwnerDrawMatrixEPfS0_P9ZBaseGeomj  # ZGEOM::CorrectOwnerDrawMatrix(float *,float *,ZBaseGeom *,uint)
            .data:00573840                 .word _ZNK5ZGEOM26CorrectOwnerDrawPartMatrixEP7ZMatrixP9ZBaseGeomP5ZBone  # ZGEOM::CorrectOwnerDrawPartMatrix(ZMatrix *,ZBaseGeom *,ZBone *)
            .data:00573844                 .word _ZN5ZGEOM21WantDrawBufferControlEv  # ZGEOM::WantDrawBufferControl(void)
            .data:00573848                 .word _ZN5ZGEOM10DrawUpdateEv  # ZGEOM::DrawUpdate(void)
            .data:0057384C                 .word _ZN5ZGEOM20DrawBufferViewUpdateEP11ZDrawBufferP12ZCameraSpace  # ZGEOM::DrawBufferViewUpdate(ZDrawBuffer *,ZCameraSpace *)
            .data:00573850                 .word _ZN5ZGEOM20DrawBufferViewUpdateEP11ZDrawBufferP9ZBaseGeomj  # ZGEOM::DrawBufferViewUpdate(ZDrawBuffer *,ZBaseGeom *,uint)
            .data:00573854                 .word _ZNK9ZHM3Actor29WantViewPrimHideUnhideRequestEv  # ZHM3Actor::WantViewPrimHideUnhideRequest(void)
            .data:00573858                 .word _ZNK9ZHM3Actor16WantViewPrimHideEhb  # ZHM3Actor::WantViewPrimHide(uchar,bool)
            .data:0057385C                 .word _ZNK7ZLNKOBJ23WantViewPrimHideMirrorsEh  # ZLNKOBJ::WantViewPrimHideMirrors(uchar)
            .data:00573860                 .word _ZNK5ZGEOM17WantViewUseAllLODEv  # ZGEOM::WantViewUseAllLOD(void)
            .data:00573864                 .word _ZNK7ZLNKOBJ18GetLODMaskOverrideEv  # ZLNKOBJ::GetLODMaskOverride(void)
            .data:00573868                 .word _ZN5ZGEOM15GetSortPriorityEv  # ZGEOM::GetSortPriority(void)
            .data:0057386C                 .word _ZN5ZGEOM10CopyEventsEPKS_  # ZGEOM::CopyEvents(ZGEOM const*)
            .data:00573870                 .word _ZNK5ZGEOM9FindEventEPKc  # ZGEOM::FindEvent(char const*)
            .data:00573874                 .word _ZN5ZGEOM12GetEventDataEPc  # ZGEOM::GetEventData(char *)
            .data:00573878                 .word _ZN5ZGEOM8AddEventEPKc  # ZGEOM::AddEvent(char const*)
            .data:0057387C                 .word _ZN5ZGEOM11AttachEventER10ZEventBase  # ZGEOM::AttachEvent(ZEventBase &)
            .data:00573880                 .word _ZN5ZGEOM15EnableClassCallEj  # ZGEOM::EnableClassCall(uint)
            .data:00573884                 .word _ZN5ZGEOM16DisableClassCallEj  # ZGEOM::DisableClassCall(uint)
            .data:00573888                 .word _ZN5ZGEOM21SetClassTimerIntervalEf  # ZGEOM::SetClassTimerInterval(float)
            .data:0057388C                 .word _ZN5ZGEOM10CallEventsEiPviPS_  # ZGEOM::CallEvents(int,void *,int,ZGEOM*)
            .data:00573890                 .word _ZN5ZGEOM11SendCommandEPS_tPv  # ZGEOM::SendCommand(ZGEOM*,ushort,void *)
            .data:00573894                 .word _ZN5ZGEOM11SendCommandEjtPv  # ZGEOM::SendCommand(uint,ushort,void *)
            .data:00573898                 .word _ZN5ZGEOM11SendCommandEtPvPS_  # ZGEOM::SendCommand(ushort,void *,ZGEOM*)
            .data:0057389C                 .word _ZN5ZGEOM20SendCommandRecursiveEtPvPS_  # ZGEOM::SendCommandRecursive(ushort,void *,ZGEOM*)
            .data:005738A0                 .word _ZN5ZGEOM20SendCommandRecursiveEjtPv  # ZGEOM::SendCommandRecursive(uint,ushort,void *)
            .data:005738A4                 .word _ZN5ZGEOM10FreeEventsEv  # ZGEOM::FreeEvents(void)
            .data:005738A8                 .word _ZN5ZGEOM9FreeEventEP10ZEventBase  # ZGEOM::FreeEvent(ZEventBase *)
            .data:005738AC                 .word _ZN5ZGEOM9FreeEventEPKc  # ZGEOM::FreeEvent(char const*)
            .data:005738B0                 .word _ZN5ZGEOM19RemoveEventFromListEP10ZEventBase  # ZGEOM::RemoveEventFromList(ZEventBase *)
            .data:005738B4                 .word _ZN5ZGEOM16RegisterInstanceEj  # ZGEOM::RegisterInstance(uint)
            .data:005738B8                 .word _ZN9ZHM3Actor9ClassInitEv  # ZHM3Actor::ClassInit(void)
            .data:005738BC                 .word _ZN9ZHM3Actor10ClassInit2Ev  # ZHM3Actor::ClassInit2(void)
            .data:005738C0                 .word _ZN9ZHM3Actor13PostClassInitEv  # ZHM3Actor::PostClassInit(void)
            .data:005738C4                 .word _ZN5ZGEOM14PostClassInit2Ev  # ZGEOM::PostClassInit2(void)
            .data:005738C8                 .word _ZN5ZGEOM12ClassDisplayEv  # ZGEOM::ClassDisplay(void)
            .data:005738CC                 .word _ZN9ZHM3Actor16ClassFrameUpdateEv  # ZHM3Actor::ClassFrameUpdate(void)
            .data:005738D0                 .word _ZN5ZGEOM15ClassTimeUpdateEv  # ZGEOM::ClassTimeUpdate(void)
            .data:005738D4                 .word _ZN9ZHM3Actor12ClassCommandEtPv  # ZHM3Actor::ClassCommand(ushort,void *)
            .data:005738D8                 .word _ZN5ZGEOM17ClassPushPopSceneEb  # ZGEOM::ClassPushPopScene(bool)
            .data:005738DC                 .word _ZN7ZSTDOBJ11ChkLineColiEP4COLIb  # ZSTDOBJ::ChkLineColi(COLI *,bool)
            .data:005738E0                 .word _ZNK7ZSTDOBJ16CheckPointInsideEPKff  # ZSTDOBJ::CheckPointInside(float const*,float)
            .data:005738E4                 .word _ZN5ZGEOM21CheckPointInsideBoundEPKf  # ZGEOM::CheckPointInsideBound(float const*)
            .data:005738E8                 .word _ZN7ZSTDOBJ14CheckBoxInsideEPKfS1_S1_  # ZSTDOBJ::CheckBoxInside(float const*,float const*,float const*)
            .data:005738EC                 .word _ZN5ZGEOM22GetPointInsideDistanceEPKf  # ZGEOM::GetPointInsideDistance(float const*)
            .data:005738F0                 .word _ZN5ZGEOM7VisibleEv  # ZGEOM::Visible(void)
            .data:005738F4                 .word _ZN5ZGEOM9InvisibleEv  # ZGEOM::Invisible(void)
            .data:005738F8                 .word _ZN9ZIKLNKOBJ9PushStateEv  # ZIKLNKOBJ::PushState(void)
            .data:005738FC                 .word _ZN9ZIKLNKOBJ8PopStateEv  # ZIKLNKOBJ::PopState(void)
            .data:00573900                 .word _ZN5ZGEOM13DuplicateDataEPS_  # ZGEOM::DuplicateData(ZGEOM*)
            .data:00573904                 .word _ZN5ZGEOM9DuplicateEP6ZGROUPPKcb  # ZGEOM::Duplicate(ZGROUP *,char const*,bool)
            .data:00573908                 .word _ZN5ZGEOM13DuplicateInitEP6ZGROUPPKfS3_PKcb  # ZGEOM::DuplicateInit(ZGROUP *,float const*,float const*,char const*,bool)
            .data:0057390C                 .word _ZN5ZGEOM19DuplicateToResourceEP6ZGROUPjPKcb  # ZGEOM::DuplicateToResource(ZGROUP *,uint,char const*,bool)
            .data:00573910                 .word _ZN5ZGEOM23DuplicateToResourceInitEP6ZGROUPjPKfS3_PKcb  # ZGEOM::DuplicateToResourceInit(ZGROUP *,uint,float const*,float const*,char const*,bool)
            .data:00573914                 .word _ZN7ZLNKOBJ8CopyDataEPK5ZGEOM  # ZLNKOBJ::CopyData(ZGEOM const*)
            .data:00573918                 .word _ZN5ZGEOM12AddActionMapEP22SInputActionDefinitionPc  # ZGEOM::AddActionMap(SInputActionDefinition *,char *)
            .data:0057391C                 .word _ZN5ZGEOM15RemoveActionMapEPc  # ZGEOM::RemoveActionMap(char *)
            .data:00573920                 .word _ZN5ZGEOM11CheckActionEiPv  # ZGEOM::CheckAction(int,void *)
            .data:00573924                 .word _ZN5ZGEOM11CheckActionEPcPv  # ZGEOM::CheckAction(char *,void *)
            .data:00573928                 .word _ZN5ZGEOM11CheckActionEP12SInputActionPv  # ZGEOM::CheckAction(SInputAction *,void *)
            .data:0057392C                 .word _ZN5ZGEOM11GetActionIDEPc  # ZGEOM::GetActionID(char *)
            .data:00573930                 .word _ZN5ZGEOM12GetActionPtrEi  # ZGEOM::GetActionPtr(int)
            .data:00573934                 .word _ZN5ZGEOM12GetActionPtrEPc  # ZGEOM::GetActionPtr(char *)
            .data:00573938                 .word _ZNK7ZLNKOBJ10IsAttachedEv  # ZLNKOBJ::IsAttached(void)
            .data:0057393C                 .word _ZN7ZLNKOBJ13SetAttachedToEPS_  # ZLNKOBJ::SetAttachedTo(ZLNKOBJ*)
            .data:00573940                 .word _ZNK7ZLNKOBJ13GetAttachedToEv  # ZLNKOBJ::GetAttachedTo(void)
            .data:00573944                 .word _ZNK5ZGEOM13IsLinkBaseObjEv  # ZGEOM::IsLinkBaseObj(void)
            .data:00573948                 .word _ZN6ZActor13OnCameraEnterEv  # ZActor::OnCameraEnter(void)
            .data:0057394C                 .word _ZN7ZLNKOBJ14InitObjMatBoneEv  # ZLNKOBJ::InitObjMatBone(void)
            .data:00573950                 .word _ZN7ZLNKOBJ15CloseObjMatBoneEv  # ZLNKOBJ::CloseObjMatBone(void)
            .data:00573954                 .word _ZNK7ZLNKOBJ7GetAnimEPKc  # ZLNKOBJ::GetAnim(char const*)
            .data:00573958                 .word _ZN7ZLNKOBJ12StopAllAnimsEb  # ZLNKOBJ::StopAllAnims(bool)
            .data:0057395C                 .word _ZN7ZLNKOBJ11StopUBAnimsEv  # ZLNKOBJ::StopUBAnims(void)
            .data:00573960                 .word _ZN7ZLNKOBJ8StopAnimEPN9Animation15ActiveAnimationE  # ZLNKOBJ::StopAnim(Animation::ActiveAnimation *)
            .data:00573964                 .word _ZN6ZActor19ActivateAnimSegmentEPN9Animation6HeaderEifff  # ZActor::ActivateAnimSegment(Animation::Header *,int,float,float,float)
            .data:00573968                 .word _ZN7ZLNKOBJ19ActivateAnimSegmentE20ZAnimVariationHandleifff  # ZLNKOBJ::ActivateAnimSegment(ZAnimVariationHandle,int,float,float,float)
            .data:0057396C                 .word _ZN7ZLNKOBJ12ActivateAnimEPN9Animation6HeaderEi  # ZLNKOBJ::ActivateAnim(Animation::Header *,int)
            .data:00573970                 .word _ZN7ZLNKOBJ24SetActiveAnimDestinationEPKfS1_f  # ZLNKOBJ::SetActiveAnimDestination(float const*,float const*,float)
            .data:00573974                 .word _ZN7ZLNKOBJ15CheckActiveAnimEPN9Animation6HeaderEi  # ZLNKOBJ::CheckActiveAnim(Animation::Header *,int)
            .data:00573978                 .word _ZN7ZLNKOBJ17SetBoneFrameBlendEPN9Animation6HeaderEffbj  # ZLNKOBJ::SetBoneFrameBlend(Animation::Header *,float,float,bool,uint)
            .data:0057397C                 .word _ZN7ZLNKOBJ12SetDualFrameEPN9Animation6HeaderEfS2_fff  # ZLNKOBJ::SetDualFrame(Animation::Header *,float,Animation::Header *,float,float,float)
            .data:00573980                 .word _ZNK7ZLNKOBJ14GroundAnimatedEv  # ZLNKOBJ::GroundAnimated(void)
            .data:00573984                 .word _ZN7ZLNKOBJ9OnMetaKeyEPN9Animation15ActiveAnimationEPNS0_8ZMetaKeyEPKc  # ZLNKOBJ::OnMetaKey(Animation::ActiveAnimation *,Animation::ZMetaKey *,char const*)
            .data:00573988                 .word _ZN7ZLNKOBJ16ActivatePoseAnimEPcfjf  # ZLNKOBJ::ActivatePoseAnim(char *,float,uint,float)
            .data:0057398C                 .word _ZN7ZLNKOBJ12StopPoseAnimEjb  # ZLNKOBJ::StopPoseAnim(uint,bool)
            .data:00573990                 .word _ZN7ZLNKOBJ9StopAudioEv  # ZLNKOBJ::StopAudio(void)
            .data:00573994                 .word _ZN7ZLNKOBJ13StopAnimSoundEbib  # ZLNKOBJ::StopAnimSound(bool,int,bool)
            .data:00573998                 .word _ZN7ZLNKOBJ17StopAllAnimSoundsEv  # ZLNKOBJ::StopAllAnimSounds(void)
            .data:0057399C                 .word _ZNK7ZLNKOBJ18CheckLineCollisionEPfPKfS2_  # ZLNKOBJ::CheckLineCollision(float *,float const*,float const*)
            .data:005739A0                 .word _ZNK7ZLNKOBJ18CheckLineCollisionEPfPKfS2_S0_  # ZLNKOBJ::CheckLineCollision(float *,float const*,float const*,float *)
            .data:005739A4                 .word _ZNK7ZLNKOBJ17CheckBoxCollisionEPKfS1_S1_  # ZLNKOBJ::CheckBoxCollision(float const*,float const*,float const*)
            .data:005739A8                 .word _ZN7ZLNKOBJ13Use2SkeletonsEv  # ZLNKOBJ::Use2Skeletons(void)
            .data:005739AC                 .word _ZN9ZHM3Actor12LocalStateIKEv  # ZHM3Actor::LocalStateIK(void)
            .data:005739B0                 .word _ZNK9ZIKLNKOBJ15GetDefaultBonesEP5ZBonej  # ZIKLNKOBJ::GetDefaultBones(ZBone *,uint)
            .data:005739B4                 .word _ZN9ZIKLNKOBJ15SetDefaultBonesEPK5ZBonePK15SBoneDefinition  # ZIKLNKOBJ::SetDefaultBones(ZBone const*,SBoneDefinition const*)
            .data:005739B8                 .word _ZN7ZLNKOBJ17GetAnimDeltaBonesEPN9Animation6HeaderE  # ZLNKOBJ::GetAnimDeltaBones(Animation::Header *)
            .data:005739BC                 .word _ZNK7ZLNKOBJ13GetBoneMatPosEPfS0_j  # ZLNKOBJ::GetBoneMatPos(float *,float *,uint)
            .data:005739C0                 .word _ZN7ZLNKOBJ20AttachBaseGeomToBoneEPK9ZBaseGeomjPKfS4_  # ZLNKOBJ::AttachBaseGeomToBone(ZBaseGeom const*,uint,float const*,float const*)
            .data:005739C4                 .word _ZN7ZLNKOBJ22DetachBaseGeomFromBoneEPK9ZBaseGeomj  # ZLNKOBJ::DetachBaseGeomFromBone(ZBaseGeom const*,uint)
            .data:005739C8                 .word _ZN7ZLNKOBJ25GetAttachedBaseGeomBoneIdEPK9ZBaseGeom  # ZLNKOBJ::GetAttachedBaseGeomBoneId(ZBaseGeom const*)
            .data:005739CC                 .word _ZN7ZLNKOBJ23GetGroundBoneAnimMatPosERA9_fRA3_fPN9Animation6HeaderEfb  # ZLNKOBJ::GetGroundBoneAnimMatPos(float (&)[9],float (&)[3],Animation::Header *,float,bool)
            .data:005739D0                 .word _ZN7ZLNKOBJ24GetGroundBoneDeltaMatPosERA9_fRA3_fPN9Animation6HeaderEff  # ZLNKOBJ::GetGroundBoneDeltaMatPos(float (&)[9],float (&)[3],Animation::Header *,float,float)
            .data:005739D4                 .word _ZNK7ZLNKOBJ21GetAttachedGeomMatPosEPK9ZBaseGeomPfS3_  # ZLNKOBJ::GetAttachedGeomMatPos(ZBaseGeom const*,float *,float *)
            .data:005739D8                 .word _ZN7ZLNKOBJ11DisplayBoneEjb  # ZLNKOBJ::DisplayBone(uint,bool)
            .data:005739DC                 .word _ZNK7ZLNKOBJ14GetFocusMatPosEPfS0_  # ZLNKOBJ::GetFocusMatPos(float *,float *)
            .data:005739E0                 .word _ZN7ZLNKOBJ15DisplayAllBonesEb  # ZLNKOBJ::DisplayAllBones(bool)
            .data:005739E4                 .word _ZN7ZLNKOBJ18GetRootFocusMatPosEPfS0_  # ZLNKOBJ::GetRootFocusMatPos(float *,float *)
            .data:005739E8                 .word _ZNK7ZLNKOBJ15GetBoneNrFromIdEh  # ZLNKOBJ::GetBoneNrFromId(uchar)
            .data:005739EC                 .word _ZNK7ZLNKOBJ16GetBoneFromPointEPKf  # ZLNKOBJ::GetBoneFromPoint(float const*)
            .data:005739F0                 .word _ZNK7ZLNKOBJ17GetBoneNrFromNameEPKc  # ZLNKOBJ::GetBoneNrFromName(char const*)
            .data:005739F4                 .word _ZNK7ZLNKOBJ11GetBoneNameEi  # ZLNKOBJ::GetBoneName(int)
            .data:005739F8                 .word _ZNK7ZLNKOBJ17GetOrigLocalBonesEv  # ZLNKOBJ::GetOrigLocalBones(void)
            .data:005739FC                 .word _ZNK7ZLNKOBJ18GetBoneDefinitionsEv  # ZLNKOBJ::GetBoneDefinitions(void)
            .data:00573A00                 .word _ZN9ZIKLNKOBJ16CopyGeometryFromEP5ZGEOM  # ZIKLNKOBJ::CopyGeometryFrom(ZGEOM *)
            .data:00573A04                 .word _ZN7ZLNKOBJ16CopyGeometryFromEj  # ZLNKOBJ::CopyGeometryFrom(uint)
            .data:00573A08                 .word _ZN7ZLNKOBJ12CopyPoseFromEPS_  # ZLNKOBJ::CopyPoseFrom(ZLNKOBJ*)
            .data:00573A0C                 .word _ZN7ZLNKOBJ10ChangeMeshEP6ZGROUP  # ZLNKOBJ::ChangeMesh(ZGROUP *)
            .data:00573A10                 .word _ZNK7ZLNKOBJ17PrintAllBoneNamesEv  # ZLNKOBJ::PrintAllBoneNames(void)
            .data:00573A14                 .word _ZN7ZLNKOBJ14SetCutSequenceEb  # ZLNKOBJ::SetCutSequence(bool)
            .data:00573A18                 .word _ZN6ZActor12MoveToMatPosEPKfS1_  # ZActor::MoveToMatPos(float const*,float const*)
            .data:00573A1C                 .word _ZN7ZLNKOBJ15SetRootTMParentEPfS0_  # ZLNKOBJ::SetRootTMParent(float *,float *)
            .data:00573A20                 .word _ZN7ZLNKOBJ13EventCallBackEPN9Animation15ActiveAnimationEffPv  # ZLNKOBJ::EventCallBack(Animation::ActiveAnimation *,float,float,void *)
            .data:00573A24                 .word _ZN10ZLNKWHANDS8OnMovingEv  # ZLNKWHANDS::OnMoving(void)
            .data:00573A28                 .word _ZN10ZLNKWHANDS7OnMovedEv  # ZLNKWHANDS::OnMoved(void)
            .data:00573A2C                 .word _ZNK7ZLNKOBJ16CalcTightCenSizeEPfS0_  # ZLNKOBJ::CalcTightCenSize(float *,float *)
            .data:00573A30                 .word _ZNK9ZIKLNKOBJ22CalcShadowProjectPlaneEPfPKfS2_  # ZIKLNKOBJ::CalcShadowProjectPlane(float *,float const*,float const*)
            .data:00573A34                 .word _ZNK7ZLNKOBJ14GetBoneControlEi  # ZLNKOBJ::GetBoneControl(int)
            .data:00573A38                 .word _ZN7ZLNKOBJ14UpdateGeometryEb  # ZLNKOBJ::UpdateGeometry(bool)
            .data:00573A3C                 .word _ZN7ZLNKOBJ17ResetAllAnimBonesEv  # ZLNKOBJ::ResetAllAnimBones(void)
            .data:00573A40                 .word _ZN7ZLNKOBJ18ResetInactiveBonesEv  # ZLNKOBJ::ResetInactiveBones(void)
            .data:00573A44                 .word _ZN7ZLNKOBJ15ExecuteCallBackEPKc  # ZLNKOBJ::ExecuteCallBack(char const*)
            .data:00573A48                 .word _ZN7ZLNKOBJ13GetBoneVolumeEi  # ZLNKOBJ::GetBoneVolume(int)
            .data:00573A4C                 .word _ZN7ZLNKOBJ11GetBoneSizeEiPf  # ZLNKOBJ::GetBoneSize(int,float *)
            .data:00573A50                 .word _ZN7ZLNKOBJ13GetBoneCenterEiPf  # ZLNKOBJ::GetBoneCenter(int,float *)
            .data:00573A54                 .word _ZN9ZHM3Actor7AnimEndEPN9Animation15ActiveAnimationEi  # ZHM3Actor::AnimEnd(Animation::ActiveAnimation *,int)
            .data:00573A58                 .word _ZN7ZLNKOBJ29UpdateAnimationsAndGroundLinkEf  # ZLNKOBJ::UpdateAnimationsAndGroundLink(float)
            .data:00573A5C                 .word _ZN7ZLNKOBJ19UpdatePoseAnimationEv  # ZLNKOBJ::UpdatePoseAnimation(void)
            .data:00573A60                 .word _ZN7ZLNKOBJ9StartAnimEPN9Animation15ActiveAnimationEi  # ZLNKOBJ::StartAnim(Animation::ActiveAnimation *,int)
            .data:00573A64                 .word _ZNK9ZHM3Actor12IsInElevatorEv  # ZHM3Actor::IsInElevator(void)
            .data:00573A68                 .word _ZNK9ZHM3Actor17GetElevatorDeltaYEv  # ZHM3Actor::GetElevatorDeltaY(void)
            .data:00573A6C                 .word _ZNK9ZHM3Actor14WantBloodOnHitEv  # ZHM3Actor::WantBloodOnHit(void)
            .data:00573A70                 .word _ZN7ZLNKOBJ18LoadSaveAnimationsER17ISerializerStreamb  # ZLNKOBJ::LoadSaveAnimations(ISerializerStream &,bool)
            .data:00573A74                 .word _ZN9ZHM3Actor15ActivateRagdollEbbb  # ZHM3Actor::ActivateRagdoll(bool,bool,bool)
            .data:00573A78                 .word _ZN9ZHM3Actor18CalcAnimRemapNamesEv  # ZHM3Actor::CalcAnimRemapNames(void)
            .data:00573A7C                 .word _ZN9ZIKLNKOBJ8EnableIKEv  # ZIKLNKOBJ::EnableIK(void)
            .data:00573A80                 .word _ZN9ZIKLNKOBJ9DisableIKEv  # ZIKLNKOBJ::DisableIK(void)
            .data:00573A84                 .word _ZN9ZIKLNKOBJ15DisableControlsEv  # ZIKLNKOBJ::DisableControls(void)
            .data:00573A88                 .word _ZN9ZIKLNKOBJ14EnableControlsEv  # ZIKLNKOBJ::EnableControls(void)
            .data:00573A8C                 .word _ZN9ZIKLNKOBJ11ForceFacingEPKf  # ZIKLNKOBJ::ForceFacing(float const*)
            .data:00573A90                 .word _ZN9ZIKLNKOBJ13GetFocalPointEPf  # ZIKLNKOBJ::GetFocalPoint(float *)
            .data:00573A94                 .word _ZN10ZLNKWHANDS5ResetEv  # ZLNKWHANDS::Reset(void)
            .data:00573A98                 .word _ZNK9ZIKLNKOBJ13GetRootCenterEPfS0_  # ZIKLNKOBJ::GetRootCenter(float *,float *)
            .data:00573A9C                 .word _ZN9ZIKLNKOBJ16GetBoneCollisionEPKfS1_  # ZIKLNKOBJ::GetBoneCollision(float const*,float const*)
            .data:00573AA0                 .word _ZNK9ZIKLNKOBJ17GetOwnerMoveSpeedEv  # ZIKLNKOBJ::GetOwnerMoveSpeed(void)
            .data:00573AA4                 .word _ZNK9ZIKLNKOBJ15GetIKBoneMatPosEiPfS0_  # ZIKLNKOBJ::GetIKBoneMatPos(int,float *,float *)
            .data:00573AA8                 .word _ZNK9ZIKLNKOBJ12GetIKBoneMatEiPf  # ZIKLNKOBJ::GetIKBoneMat(int,float *)
            .data:00573AAC                 .word _ZNK9ZIKLNKOBJ12GetIKBonePosEiPf  # ZIKLNKOBJ::GetIKBonePos(int,float *)
            .data:00573AB0                 .word _ZN9ZIKLNKOBJ13SetHeadTargetEPKff  # ZIKLNKOBJ::SetHeadTarget(float const*,float)
            .data:00573AB4                 .word _ZN9ZIKLNKOBJ15ResetHeadTargetEv  # ZIKLNKOBJ::ResetHeadTarget(void)
            .data:00573AB8                 .word _ZNK9ZIKLNKOBJ13HeadBoneIndexEv  # ZIKLNKOBJ::HeadBoneIndex(void)
            .data:00573ABC                 .word _ZNK9ZIKLNKOBJ13NeckBoneIndexEv  # ZIKLNKOBJ::NeckBoneIndex(void)
            .data:00573AC0                 .word _ZNK9ZIKLNKOBJ15PelvisBoneIndexEv  # ZIKLNKOBJ::PelvisBoneIndex(void)
            .data:00573AC4                 .word _ZNK9ZIKLNKOBJ14LHandBoneIndexEv  # ZIKLNKOBJ::LHandBoneIndex(void)
            .data:00573AC8                 .word _ZNK9ZIKLNKOBJ14RHandBoneIndexEv  # ZIKLNKOBJ::RHandBoneIndex(void)
            .data:00573ACC                 .word _ZNK9ZIKLNKOBJ13LToeBoneIndexEv  # ZIKLNKOBJ::LToeBoneIndex(void)
            .data:00573AD0                 .word _ZNK9ZIKLNKOBJ13RToeBoneIndexEv  # ZIKLNKOBJ::RToeBoneIndex(void)
            .data:00573AD4                 .word _ZN9ZIKLNKOBJ14IKCallBackToIdEMS_FvvE  # ZIKLNKOBJ::IKCallBackToId(void (ZIKLNKOBJ::*)(void))
            .data:00573AD8                 .word _ZN9ZIKLNKOBJ16IKCallBackFromIdEi  # ZIKLNKOBJ::IKCallBackFromId(int)
            .data:00573ADC                 .word _ZN9ZIKLNKOBJ15SetFacingTargetEjfMS_FvvE  # ZIKLNKOBJ::SetFacingTarget(uint,float,void (ZIKLNKOBJ::*)(void))
            .data:00573AE0                 .word _ZN9ZIKLNKOBJ18RemoveFacingTargetEfMS_FvvE  # ZIKLNKOBJ::RemoveFacingTarget(float,void (ZIKLNKOBJ::*)(void))
            .data:00573AE4                 .word _ZN9ZIKLNKOBJ13DisableFacingEv  # ZIKLNKOBJ::DisableFacing(void)
            .data:00573AE8                 .word _ZN9ZIKLNKOBJ12EnableFacingEv  # ZIKLNKOBJ::EnableFacing(void)
            .data:00573AEC                 .word _ZN9ZIKLNKOBJ22CreateActionDispatcherEv  # ZIKLNKOBJ::CreateActionDispatcher(void)
            .data:00573AF0                 .word _ZN9ZIKLNKOBJ12RunLnkActionEP10ZLnkAction  # ZIKLNKOBJ::RunLnkAction(ZLnkAction *)
            .data:00573AF4                 .word _ZN9ZIKLNKOBJ22RemoveCurrentLnkActionEv  # ZIKLNKOBJ::RemoveCurrentLnkAction(void)
            .data:00573AF8                 .word _ZN9ZIKLNKOBJ22UpdateCurrentLnkActionEv  # ZIKLNKOBJ::UpdateCurrentLnkAction(void)
            .data:00573AFC                 .word _ZN9ZIKLNKOBJ23CallBackLnkActionTargetEv  # ZIKLNKOBJ::CallBackLnkActionTarget(void)
            .data:00573B00                 .word _ZN9ZIKLNKOBJ21CallBackLnkActionBoneEPN9Animation15ActiveAnimationEffj  # ZIKLNKOBJ::CallBackLnkActionBone(Animation::ActiveAnimation *,float,float,uint)
            .data:00573B04                 .word _ZN9ZHM3Actor15CreateLnkActionEj  # ZHM3Actor::CreateLnkAction(uint)
            .data:00573B08                 .word _ZNK9ZIKLNKOBJ18CurrentLnkActionIdEv  # ZIKLNKOBJ::CurrentLnkActionId(void)
            .data:00573B0C                 .word _ZN9ZIKLNKOBJ19GetCurrentLnkActionEv  # ZIKLNKOBJ::GetCurrentLnkAction(void)
            .data:00573B10                 .word _ZN9ZIKLNKOBJ13DisplayGroundEb  # ZIKLNKOBJ::DisplayGround(bool)
            .data:00573B14                 .word _ZN9ZIKLNKOBJ20EmitFootDustParticleEfi  # ZIKLNKOBJ::EmitFootDustParticle(float,int)
            .data:00573B18                 .word _ZN9ZIKLNKOBJ13MakeFootPrintEb  # ZIKLNKOBJ::MakeFootPrint(bool)
            .data:00573B1C                 .word _ZN9ZIKLNKOBJ10UpdateHeadEv  # ZIKLNKOBJ::UpdateHead(void)
            .data:00573B20                 .word _ZN6ZActor12UpdateFacingEv  # ZActor::UpdateFacing(void)
            .data:00573B24                 .word _ZN10ZLNKWHANDS13UpdateTargetsEv  # ZLNKWHANDS::UpdateTargets(void)
            .data:00573B28                 .word _ZN10ZLNKWHANDS12ResetTargetsEv  # ZLNKWHANDS::ResetTargets(void)
            .data:00573B2C                 .word _ZN10ZLNKWHANDS13RemoveTargetsEv  # ZLNKWHANDS::RemoveTargets(void)
            .data:00573B30                 .word _ZN13ZCTRLIKLNKOBJ13SetControllerENS_10CONTROLLERE  # ZCTRLIKLNKOBJ::SetController(ZCTRLIKLNKOBJ::CONTROLLER)
            .data:00573B34                 .word _ZNK13ZCTRLIKLNKOBJ13GetControllerEv  # ZCTRLIKLNKOBJ::GetController(void)
            .data:00573B38                 .word _ZN13ZCTRLIKLNKOBJ14SetContactGeomEj  # ZCTRLIKLNKOBJ::SetContactGeom(uint)
            .data:00573B3C                 .word _ZNK13ZCTRLIKLNKOBJ14GetContactGeomEv  # ZCTRLIKLNKOBJ::GetContactGeom(void)
            .data:00573B40                 .word _ZN13ZCTRLIKLNKOBJ16CanOperateObjectEP7ZActionPA9_fPA3_fb  # ZCTRLIKLNKOBJ::CanOperateObject(ZAction *,float (*)[9],float (*)[3],bool)
            .data:00573B44                 .word _ZN13ZCTRLIKLNKOBJ13OperateObjectEP7ZAction  # ZCTRLIKLNKOBJ::OperateObject(ZAction *)
            .data:00573B48                 .word _ZNK13ZCTRLIKLNKOBJ9IsRunningEv  # ZCTRLIKLNKOBJ::IsRunning(void)
            .data:00573B4C                 .word _ZNK13ZCTRLIKLNKOBJ10IsSneakingEv  # ZCTRLIKLNKOBJ::IsSneaking(void)
            .data:00573B50                 .word _ZNK6ZActor6IsDeadEv  # ZActor::IsDead(void)
            .data:00573B54                 .word _ZN13ZCTRLIKLNKOBJ16SetLightReceivedEf  # ZCTRLIKLNKOBJ::SetLightReceived(float)
            .data:00573B58                 .word _ZNK13ZCTRLIKLNKOBJ13LightReceivedEv  # ZCTRLIKLNKOBJ::LightReceived(void)
            .data:00573B5C                 .word _ZN13ZCTRLIKLNKOBJ12ReducedSightEj  # ZCTRLIKLNKOBJ::ReducedSight(uint)
            .data:00573B60                 .word _ZN13ZCTRLIKLNKOBJ13GetSeerPosDirEPfS0_  # ZCTRLIKLNKOBJ::GetSeerPosDir(float *,float *)
            .data:00573B64                 .word _ZNK9ZHM3Actor12GetVisionPosEPf  # ZHM3Actor::GetVisionPos(float *)
            .data:00573B68                 .word _ZN10ZLNKWHANDS11AddNearItemEj  # ZLNKWHANDS::AddNearItem(uint)
            .data:00573B6C                 .word _ZN10ZLNKWHANDS14RemoveNearItemEj  # ZLNKWHANDS::RemoveNearItem(uint)
            .data:00573B70                 .word _ZN10ZLNKWHANDS13OnBoidPushingEPS_  # ZLNKWHANDS::OnBoidPushing(ZLNKWHANDS*)
            .data:00573B74                 .word _ZN9ZHM3Actor12OnBoidPushedEP10ZLNKWHANDS  # ZHM3Actor::OnBoidPushed(ZLNKWHANDS *)
            .data:00573B78                 .word _ZN10ZLNKWHANDS20CheckRHandFireTargetEv  # ZLNKWHANDS::CheckRHandFireTarget(void)
            .data:00573B7C                 .word _ZN10ZLNKWHANDS18GetRHandFireTargetEv  # ZLNKWHANDS::GetRHandFireTarget(void)
            .data:00573B80                 .word _ZN10ZLNKWHANDS16SetAimInPositionEb  # ZLNKWHANDS::SetAimInPosition(bool)
            .data:00573B84                 .word _ZN10ZLNKWHANDS9AddActionEij  # ZLNKWHANDS::AddAction(int,uint)
            .data:00573B88                 .word _ZN10ZLNKWHANDS24GetAnimNameFromCollisionEPN9ZIKLNKOBJ16SIKBoneCollisionEbP19ZItemTemplateWeapon  # ZLNKWHANDS::GetAnimNameFromCollision(ZIKLNKOBJ::SIKBoneCollision *,bool,ZItemTemplateWeapon *)
            .data:00573B8C                 .word _ZN10ZLNKWHANDS10ReloadItemEP5ZItem  # ZLNKWHANDS::ReloadItem(ZItem *)
            .data:00573B90                 .word _ZN10ZLNKWHANDS11LetItemFallEP5ZItem  # ZLNKWHANDS::LetItemFall(ZItem *)
            .data:00573B94                 .word _ZNK10ZLNKWHANDS14ShowReloadAnimEP11ZItemWeapon  # ZLNKWHANDS::ShowReloadAnim(ZItemWeapon *)
            .data:00573B98                 .word _ZNK10ZLNKWHANDS15ShowChamberAnimEP11ZItemWeapon  # ZLNKWHANDS::ShowChamberAnim(ZItemWeapon *)
            .data:00573B9C                 .word _ZN10ZLNKWHANDS13ControlPickupEP5ZItem  # ZLNKWHANDS::ControlPickup(ZItem *)
            .data:00573BA0                 .word _ZN10ZLNKWHANDS18ControlUseOneExtraEj  # ZLNKWHANDS::ControlUseOneExtra(uint)
            .data:00573BA4                 .word _ZN10ZLNKWHANDS18ControlUseOneAloneEj  # ZLNKWHANDS::ControlUseOneAlone(uint)
            .data:00573BA8                 .word _ZN10ZLNKWHANDS13ControlUseTwoEjj  # ZLNKWHANDS::ControlUseTwo(uint,uint)
            .data:00573BAC                 .word _ZN10ZLNKWHANDS11ControlDropEP5ZItem  # ZLNKWHANDS::ControlDrop(ZItem *)
            .data:00573BB0                 .word _ZNK10ZLNKWHANDS15GetPickupActionER10HANDPICKUPS1_R11HANDSPICKUP9ITEMHANDSS4_S4_b  # ZLNKWHANDS::GetPickupAction(HANDPICKUP &,HANDPICKUP &,HANDSPICKUP &,ITEMHANDS,ITEMHANDS,ITEMHANDS,bool)
            .data:00573BB4                 .word _ZNK10ZLNKWHANDS18ModifyPickupActionER9ITEMHANDSS1_S1_P13ZItemTemplate  # ZLNKWHANDS::ModifyPickupAction(ITEMHANDS &,ITEMHANDS &,ITEMHANDS &,ZItemTemplate *)
            .data:00573BB8                 .word _ZNK10ZLNKWHANDS15OnlyVerticalAimEv  # ZLNKWHANDS::OnlyVerticalAim(void)
            .data:00573BBC                 .word _ZN9ZHM3Actor10GetAimAnimEPPN9Animation6HeaderERj  # ZHM3Actor::GetAimAnim(Animation::Header **,uint &)
            .data:00573BC0                 .word _ZN9ZHM3Actor14GetPoseEffectsEPfPs  # ZHM3Actor::GetPoseEffects(float *,short *)
            .data:00573BC4                 .word _ZN10ZLNKWHANDS13SetHandTargetEiPff  # ZLNKWHANDS::SetHandTarget(int,float *,float)
            .data:00573BC8                 .word _ZN10ZLNKWHANDS20DontAnimateAttachersEv  # ZLNKWHANDS::DontAnimateAttachers(void)
            .data:00573BCC                 .word _ZN10ZLNKWHANDS19RemoveLHandIKTargetEfM9ZIKLNKOBJFvvE  # ZLNKWHANDS::RemoveLHandIKTarget(float,void (ZIKLNKOBJ::*)(void))
            .data:00573BD0                 .word _ZN10ZLNKWHANDS19RemoveRHandIKTargetEfM9ZIKLNKOBJFvvE  # ZLNKWHANDS::RemoveRHandIKTarget(float,void (ZIKLNKOBJ::*)(void))
            .data:00573BD4                 .word _ZN10ZLNKWHANDS15UpdateAimTargetEv  # ZLNKWHANDS::UpdateAimTarget(void)
            .data:00573BD8                 .word _ZN10ZLNKWHANDS12SetAimTargetEPKffM9ZIKLNKOBJFvvE  # ZLNKWHANDS::SetAimTarget(float const*,float,void (ZIKLNKOBJ::*)(void))
            .data:00573BDC                 .word _ZN10ZLNKWHANDS12SetAimTargetEjPKffM9ZIKLNKOBJFvvEi  # ZLNKWHANDS::SetAimTarget(uint,float const*,float,void (ZIKLNKOBJ::*)(void),int)
            .data:00573BE0                 .word _ZN10ZLNKWHANDS15RemoveAimTargetEfM9ZIKLNKOBJFvvE  # ZLNKWHANDS::RemoveAimTarget(float,void (ZIKLNKOBJ::*)(void))
            .data:00573BE4                 .word _ZN10ZLNKWHANDS15FreezeAimTargetEv  # ZLNKWHANDS::FreezeAimTarget(void)
            .data:00573BE8                 .word _ZN10ZLNKWHANDS10DisableAimEv  # ZLNKWHANDS::DisableAim(void)
            .data:00573BEC                 .word _ZN10ZLNKWHANDS9EnableAimEv  # ZLNKWHANDS::EnableAim(void)
            .data:00573BF0                 .word _ZN10ZLNKWHANDS12GetAimTargetEPf  # ZLNKWHANDS::GetAimTarget(float *)
            .data:00573BF4                 .word _ZNK10ZLNKWHANDS12GetAimTargetEPj  # ZLNKWHANDS::GetAimTarget(uint *)
            .data:00573BF8                 .word _ZNK10ZLNKWHANDS12GetAimTargetEv  # ZLNKWHANDS::GetAimTarget(void)
            .data:00573BFC                 .word _ZN9ZHM3Actor18GetDrawWeaponSpeedEv  # ZHM3Actor::GetDrawWeaponSpeed(void)
            .data:00573C00                 .word _ZNK10ZLNKWHANDS8IsAimingEv  # ZLNKWHANDS::IsAiming(void)
            .data:00573C04                 .word _ZN10ZLNKWHANDS13SetAimAnimPrcEfff  # ZLNKWHANDS::SetAimAnimPrc(float,float,float)
            .data:00573C08                 .word _ZN10ZLNKWHANDS14FireShotNotifyEv  # ZLNKWHANDS::FireShotNotify(void)
            .data:00573C0C                 .word _ZN10ZLNKWHANDS15SetHitAnimationEPKc  # ZLNKWHANDS::SetHitAnimation(char const*)
            .data:00573C10                 .word _ZN10ZLNKWHANDS16SetHitAnimHandleER20ZAnimVariationHandle  # ZLNKWHANDS::SetHitAnimHandle(ZAnimVariationHandle &)
            .data:00573C14                 .word _ZN10ZLNKWHANDS7UseItemEP5ZItemi  # ZLNKWHANDS::UseItem(ZItem *,int)
            .data:00573C18                 .word _ZN10ZLNKWHANDS8DropItemEP5ZItem  # ZLNKWHANDS::DropItem(ZItem *)
            .data:00573C1C                 .word _ZN9ZHM3Actor10PickupItemEP5ZItem  # ZHM3Actor::PickupItem(ZItem *)
            .data:00573C20                 .word _ZN10ZLNKWHANDS6ReloadEP5ZItem  # ZLNKWHANDS::Reload(ZItem *)
            .data:00573C24                 .word _ZN10ZLNKWHANDS7ChamberEP5ZItem  # ZLNKWHANDS::Chamber(ZItem *)
            .data:00573C28                 .word _ZN10ZLNKWHANDS11PerformDropEP5ZItembb  # ZLNKWHANDS::PerformDrop(ZItem *,bool,bool)
            .data:00573C2C                 .word _ZN10ZLNKWHANDS8GetRHandEv  # ZLNKWHANDS::GetRHand(void)
            .data:00573C30                 .word _ZN10ZLNKWHANDS8GetLHandEv  # ZLNKWHANDS::GetLHand(void)
            .data:00573C34                 .word _ZNK10ZLNKWHANDS12GetLHandItemEv  # ZLNKWHANDS::GetLHandItem(void)
            .data:00573C38                 .word _ZNK10ZLNKWHANDS12GetRHandItemEv  # ZLNKWHANDS::GetRHandItem(void)
            .data:00573C3C                 .word _ZNK10ZLNKWHANDS14GetLHandWeaponEv  # ZLNKWHANDS::GetLHandWeapon(void)
            .data:00573C40                 .word _ZNK10ZLNKWHANDS14GetRHandWeaponEv  # ZLNKWHANDS::GetRHandWeapon(void)
            .data:00573C44                 .word _ZNK10ZLNKWHANDS16GetRHandItemTypeEv  # ZLNKWHANDS::GetRHandItemType(void)
            .data:00573C48                 .word _ZNK10ZLNKWHANDS16GetLHandItemTypeEv  # ZLNKWHANDS::GetLHandItemType(void)
            .data:00573C4C                 .word _ZN10ZLNKWHANDS17SetRHandItemStateE9ITEMSTATE  # ZLNKWHANDS::SetRHandItemState(ITEMSTATE)
            .data:00573C50                 .word _ZN10ZLNKWHANDS17SetLHandItemStateE9ITEMSTATE  # ZLNKWHANDS::SetLHandItemState(ITEMSTATE)
            .data:00573C54                 .word _ZN10ZLNKWHANDS16AttachItemToHandEP7ZIKHANDj  # ZLNKWHANDS::AttachItemToHand(ZIKHAND *,uint)
            .data:00573C58                 .word _ZN10ZLNKWHANDS15AttachRHandItemEj  # ZLNKWHANDS::AttachRHandItem(uint)
            .data:00573C5C                 .word _ZN10ZLNKWHANDS15AttachLHandItemEj  # ZLNKWHANDS::AttachLHandItem(uint)
            .data:00573C60                 .word _ZNK10ZLNKWHANDS12GetNearItemsEv  # ZLNKWHANDS::GetNearItems(void)
            .data:00573C64                 .word _ZN10ZLNKWHANDS9SetDialogEb  # ZLNKWHANDS::SetDialog(bool)
            .data:00573C68                 .word _ZNK10ZLNKWHANDS9GetDialogEv  # ZLNKWHANDS::GetDialog(void)
            .data:00573C6C                 .word _ZN10ZLNKWHANDS12DialogListenEi  # ZLNKWHANDS::DialogListen(int)
            .data:00573C70                 .word _ZN10ZLNKWHANDS10DialogTalkEi  # ZLNKWHANDS::DialogTalk(int)
            .data:00573C74                 .word _ZN10ZLNKWHANDS13SlipRHandItemEv  # ZLNKWHANDS::SlipRHandItem(void)
            .data:00573C78                 .word _ZN10ZLNKWHANDS13SlipLHandItemEv  # ZLNKWHANDS::SlipLHandItem(void)
            .data:00573C7C                 .word _ZN10ZLNKWHANDS14ForceLHandItemEP5ZItemb  # ZLNKWHANDS::ForceLHandItem(ZItem *,bool)
            .data:00573C80                 .word _ZN10ZLNKWHANDS14ForceRHandItemEP5ZItemb  # ZLNKWHANDS::ForceRHandItem(ZItem *,bool)
            .data:00573C84                 .word _ZN10ZLNKWHANDS16DestroyRHandItemEv  # ZLNKWHANDS::DestroyRHandItem(void)
            .data:00573C88                 .word _ZN10ZLNKWHANDS16DestroyLHandItemEv  # ZLNKWHANDS::DestroyLHandItem(void)
            .data:00573C8C                 .word _ZN10ZLNKWHANDS10EmptyHandsEv  # ZLNKWHANDS::EmptyHands(void)
            .data:00573C90                 .word _ZN9ZHM3Actor10GetAmmoForEP11ZItemWeapon  # ZHM3Actor::GetAmmoFor(ZItemWeapon *)
            .data:00573C94                 .word _ZN9ZHM3Actor10SetAmmoForEP11ZItemWeaponi  # ZHM3Actor::SetAmmoFor(ZItemWeapon *,int)
            .data:00573C98                 .word _ZN10ZLNKWHANDS16SetLHandIKTargetEPKfS1_fM9ZIKLNKOBJFvvE  # ZLNKWHANDS::SetLHandIKTarget(float const*,float const*,float,void (ZIKLNKOBJ::*)(void))
            .data:00573C9C                 .word _ZN10ZLNKWHANDS16SetRHandIKTargetEPKfS1_fM9ZIKLNKOBJFvvE  # ZLNKWHANDS::SetRHandIKTarget(float const*,float const*,float,void (ZIKLNKOBJ::*)(void))
            .data:00573CA0                 .word _ZN10ZLNKWHANDS17UpdateItemActionsEv  # ZLNKWHANDS::UpdateItemActions(void)
            .data:00573CA4                 .word _ZN10ZLNKWHANDS18CallBackItemActionEv  # ZLNKWHANDS::CallBackItemAction(void)
            .data:00573CA8                 .word _ZN10ZLNKWHANDS12GetNearItemsEv  # ZLNKWHANDS::GetNearItems(void)
            .data:00573CAC                 .word _ZN9ZHM3Actor10PlaySpeechEjib  # ZHM3Actor::PlaySpeech(uint,int,bool)
            .data:00573CB0                 .word _ZN9ZHM3Actor12PlayFootStepEN10ZLNKWHANDS9EFootSideE  # ZHM3Actor::PlayFootStep(ZLNKWHANDS::EFootSide)
            .data:00573CB4                 .word _ZNK10ZLNKWHANDS19IsFirstPersonCameraEv  # ZLNKWHANDS::IsFirstPersonCamera(void)
            .data:00573CB8                 .word _ZN9ZHM3Actor17GetCombatStrengthEv  # ZHM3Actor::GetCombatStrength(void)
            .data:00573CBC                 .word _ZN6ZActor14SetActorRootTMEPKfS1_  # ZActor::SetActorRootTM(float const*,float const*)
            .data:00573CC0                 .word _ZN6ZActor14SetActorPosDirEPKfS1_  # ZActor::SetActorPosDir(float const*,float const*)
            .data:00573CC4                 .word _ZNK6ZActor14GetActorRootTMEPfS0_  # ZActor::GetActorRootTM(float *,float *)
            .data:00573CC8                 .word _ZNK6ZActor21GetActorWorldPositionEPf  # ZActor::GetActorWorldPosition(float *)
            .data:00573CCC                 .word _ZN6ZActor21SetActorWorldPositionEPKf  # ZActor::SetActorWorldPosition(float const*)
            .data:00573CD0                 .word _ZN6ZActor18CanPlayAnimSegmentEPN9Animation6HeaderEffPKfS4_bff  # ZActor::CanPlayAnimSegment(Animation::Header *,float,float,float const*,float const*,bool,float,float)
            .data:00573CD4                 .word _ZNK6ZActor13IsUnconsciousEv  # ZActor::IsUnconscious(void)
            .data:00573CD8                 .word _ZNK6ZActor7IsAwakeEv  # ZActor::IsAwake(void)
            .data:00573CDC                 .word _ZNK6ZActor10IsSleepingEv  # ZActor::IsSleeping(void)
            .data:00573CE0                 .word _ZN6ZActor7SetHeroEj  # ZActor::SetHero(uint)
            .data:00573CE4                 .word _ZN9ZHM3Actor13SetActorStateEN6ZActor10ACTORSTATEE  # ZHM3Actor::SetActorState(ZActor::ACTORSTATE)
            .data:00573CE8                 .word _ZN6ZActor11OnViewEnterEv  # ZActor::OnViewEnter(void)
            .data:00573CEC                 .word _ZN6ZActor11OnViewLeaveEv  # ZActor::OnViewLeave(void)
            .data:00573CF0                 .word _ZNK6ZActor14GetPathFinder4Ev  # ZActor::GetPathFinder4(void)
            .data:00573CF4                 .word _ZN6ZActor16EnablePathFinderEb  # ZActor::EnablePathFinder(bool)
            .data:00573CF8                 .word _ZN6ZActor15SetStopDistanceEf  # ZActor::SetStopDistance(float)
            .data:00573CFC                 .word _ZN6ZActor9SetEndDirEPKf  # ZActor::SetEndDir(float const*)
            .data:00573D00                 .word _ZNK6ZActor9GetEndDirEv  # ZActor::GetEndDir(void)
            .data:00573D04                 .word _ZN6ZActor14MoveToPositionEPKfS1_  # ZActor::MoveToPosition(float const*,float const*)
            .data:00573D08                 .word _ZN6ZActor15SlideToPositionEPKfS1_  # ZActor::SlideToPosition(float const*,float const*)
            .data:00573D0C                 .word _ZN6ZActor13SetPathNotifyEf  # ZActor::SetPathNotify(float)
            .data:00573D10                 .word _ZN6ZActor24SetPathNotifySyncToCycleEb  # ZActor::SetPathNotifySyncToCycle(bool)
            .data:00573D14                 .word _ZN6ZActor12SetEndActionEc  # ZActor::SetEndAction(char)
            .data:00573D18                 .word _ZN6ZActor10RemovePathEhNS_19PATH_CANCEL_REASONSEb  # ZActor::RemovePath(uchar,ZActor::PATH_CANCEL_REASONS,bool)
            .data:00573D1C                 .word _ZN6ZActor12SendPathDoneEb  # ZActor::SendPathDone(bool)
            .data:00573D20                 .word _ZNK6ZActor14GetMoveFromPosEPf  # ZActor::GetMoveFromPos(float *)
            .data:00573D24                 .word _ZN6ZActor19FindNextPathBlockerEv  # ZActor::FindNextPathBlocker(void)
            .data:00573D28                 .word _ZN6ZActor18SetShootIntoGroundEb  # ZActor::SetShootIntoGround(bool)
            .data:00573D2C                 .word _ZN6ZActor28SetShootIntoGroundInFullbodyEb  # ZActor::SetShootIntoGroundInFullbody(bool)
            .data:00573D30                 .word _ZN6ZActor17SetStayInsidePathEb  # ZActor::SetStayInsidePath(bool)
            .data:00573D34                 .word _ZN9ZHM3Actor15ShootIntoGroundEPfbb  # ZHM3Actor::ShootIntoGround(float *,bool,bool)
            .data:00573D38                 .word _ZN6ZActor24ShootIntoGroundRegularlyEPfbbf  # ZActor::ShootIntoGroundRegularly(float *,bool,bool,float)
            .data:00573D3C                 .word _ZN6ZActor22SetMoveSpeedMultiplierEf  # ZActor::SetMoveSpeedMultiplier(float)
            .data:00573D40                 .word _ZN6ZActor20SetPathFinderEnabledEb  # ZActor::SetPathFinderEnabled(bool)
            .data:00573D44                 .word _ZN6ZActor13OnPathRequestEj  # ZActor::OnPathRequest(uint)
            .data:00573D48                 .word _ZN9ZHM3Actor14OnPathFinishedEj  # ZHM3Actor::OnPathFinished(uint)
            .data:00573D4C                 .word _ZN9ZHM3Actor14OnPathCanceledEN6ZActor19PATH_CANCEL_REASONSE  # ZHM3Actor::OnPathCanceled(ZActor::PATH_CANCEL_REASONS)
            .data:00573D50                 .word _ZN9ZHM3Actor24OnPathCanceledLockedDoorEj  # ZHM3Actor::OnPathCanceledLockedDoor(uint)
            .data:00573D54                 .word _ZN9ZHM3Actor11OnPathErrorEN6ZActor11PATH_ERRORSE  # ZHM3Actor::OnPathError(ZActor::PATH_ERRORS)
            .data:00573D58                 .word _ZN6ZActor12OnPathNotifyEv  # ZActor::OnPathNotify(void)
            .data:00573D5C                 .word _ZN9ZHM3Actor9OnNewPathEv  # ZHM3Actor::OnNewPath(void)
            .data:00573D60                 .word _ZN9ZHM3Actor7OnSoundEP6REFTAB  # ZHM3Actor::OnSound(REFTAB *)
            .data:00573D64                 .word _ZN9ZHM3Actor3DieEv  # ZHM3Actor::Die(void)
            .data:00573D68                 .word _ZN9ZHM3Actor10DieByForceEPKfS1_fj  # ZHM3Actor::DieByForce(float const*,float const*,float,uint)
            .data:00573D6C                 .word _ZN6ZActor9ResurrectEv  # ZActor::Resurrect(void)
            .data:00573D70                 .word _ZN6ZActor8KnockoutEv  # ZActor::Knockout(void)
            .data:00573D74                 .word _ZN6ZActor6ReviveEv  # ZActor::Revive(void)
            .data:00573D78                 .word _ZNK6ZActor13GetKnockedOutEv  # ZActor::GetKnockedOut(void)
            .data:00573D7C                 .word _ZNK6ZActor12GetActorListEv  # ZActor::GetActorList(void)
            .data:00573D80                 .word _ZN6ZActor23SetDisableIdleAnimationEb  # ZActor::SetDisableIdleAnimation(bool)
            .data:00573D84                 .word _ZN6ZActor18GetAudibleRoomListEv  # ZActor::GetAudibleRoomList(void)
            .data:00573D88                 .word _ZN9ZHM3Actor6LookAtEj  # ZHM3Actor::LookAt(uint)
            .data:00573D8C                 .word _ZNK6ZActor8IsSeeingEv  # ZActor::IsSeeing(void)
            .data:00573D90                 .word _ZN6ZActor9SetSeeingEb  # ZActor::SetSeeing(bool)
            .data:00573D94                 .word _ZNK6ZActor9IsVisibleEv  # ZActor::IsVisible(void)
            .data:00573D98                 .word _ZN6ZActor10SetVisibleEb  # ZActor::SetVisible(bool)
            .data:00573D9C                 .word _ZN6ZActor12WantToLookAtEP5ZGEOMh  # ZActor::WantToLookAt(ZGEOM *,uchar)
            .data:00573DA0                 .word _ZN9ZHM3Actor19VerifyPlayerVisibleEv  # ZHM3Actor::VerifyPlayerVisible(void)
            .data:00573DA4                 .word _ZN9ZHM3Actor19DeterminePathLookAtEP14LocomotionInfoPfS2_S2_S2_  # ZHM3Actor::DeterminePathLookAt(LocomotionInfo *,float *,float *,float *,float *)
            .data:00573DA8                 .word _ZNK9ZHM3Actor9CanLookAtEP5ZGEOM  # ZHM3Actor::CanLookAt(ZGEOM *)
            .data:00573DAC                 .word _ZNK9ZHM3Actor10IsOnStairsEv  # ZHM3Actor::IsOnStairs(void)
            .data:00573DB0                 .word _ZN6ZActor23UpdatePositionOffScreenEv  # ZActor::UpdatePositionOffScreen(void)
            .data:00573DB4                 .word _ZN6ZActor14UpdatePositionEv  # ZActor::UpdatePosition(void)
            .data:00573DB8                 .word _ZNK9ZHM3Actor16GetCurrentUBAnimEP5ZItemS1_Rb  # ZHM3Actor::GetCurrentUBAnim(ZItem *,ZItem *,bool &)
            .data:00573DBC                 .word _ZN6ZActor19SetHoldWeaponUBAnimEPN9Animation6HeaderE  # ZActor::SetHoldWeaponUBAnim(Animation::Header *)
            .data:00573DC0                 .word _ZN6ZActor13GetAnimOffsetEPKc  # ZActor::GetAnimOffset(char const*)
            .data:00573DC4                 .word _ZN6ZActor13GetAnimOffsetEPN9Animation6HeaderE  # ZActor::GetAnimOffset(Animation::Header *)
            .data:00573DC8                 .word _ZN6ZActor13GetAnimHeaderEj  # ZActor::GetAnimHeader(uint)
            .data:00573DCC                 .word _ZN9ZHM3Actor23ShootIntoGroundCallbackEP19SExtendedImpactInfo  # ZHM3Actor::ShootIntoGroundCallback(SExtendedImpactInfo *)
            .data:00573DD0                 .word _ZN9ZHM3Actor33ActivateAnimSegmentWithCameraBoneEPN9Animation6HeaderEifff  # ZHM3Actor::ActivateAnimSegmentWithCameraBone(Animation::Header *,int,float,float,float)
            .data:00573DD4                 .word _ZN9ZHM3Actor18PlaySpeechResourceEji  # ZHM3Actor::PlaySpeechResource(uint,int)
            .data:00573DD8                 .word _ZN9ZHM3Actor28PlaySpeechResourceWithFilterEjifff  # ZHM3Actor::PlaySpeechResourceWithFilter(uint,int,float,float,float)
            .data:00573DDC                 .word _ZN9ZHM3Actor9SetWeaponEj  # ZHM3Actor::SetWeapon(uint)
            .data:00573DE0                 .word _ZNK9ZHM3Actor9GetWeaponEv  # ZHM3Actor::GetWeapon(void)
            .data:00573DE4                 .word _ZN9ZHM3Actor17SetWeaponTemplateEj  # ZHM3Actor::SetWeaponTemplate(uint)
            .data:00573DE8                 .word _ZNK9ZHM3Actor17GetWeaponTemplateEv  # ZHM3Actor::GetWeaponTemplate(void)
            .data:00573DEC                 .word _ZN9ZHM3Actor10FireWeaponEjbfb  # ZHM3Actor::FireWeapon(uint,bool,float,bool)
            .data:00573DF0                 .word _ZN9ZHM3Actor4BiteEiPfS0_ff  # ZHM3Actor::Bite(int,float *,float *,float,float)
            .data:00573DF4                 .word _ZN9ZHM3Actor5PunchEb  # ZHM3Actor::Punch(bool)
            .data:00573DF8                 .word _ZN9ZHM3Actor13StunGunAttackEv  # ZHM3Actor::StunGunAttack(void)
            .data:00573DFC                 .word _ZN9ZHM3Actor15ThrowKnifeAtRefEjj  # ZHM3Actor::ThrowKnifeAtRef(uint,uint)
            .data:00573E00                 .word _ZN9ZHM3Actor21ActivateRagdollOrAnimEv  # ZHM3Actor::ActivateRagdollOrAnim(void)
            .data:00573E04                 .word _ZN9ZHM3Actor24ActivateRagdollNextFrameEv  # ZHM3Actor::ActivateRagdollNextFrame(void)
            .data:00573E08                 .word _ZN9ZHM3Actor19InitializeHitpointsEf  # ZHM3Actor::InitializeHitpoints(float)
            .data:00573E0C                 .word _ZN9ZHM3Actor12SetHitpointsEf  # ZHM3Actor::SetHitpoints(float)
            .data:00573E10                 .word _ZN9ZHM3Actor12GetHitpointsEv  # ZHM3Actor::GetHitpoints(void)
            .data:00573E14                 .word _ZN9ZHM3Actor10TakeDamageEf  # ZHM3Actor::TakeDamage(float)
            .data:00573E18                 .word _ZN9ZHM3Actor9GetHealthEv  # ZHM3Actor::GetHealth(void)
            .data:00573E1C                 .word _ZN9ZHM3Actor17GetWeaponStrengthEv  # ZHM3Actor::GetWeaponStrength(void)
            .data:00573E20                 .word _ZNK9ZHM3Actor13IsDragEnabledEv  # ZHM3Actor::IsDragEnabled(void)
            .data:00573E24                 .word _ZN9ZHM3Actor15GetItemTemplateEj  # ZHM3Actor::GetItemTemplate(uint)
            .data:00573E28                 .word _ZN9ZHM3Actor26CreateItemFromItemTemplateEj  # ZHM3Actor::CreateItemFromItemTemplate(uint)
            .data:00573E2C                 .word _ZN9ZHM3Actor12ActivateItemEji  # ZHM3Actor::ActivateItem(uint,int)
            .data:00573E30                 .word _ZN9ZHM3Actor11ConcealItemEjb  # ZHM3Actor::ConcealItem(uint,bool)
            .data:00573E34                 .word _ZN9ZHM3Actor19EnablePickupClothesEv  # ZHM3Actor::EnablePickupClothes(void)
            .data:00573E38                 .word _ZN9ZHM3Actor20DisablePickupClothesEv  # ZHM3Actor::DisablePickupClothes(void)
            .data:00573E3C                 .word _ZNK9ZHM3Actor16IsWearingClothesEv  # ZHM3Actor::IsWearingClothes(void)
            .data:00573E40                 .word _ZN9ZHM3Actor22OnHitmanChangedClothesEv  # ZHM3Actor::OnHitmanChangedClothes(void)
            .data:00573E44                 .word _ZN9ZHM3Actor11GetHitmanAsEv  # ZHM3Actor::GetHitmanAs(void)
            .data:00573E48                 .word _ZN9ZHM3Actor18GetActorPropertiesEv  # ZHM3Actor::GetActorProperties(void)
            .data:00573E4C                 .word _ZN9ZHM3Actor15SetScriptUBAnimEPN9Animation6HeaderEb  # ZHM3Actor::SetScriptUBAnim(Animation::Header *,bool)
            .data:00573E50                 .word _ZN9ZHM3Actor16GetDeadBodyFlagsEP7ZLNKOBJ  # ZHM3Actor::GetDeadBodyFlags(ZLNKOBJ *)
            .data:00573E54                 .word _ZN9ZHM3Actor9StartDragEj  # ZHM3Actor::StartDrag(uint)
            .data:00573E58                 .word _ZN9ZHM3Actor7EndDragEv  # ZHM3Actor::EndDrag(void)
            .data:00573E5C                 .word _ZN9ZHM3Actor16GetAutoAimTargetEv  # ZHM3Actor::GetAutoAimTarget(void)
            .data:00573E60                 .word _ZN9ZHM3Actor16SetAutoAimTargetEb  # ZHM3Actor::SetAutoAimTarget(bool)
            .data:00573E64                 .word _ZN9ZHM3Actor16StoreUBHoldAnimsEv  # ZHM3Actor::StoreUBHoldAnims(void)
            .data:00573E68                 .word _ZN9ZHM3Actor19MapUBHoldAnimsToIdxEv  # ZHM3Actor::MapUBHoldAnimsToIdx(void)
            .data:00573E6C                 .word _ZNK9ZHM3Actor21GetItemAssignedUBAnimEP5ZItem  # ZHM3Actor::GetItemAssignedUBAnim(ZItem *)
            .data:00573E70                 .word _ZN9ZHM3Actor8LoadSaveER17ISerializerStream  # ZHM3Actor::LoadSave(ISerializerStream &)
            .data:00573E74                 .word _ZN9ZHM3Actor17ActivateRigidBodyEPK18SRigidBodyVelocity  # ZHM3Actor::ActivateRigidBody(SRigidBodyVelocity const*)
         */
    };
}