#pragma once

#include <Glacier/Glacier.h>
#include <Glacier/ZSysInput.h>

namespace Glacier
{
	struct SActionKeyTableEntry {
		char* psKeyName;
		int iKeyID;
	};
    class ZInputDevice
    {
    public:
    	// vftable
        virtual void Release(bool);
        virtual EDeviceType Type();
        virtual int DigitalCount();
        virtual int DigitalState(int);
        virtual const char* DigitalName(int);
        virtual void DigitalId(char *);
        virtual void DigitalHist(int,int);
        virtual int AnalogCount();
        virtual int AnalogState(int);
        virtual const char* AnalogName(int);
        virtual void AnalogId(char *);
        virtual void AnalogMotion(int);
        virtual void ResetTables(bool);
        virtual void ClearKey(int);
        virtual void RumbleSetPitch(int,float);
        virtual void StartHaptic(uint,float,float,bool);
        virtual void StopHaptics();
        virtual void SetRumbleBGPitch(float,float);
        virtual void Activate();
        virtual void Deactivate();
        virtual const char* GetName();
        virtual void PrintInfo();
        virtual const char* DigitalSystemName(int);
        virtual void UnknownVirtualMethod();
        virtual bool Initialize();
        virtual void Terminate();
        virtual void Update();
        virtual void Acquire(int);
        virtual void Acquire();
        virtual void Unacquire();

        // --------------------------------
	    // Keyboard Wintel size 0x1698
	    // Mouse Wintel size 0x2A4 <<<
	    // Game Control Wintel size 0x2C8
	    // data (total size is 0x2A4)
        EDeviceType m_deviceType;
        int m_field8;
        int m_fieldC;
        int m_field10;
        int m_field14;
        int m_field18;
        int m_field1C;
        int m_field20;
        int m_field24;
        int m_field28;
        int m_field2C;
        int m_field30;
	    SActionKeyTableEntry* m_pDigitalActionsTable;
        int m_field38;
        int m_field3C;
        int m_field40;
        int m_field44;
	    SActionKeyTableEntry* m_pAnalogActionsTable;
        int m_field4C;
        int m_field50;
        int m_field54;
		int   m_vHandlers   [2];
		void* m_vHandlerArgs[2];
		int m_field68;
	    int m_field6C;
	    int m_field70;
	    int m_field74;
	    int m_field78;
	    int m_field7C;
	    int m_field80;
	    int m_field84;
	    int m_field88;
	    int m_field8C;
	    int m_field90;
	    int m_field94;
	    int m_field98;
	    int m_field9C;
	    int m_fieldA0;
	    int m_fieldA4;
	    int m_fieldA8;
	    int m_fieldAC;
	    int m_fieldB0;
	    int m_fieldB4;
	    int m_fieldB8;
	    int m_fieldBC;
	    int m_fieldC0;
	    int m_fieldC4;
	    int m_fieldC8;
	    int m_fieldCC;
	    int m_fieldD0;
	    int m_fieldD4;
	    int m_fieldD8;
	    int m_fieldDC;
	    int m_fieldE0;
	    int m_fieldE4;
	    int m_fieldE8;
	    int m_fieldEC;
	    int m_fieldF0;
	    int m_fieldF4;
	    int m_fieldF8;
	    int m_fieldFC;
	    int m_field100;
	    int m_field104;
	    int m_field108;
	    int m_field10C;
	    int m_field110;
	    int m_field114;
	    int m_field118;
	    int m_field11C;
	    int m_field120;
	    int m_field124;
	    int m_field128;
	    int m_field12C;
	    int m_field130;
	    int m_field134;
	    int m_field138;
	    int m_field13C;
	    int m_field140;
	    int m_field144;
	    int m_field148;
	    int m_field14C;
	    int m_field150;
	    int m_field154;
	    int m_field158;
	    int m_field15C;
	    int m_field160;
	    int m_field164;
	    int m_field168;
	    int m_field16C;
	    int m_field170;
	    int m_field174;
	    int m_field178;
	    int m_field17C;
	    int m_field180;
	    int m_field184;
	    int m_field188;
	    int m_field18C;
	    int m_field190;
	    int m_field194;
	    int m_field198;
	    int m_field19C;
	    int m_field1A0;
	    int m_field1A4;
	    int m_field1A8;
	    int m_field1AC;
	    int m_field1B0;
	    int m_field1B4;
	    int m_field1B8;
	    int m_field1BC;
	    int m_field1C0;
	    int m_field1C4;
	    int m_field1C8;
	    int m_field1CC;
	    int m_field1D0;
	    int m_field1D4;
	    int m_field1D8;
	    int m_field1DC;
	    int m_field1E0;
	    int m_field1E4;
	    int m_field1E8;
	    int m_field1EC;
	    int m_field1F0;
	    int m_field1F4;
	    int m_field1F8;
	    int m_field1FC;
	    int m_field200;
	    int m_field204;
	    int m_field208;
	    int m_field20C;
	    int m_field210;
	    int m_field214;
	    int m_field218;
	    int m_field21C;
	    int m_field220;
	    int m_field224;
	    int m_field228;
	    int m_field22C;
	    int m_field230;
	    int m_field234;
	    int m_field238;
	    int m_field23C;
	    int m_field240;
	    int m_field244;
	    int m_field248;
	    int m_field24C;
	    int m_field250;
	    int m_field254;
	    int m_field258;
	    int m_field25C;
	    int m_field260;
	    int m_field264;
	    int m_field268;
	    int m_field26C;
	    int m_field270;
	    int m_field274;
	    int m_field278;
	    int m_field27C;
	    int m_field280;
	    int m_field284;
	    int m_field288;
	    int m_field28C;
	    int m_field290;
	    int m_field294;
	    int m_field298;
	    int m_field29C;
	    int m_field2A0;
    };
}