name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build_windows:
    name: Build (Windows)
    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Generate projects
      run: |
        mkdir build
        cd build
        cmake --version
        cmake -A Win32 -G "Visual Studio 18 2026" ..
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Prepare artifact
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force artifact

        Copy-Item build/ReHitman/Release/ReHitman.dll artifact/
        Copy-Item build/ReHitman/NVCPL/Release/NVCPL.dll artifact/

    - name: Upload build artifact - ReHitman
      uses: actions/upload-artifact@v7
      with:
        name: "ReHitman"
        path: "artifact"
  
  create_release:
    name: Create release
    needs: [build_windows]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
      
    steps:
    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ReHitman
        path: ReHitman

    - name: Package artifacts for release
      run: |
        zip -r ReHitman-${VERSION}.zip *

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ReHitman-${{ env.VERSION }}.zip